export interface PolicyVersion {
  version: string; changedBy: string; changedAt: string; summary: string;
  status: PolicyStatus;
}
export type PolicyStatus = "draft" | "in-review" | "approved" | "distributed" | "archived";
export interface Policy {
  id: string; policyRef: string; name: string; category: string; owner: string;
  version: string; status: PolicyStatus; frameworks: string[]; reviewed: string;
  nextReview: string; versions: PolicyVersion[]; attestationRequired: boolean;
  departmentTargets: string[]; createdAt: string; updatedAt: string;
  approvedBy?: string; approvedAt?: string; rejectionNotes?: string;
}
export interface AttestationDept {
  dept: string; contact: string; totalPolicies: number; acknowledged: number;
  overdue: number; lastActivity: string; color: string;
}
export interface PolicyTemplate {
  id: string; name: string; category: string; frameworks: string[];
  description: string; pages: number; popularity: number;
}
export interface ControlEntry {
  id: string; name: string; category: string; frameworks: string[];
  description: string; type: "technical" | "administrative" | "physical";
}

// ── 212 Policy Templates ─────────────────────────────────────────────────────
const TEMPLATES: PolicyTemplate[] = [
  // CORE INFORMATION SECURITY (001-020)
  { id:"TPL-001", name:"Information Security Policy",             category:"Security",      frameworks:["ISO 27001","SOC 2","NIST CSF"],            description:"Master ISMS governance policy defining security objectives and accountabilities.",                   pages:12, popularity:98 },
  { id:"TPL-002", name:"Acceptable Use Policy",                   category:"Security",      frameworks:["ISO 27001","SOC 2"],                       description:"Rules governing acceptable use of company IT assets and systems.",                                   pages:8,  popularity:95 },
  { id:"TPL-003", name:"Data Classification Policy",              category:"Data",          frameworks:["ISO 27001","GDPR","NIST"],                  description:"Framework for classifying data — Public, Internal, Confidential, Restricted.",                     pages:10, popularity:92 },
  { id:"TPL-004", name:"Incident Response Policy",                category:"Security",      frameworks:["ISO 27001","NIST CSF","NIS2"],              description:"Roles, process and SLAs for detecting, responding to and recovering from incidents.",               pages:14, popularity:90 },
  { id:"TPL-005", name:"Access Control Policy",                   category:"IAM",           frameworks:["ISO 27001","SOC 2","CIS 18"],               description:"Least-privilege framework covering provisioning, reviews and deprovisioning.",                       pages:11, popularity:88 },
  { id:"TPL-006", name:"Password & Authentication Policy",        category:"IAM",           frameworks:["ISO 27001","NIST SP 800-63"],               description:"Password complexity, rotation, MFA and privileged account standards.",                             pages:7,  popularity:91 },
  { id:"TPL-007", name:"Vulnerability Management Policy",         category:"Security",      frameworks:["ISO 27001","NIST CSF","PCI DSS"],           description:"Scanning cadence, SLA for patching, and CVE escalation procedures.",                               pages:11, popularity:87 },
  { id:"TPL-008", name:"Cryptography & Key Management Policy",    category:"Security",      frameworks:["ISO 27001","PCI DSS","FIPS 140-2"],        description:"Approved algorithms, key lifecycle, CA and HSM requirements.",                                     pages:10, popularity:76 },
  { id:"TPL-009", name:"Security Event Monitoring Policy",        category:"Security",      frameworks:["ISO 27001","SOC 2","NIST"],                 description:"Log collection, SIEM integration, alerting and retention requirements.",                            pages:10, popularity:80 },
  { id:"TPL-010", name:"Asset Management Policy",                 category:"Governance",    frameworks:["ISO 27001","CIS 18"],                       description:"Inventory, ownership, classification and lifecycle management of IT assets.",                        pages:9,  popularity:82 },
  { id:"TPL-011", name:"Email Security Policy",                   category:"Security",      frameworks:["ISO 27001","SOC 2"],                        description:"Email encryption, anti-phishing, SPF/DKIM/DMARC and data loss prevention.",                          pages:7,  popularity:83 },
  { id:"TPL-012", name:"Mobile Device Policy",                    category:"Security",      frameworks:["ISO 27001","NIST"],                         description:"MDM, encryption, remote wipe, and BYOD controls for mobile devices.",                               pages:8,  popularity:79 },
  { id:"TPL-013", name:"Social Media Policy",                     category:"Governance",    frameworks:["ISO 27001"],                                description:"Acceptable social media use, data protection and brand risk controls.",                              pages:5,  popularity:70 },
  { id:"TPL-014", name:"Secure Disposal Policy",                  category:"Physical",      frameworks:["ISO 27001","GDPR","NIST"],                  description:"Secure erasure and destruction of media containing sensitive information.",                           pages:6,  popularity:74 },
  { id:"TPL-015", name:"Security Patch Management Policy",        category:"Security",      frameworks:["ISO 27001","CIS 18","PCI DSS"],             description:"Criticality-based patching SLAs, emergency patch and exception process.",                           pages:9,  popularity:85 },
  { id:"TPL-016", name:"Antimalware Policy",                      category:"Security",      frameworks:["ISO 27001","CIS 18"],                       description:"Endpoint protection deployment, scan schedules and incident escalation.",                            pages:6,  popularity:78 },
  { id:"TPL-017", name:"Firewall Management Policy",              category:"Network",       frameworks:["ISO 27001","PCI DSS","NIST"],               description:"Firewall rule lifecycle, review cadence, emergency changes and documentation.",                     pages:9,  popularity:77 },
  { id:"TPL-018", name:"Security Testing Policy",                 category:"AppSec",        frameworks:["ISO 27001","OWASP SAMM","PCI DSS"],         description:"Penetration testing cadence, scope, methodology and results handling.",                              pages:10, popularity:75 },
  { id:"TPL-019", name:"Security Architecture Policy",            category:"Security",      frameworks:["ISO 27001","NIST CSF","TOGAF"],             description:"Security-by-design principles, architecture review board and patterns.",                             pages:12, popularity:71 },
  { id:"TPL-020", name:"Information Security Risk Policy",        category:"Risk",          frameworks:["ISO 27001","NIST RMF"],                     description:"Risk identification, assessment, treatment and reporting obligations.",                               pages:10, popularity:84 },
  // CLOUD & INFRASTRUCTURE (021-035)
  { id:"TPL-021", name:"Cloud Security Policy",                   category:"Cloud",         frameworks:["ISO 27001","CIS 18","CSA CCM"],             description:"Governance for cloud resource provisioning, configuration and access.",                               pages:14, popularity:86 },
  { id:"TPL-022", name:"Cloud Resource Provisioning Policy",      category:"Cloud",         frameworks:["ISO 27001","CIS 18"],                       description:"Approved cloud services, provisioning controls and tagging standards.",                               pages:8,  popularity:76 },
  { id:"TPL-023", name:"Container Security Policy",               category:"Cloud",         frameworks:["CIS Docker","NIST SP 800-190"],             description:"Container image hardening, registry controls and runtime security.",                                 pages:10, popularity:72 },
  { id:"TPL-024", name:"Kubernetes Security Policy",              category:"Cloud",         frameworks:["CIS Kubernetes","NIST","NSA/CISA"],         description:"Cluster hardening, RBAC, network policies and admission control.",                                   pages:12, popularity:70 },
  { id:"TPL-025", name:"DevOps Security Policy",                  category:"Cloud",         frameworks:["ISO 27001","OWASP SAMM","NIST"],            description:"CI/CD pipeline security gates, secrets management and deployment controls.",                         pages:11, popularity:74 },
  { id:"TPL-026", name:"Infrastructure as Code Security Policy",  category:"Cloud",         frameworks:["ISO 27001","CIS 18"],                       description:"IaC template scanning, drift detection and version control requirements.",                           pages:9,  popularity:69 },
  { id:"TPL-027", name:"Cloud Storage Security Policy",           category:"Cloud",         frameworks:["ISO 27001","CSA CCM","PCI DSS"],            description:"Bucket/blob access controls, encryption, public exposure prevention.",                               pages:8,  popularity:82 },
  { id:"TPL-028", name:"SaaS Governance Policy",                  category:"Cloud",         frameworks:["ISO 27001","SOC 2"],                        description:"SaaS discovery, approval, SSO integration and data residency requirements.",                         pages:9,  popularity:77 },
  { id:"TPL-029", name:"Multi-Cloud Governance Policy",           category:"Cloud",         frameworks:["ISO 27001","CSA CCM"],                      description:"Consistent controls, identity federation and cost governance across clouds.",                         pages:12, popularity:65 },
  { id:"TPL-030", name:"Cloud Backup Policy",                     category:"Cloud",         frameworks:["ISO 27001","SOC 2"],                        description:"Cloud-native backup schedules, cross-region replication and restoration tests.",                     pages:8,  popularity:79 },
  { id:"TPL-031", name:"Cloud Monitoring & Alerting Policy",      category:"Cloud",         frameworks:["ISO 27001","CIS 18"],                       description:"Cloud-native log aggregation, anomaly alerting and incident escalation.",                            pages:9,  popularity:75 },
  { id:"TPL-032", name:"Serverless Security Policy",              category:"Cloud",         frameworks:["OWASP","NIST","CSA CCM"],                   description:"Function permissions, dependency scanning and cold-start security.",                                  pages:8,  popularity:62 },
  { id:"TPL-033", name:"Cloud Vendor Lock-in Policy",             category:"Cloud",         frameworks:["ISO 27001"],                                description:"Portability requirements, exit planning and proprietary service risk.",                               pages:7,  popularity:58 },
  { id:"TPL-034", name:"Cloud Cost Governance Policy",            category:"Cloud",         frameworks:["ISO 27001","FinOps"],                       description:"Budget alerts, resource tagging, rightsizing and cloud spend controls.",                              pages:6,  popularity:63 },
  { id:"TPL-035", name:"Hybrid Cloud Security Policy",            category:"Cloud",         frameworks:["ISO 27001","NIST CSF","CIS 18"],            description:"Network connectivity, identity synchronisation and consistent controls.",                             pages:11, popularity:68 },
  // PRIVACY & DATA PROTECTION (036-055)
  { id:"TPL-036", name:"Data Privacy Policy",                     category:"Privacy",       frameworks:["GDPR","CCPA","PIPEDA"],                     description:"Privacy-by-design principles, data subject rights and transparency.",                                 pages:15, popularity:88 },
  { id:"TPL-037", name:"Data Retention & Destruction Policy",     category:"Privacy",       frameworks:["GDPR","HIPAA","ISO 27001"],                 description:"Retention schedules and secure disposal for all data classifications.",                               pages:9,  popularity:80 },
  { id:"TPL-038", name:"Data Breach Response Policy",             category:"Privacy",       frameworks:["GDPR","HIPAA","NIS2"],                      description:"72-hour notification, containment steps and post-incident review.",                                  pages:11, popularity:85 },
  { id:"TPL-039", name:"Cookie & Tracking Technology Policy",     category:"Privacy",       frameworks:["GDPR","ePrivacy","CCPA"],                   description:"Cookie consent, tracking pixel governance and opt-out mechanisms.",                                   pages:7,  popularity:76 },
  { id:"TPL-040", name:"Data Subject Rights Policy",              category:"Privacy",       frameworks:["GDPR","CCPA","LGPD"],                       description:"DSAR handling, verification, fulfilment timelines and refusal grounds.",                              pages:8,  popularity:83 },
  { id:"TPL-041", name:"Privacy Impact Assessment Policy",        category:"Privacy",       frameworks:["GDPR","ISO 29134","NIST Privacy"],          description:"PIA/DPIA triggers, methodology and documentation requirements.",                                      pages:10, popularity:79 },
  { id:"TPL-042", name:"Data Minimisation Policy",                category:"Privacy",       frameworks:["GDPR","ISO 27001"],                         description:"Limiting data collection to the minimum necessary for stated purpose.",                               pages:6,  popularity:72 },
  { id:"TPL-043", name:"Privacy by Design Policy",                category:"Privacy",       frameworks:["GDPR","ISO 27001","NIST Privacy"],          description:"Embedding privacy controls throughout the product and system lifecycle.",                              pages:8,  popularity:75 },
  { id:"TPL-044", name:"International Data Transfer Policy",      category:"Privacy",       frameworks:["GDPR","SCCs","CBPR"],                       description:"Transfer mechanisms, SCCs, BCRs and adequacy decision compliance.",                                   pages:10, popularity:77 },
  { id:"TPL-045", name:"Employee Privacy Policy",                 category:"Privacy",       frameworks:["GDPR","CCPA"],                              description:"Employee data processing, monitoring boundaries and rights notification.",                             pages:8,  popularity:74 },
  { id:"TPL-046", name:"CCTV & Physical Surveillance Policy",     category:"Privacy",       frameworks:["GDPR","ISO 27001"],                         description:"CCTV deployment, retention, access and data subject request handling.",                               pages:7,  popularity:68 },
  { id:"TPL-047", name:"Marketing Consent & Communication Policy",category:"Privacy",       frameworks:["GDPR","PECR","CAN-SPAM"],                   description:"Opt-in/out mechanisms, preference management and suppression lists.",                                pages:8,  popularity:71 },
  { id:"TPL-048", name:"Children's Data Protection Policy",       category:"Privacy",       frameworks:["GDPR","COPPA","Children's Code"],           description:"Age verification, parental consent and enhanced protections for minors.",                            pages:9,  popularity:65 },
  { id:"TPL-049", name:"Biometric Data Policy",                   category:"Privacy",       frameworks:["GDPR","BIPA","ISO 27001"],                  description:"Biometric data collection, storage, retention and deletion standards.",                               pages:8,  popularity:67 },
  { id:"TPL-050", name:"Health Data Processing Policy",           category:"Privacy",       frameworks:["GDPR","HIPAA","ISO 27001"],                 description:"Special category health data handling, explicit consent and access controls.",                        pages:9,  popularity:70 },
  { id:"TPL-051", name:"AI Data Processing Policy",               category:"Privacy",       frameworks:["GDPR","EU AI Act","ISO 42001"],             description:"Lawful basis for AI training data, bias mitigation and transparency.",                                pages:10, popularity:73 },
  { id:"TPL-052", name:"Anonymisation & Pseudonymisation Policy", category:"Privacy",       frameworks:["GDPR","ISO 29101"],                         description:"Standards for de-identification, re-identification risk and testing.",                                pages:8,  popularity:69 },
  { id:"TPL-053", name:"Cross-Border Data Transfer Policy",       category:"Privacy",       frameworks:["GDPR","APPI","PIPL"],                       description:"Third-country transfer assessments and safeguard implementation.",                                    pages:9,  popularity:71 },
  { id:"TPL-054", name:"Data Ethics Policy",                      category:"Privacy",       frameworks:["GDPR","NIST AI RMF","ISO 42001"],           description:"Ethical data use principles, review board and prohibited practices.",                                  pages:8,  popularity:67 },
  { id:"TPL-055", name:"Records of Processing Activities Policy", category:"Privacy",       frameworks:["GDPR"],                                     description:"Maintaining Art.30 RoPA, update cadence and controller/processor mapping.",                          pages:6,  popularity:75 },
  // ACCESS & IDENTITY MANAGEMENT (056-070)
  { id:"TPL-056", name:"Identity & Access Management Policy",     category:"IAM",           frameworks:["ISO 27001","NIST","SOC 2"],                 description:"Lifecycle management of digital identities from onboarding to termination.",                          pages:12, popularity:87 },
  { id:"TPL-057", name:"Privileged Access Management Policy",     category:"IAM",           frameworks:["ISO 27001","CIS 18","NIST"],                description:"PAM controls, just-in-time access, session recording and approval workflows.",                        pages:11, popularity:85 },
  { id:"TPL-058", name:"Multi-Factor Authentication Policy",      category:"IAM",           frameworks:["ISO 27001","NIST SP 800-63","SOC 2"],       description:"MFA requirements by assurance level, approved methods and exemption process.",                        pages:8,  popularity:89 },
  { id:"TPL-059", name:"Role-Based Access Control Policy",        category:"IAM",           frameworks:["ISO 27001","SOC 2","NIST"],                 description:"Role definition, assignment, review and inheritance governance.",                                     pages:9,  popularity:82 },
  { id:"TPL-060", name:"Segregation of Duties Policy",            category:"IAM",           frameworks:["ISO 27001","SOC 2","PCI DSS"],              description:"Conflicting role identification, compensating controls and exceptions.",                               pages:8,  popularity:79 },
  { id:"TPL-061", name:"Access Review & Recertification Policy",  category:"IAM",           frameworks:["ISO 27001","SOC 2","NIST"],                 description:"Periodic access reviews, automated revocation and escalation procedures.",                            pages:8,  popularity:83 },
  { id:"TPL-062", name:"Remote Access Policy",                    category:"IAM",           frameworks:["ISO 27001","NIST","CIS 18"],                description:"VPN, zero-trust, device compliance and remote session controls.",                                    pages:9,  popularity:84 },
  { id:"TPL-063", name:"Single Sign-On Policy",                   category:"IAM",           frameworks:["ISO 27001","SOC 2"],                        description:"SSO platform governance, federation standards and fallback procedures.",                               pages:7,  popularity:78 },
  { id:"TPL-064", name:"API Access Management Policy",            category:"IAM",           frameworks:["ISO 27001","OWASP API Security"],           description:"API key lifecycle, OAuth scopes, rate limiting and third-party access.",                              pages:9,  popularity:75 },
  { id:"TPL-065", name:"Service Account Policy",                  category:"IAM",           frameworks:["ISO 27001","CIS 18","NIST"],                description:"Service account creation, rotation, least privilege and orphan detection.",                           pages:8,  popularity:77 },
  { id:"TPL-066", name:"Just-In-Time Access Policy",              category:"IAM",           frameworks:["ISO 27001","CIS 18","NIST"],                description:"Temporary elevated access, approval workflow and session time limits.",                               pages:7,  popularity:72 },
  { id:"TPL-067", name:"Zero Trust Network Access Policy",        category:"IAM",           frameworks:["NIST SP 800-207","ISO 27001","CIS 18"],     description:"Never-trust-always-verify architecture, micro-segmentation and identity signals.",                    pages:13, popularity:78 },
  { id:"TPL-068", name:"Guest & Third-Party Access Policy",       category:"IAM",           frameworks:["ISO 27001","SOC 2"],                        description:"Temporary access provisioning, monitoring and automatic expiry.",                                    pages:7,  popularity:74 },
  { id:"TPL-069", name:"Identity Governance & Administration Policy",category:"IAM",        frameworks:["ISO 27001","SOC 2","NIST"],                 description:"IGA platform governance, joiner-mover-leaver automation and audit trails.",                          pages:10, popularity:76 },
  { id:"TPL-070", name:"Password Vault & Secrets Management Policy",category:"IAM",         frameworks:["ISO 27001","CIS 18","NIST"],                description:"Secrets store usage, rotation automation, CI/CD integration.",                                       pages:8,  popularity:73 },
  // RISK MANAGEMENT (071-085)
  { id:"TPL-071", name:"Enterprise Risk Management Policy",       category:"Risk",          frameworks:["ISO 31000","COSO ERM","ISO 27001"],         description:"ERM framework, risk categories, appetite setting and escalation.",                                    pages:15, popularity:84 },
  { id:"TPL-072", name:"Third Party Risk Management Policy",      category:"Risk",          frameworks:["ISO 27001","SOC 2","NIS2"],                 description:"Vendor due diligence, tiering, ongoing monitoring and exit planning.",                                 pages:13, popularity:83 },
  { id:"TPL-073", name:"Risk Appetite & Tolerance Policy",        category:"Risk",          frameworks:["ISO 31000","COSO ERM"],                     description:"Appetite statements, tolerance thresholds and breach escalation process.",                             pages:10, popularity:80 },
  { id:"TPL-074", name:"Risk Register Management Policy",         category:"Risk",          frameworks:["ISO 27001","ISO 31000"],                    description:"Risk register governance, update cadence, ownership and reporting.",                                  pages:8,  popularity:82 },
  { id:"TPL-075", name:"Cyber Risk Quantification Policy",        category:"Risk",          frameworks:["FAIR","ISO 27001","NIST CSF"],              description:"Financial exposure modelling, Monte Carlo simulation and reporting.",                                  pages:12, popularity:74 },
  { id:"TPL-076", name:"Operational Risk Policy",                 category:"Risk",          frameworks:["ISO 31000","Basel III","ISO 27001"],        description:"Operational risk event taxonomy, loss data collection and KRI monitoring.",                           pages:12, popularity:76 },
  { id:"TPL-077", name:"Emerging Technology Risk Policy",         category:"Risk",          frameworks:["ISO 31000","ISO 27001","NIST AI RMF"],      description:"Risk assessment process for new technologies before production adoption.",                             pages:9,  popularity:72 },
  { id:"TPL-078", name:"Climate Risk & ESG Policy",               category:"Risk",          frameworks:["TCFD","ISO 14001"],                         description:"Climate-related financial risk disclosure and scenario analysis.",                                    pages:10, popularity:68 },
  { id:"TPL-079", name:"Residual Risk Acceptance Policy",         category:"Risk",          frameworks:["ISO 27001","ISO 31000"],                    description:"Risk acceptance criteria, approver levels and monitoring obligations.",                                pages:7,  popularity:78 },
  { id:"TPL-080", name:"Risk Treatment Planning Policy",          category:"Risk",          frameworks:["ISO 27001","ISO 31000"],                    description:"Treatment options, owner assignment, timelines and effectiveness review.",                             pages:8,  popularity:79 },
  { id:"TPL-081", name:"Risk Escalation & Reporting Policy",      category:"Risk",          frameworks:["ISO 31000","ISO 27001"],                    description:"Escalation thresholds, reporting cadence and executive dashboard governance.",                         pages:7,  popularity:77 },
  { id:"TPL-082", name:"Concentration Risk Policy",               category:"Risk",          frameworks:["ISO 31000","Basel III"],                    description:"Single-provider dependency limits, geographic exposure and diversification.",                          pages:8,  popularity:67 },
  { id:"TPL-083", name:"Geopolitical Risk Policy",                category:"Risk",          frameworks:["ISO 31000","NIST CSF"],                     description:"Country risk assessment, sanctions screening and data residency implications.",                        pages:9,  popularity:65 },
  { id:"TPL-084", name:"Risk Communication Policy",               category:"Risk",          frameworks:["ISO 31000","ISO 27001"],                    description:"Internal and external risk communication standards and stakeholder maps.",                             pages:7,  popularity:70 },
  { id:"TPL-085", name:"Cyber Insurance Coverage Policy",         category:"Risk",          frameworks:["ISO 27001","NIST CSF"],                     description:"Coverage requirements, policy maintenance and incident notification to insurer.",                      pages:7,  popularity:72 },
  // BUSINESS CONTINUITY & DR (086-097)
  { id:"TPL-086", name:"Business Continuity Policy",              category:"BCP",           frameworks:["ISO 22301","ISO 27001"],                    description:"BCM framework, critical function identification and minimum service levels.",                           pages:16, popularity:85 },
  { id:"TPL-087", name:"Disaster Recovery Policy",                category:"BCP",           frameworks:["ISO 22301","ISO 27001","NIST SP 800-34"],   description:"IT disaster recovery objectives, strategies and test schedules.",                                     pages:14, popularity:84 },
  { id:"TPL-088", name:"IT Continuity Policy",                    category:"BCP",           frameworks:["ISO 27001","ISO 22301"],                    description:"RTO/RPO targets, failover procedures and IT continuity roles.",                                       pages:12, popularity:82 },
  { id:"TPL-089", name:"Crisis Management Policy",                category:"BCP",           frameworks:["ISO 22301","ISO 27001"],                    description:"Crisis team activation, command structure and escalation thresholds.",                                 pages:10, popularity:80 },
  { id:"TPL-090", name:"Business Impact Analysis Policy",         category:"BCP",           frameworks:["ISO 22301","NIST SP 800-34"],               description:"BIA methodology, critical process identification and impact scoring.",                                 pages:10, popularity:79 },
  { id:"TPL-091", name:"Backup & Recovery Policy",                category:"BCP",           frameworks:["ISO 27001","SOC 2","HIPAA"],                description:"Backup frequency, encryption, offsite storage and restoration testing.",                               pages:9,  popularity:83 },
  { id:"TPL-092", name:"Pandemic & Health Emergency Policy",      category:"BCP",           frameworks:["ISO 22301","WHO IHR"],                      description:"Remote work activation, supply chain continuity and workforce safety.",                                pages:9,  popularity:74 },
  { id:"TPL-093", name:"Supply Chain Continuity Policy",          category:"BCP",           frameworks:["ISO 22301","ISO 28000"],                    description:"Critical supplier alternatives, stockpile management and diversification.",                            pages:10, popularity:72 },
  { id:"TPL-094", name:"Tabletop Exercise Policy",                category:"BCP",           frameworks:["ISO 22301","NIST CSF"],                     description:"Exercise programme governance, frequency, scenario design and after-action.",                          pages:7,  popularity:76 },
  { id:"TPL-095", name:"Post-Incident Review Policy",             category:"BCP",           frameworks:["ISO 22301","ISO 27001"],                    description:"PIR process, lessons-learned documentation and corrective action tracking.",                           pages:7,  popularity:78 },
  { id:"TPL-096", name:"Communication During Crisis Policy",      category:"BCP",           frameworks:["ISO 22301"],                                description:"Internal/external communication templates, spokesperson designations.",                                 pages:8,  popularity:73 },
  { id:"TPL-097", name:"Alternate Site Operations Policy",        category:"BCP",           frameworks:["ISO 22301","NIST SP 800-34"],               description:"Hot/warm/cold site selection, activation triggers and staff relocation.",                              pages:9,  popularity:70 },
  // PHYSICAL SECURITY (098-107)
  { id:"TPL-098", name:"Physical Security Policy",                category:"Physical",      frameworks:["ISO 27001","SOC 2"],                        description:"Facility access, perimeter controls, visitor management and CCTV.",                                   pages:10, popularity:75 },
  { id:"TPL-099", name:"Visitor Management Policy",               category:"Physical",      frameworks:["ISO 27001"],                                description:"Visitor registration, escort requirements and badge issuance.",                                        pages:5,  popularity:72 },
  { id:"TPL-100", name:"Clean Desk & Screen Policy",              category:"Physical",      frameworks:["ISO 27001","SOC 2"],                        description:"Workstation lockdown, clear desk enforcement and screen lock timeouts.",                                pages:4,  popularity:74 },
  { id:"TPL-101", name:"Physical Asset Disposal Policy",          category:"Physical",      frameworks:["ISO 27001","GDPR","NIST"],                  description:"Media sanitisation, physical destruction and disposal certificate handling.",                          pages:6,  popularity:73 },
  { id:"TPL-102", name:"Data Centre Access Policy",               category:"Physical",      frameworks:["ISO 27001","SOC 2","PCI DSS"],              description:"Biometric/card access, mantrap procedures and visitor logging.",                                      pages:8,  popularity:77 },
  { id:"TPL-103", name:"Environmental Controls Policy",           category:"Physical",      frameworks:["ISO 27001","TIA-942"],                      description:"Temperature, humidity, fire suppression and UPS governance.",                                         pages:7,  popularity:69 },
  { id:"TPL-104", name:"Equipment Security Policy",               category:"Physical",      frameworks:["ISO 27001","NIST"],                         description:"Hardware tagging, cabling security, off-site equipment controls.",                                    pages:7,  popularity:70 },
  { id:"TPL-105", name:"Secure Area Policy",                      category:"Physical",      frameworks:["ISO 27001"],                                description:"High-security zone access, prohibited items and inspection procedures.",                                pages:6,  popularity:67 },
  { id:"TPL-106", name:"Property & Lock Management Policy",       category:"Physical",      frameworks:["ISO 27001"],                                description:"Key management, lock-change procedures and inventory tracking.",                                       pages:5,  popularity:64 },
  { id:"TPL-107", name:"Workplace Violence Prevention Policy",    category:"Physical",      frameworks:["OSHA","ISO 45001"],                         description:"Threat reporting, de-escalation and emergency lockdown procedures.",                                   pages:7,  popularity:68 },
  // HR & PEOPLE SECURITY (108-119)
  { id:"TPL-108", name:"HR Security Policy",                      category:"HR",            frameworks:["ISO 27001","SOC 2"],                        description:"People security obligations from recruitment through termination.",                                   pages:10, popularity:80 },
  { id:"TPL-109", name:"Employee Background Check Policy",        category:"HR",            frameworks:["ISO 27001","SOC 2"],                        description:"Pre-employment screening scope, consent handling and recurrence.",                                    pages:7,  popularity:76 },
  { id:"TPL-110", name:"Security Awareness Training Policy",      category:"HR",            frameworks:["ISO 27001","SOC 2","NIST AT"],              description:"Annual training mandate, phishing simulation and completion tracking.",                                pages:7,  popularity:81 },
  { id:"TPL-111", name:"Disciplinary Process Policy",             category:"HR",            frameworks:["ISO 27001"],                                description:"Information security breach consequences, proportionality and appeals.",                               pages:6,  popularity:73 },
  { id:"TPL-112", name:"Termination & Offboarding Policy",        category:"HR",            frameworks:["ISO 27001","SOC 2"],                        description:"Access revocation, asset return, exit interview and data retention.",                                 pages:8,  popularity:82 },
  { id:"TPL-113", name:"Conflict of Interest Policy",             category:"HR",            frameworks:["ISO 27001","SOC 2"],                        description:"Declaration requirements, prohibited conduct and annual attestation.",                                pages:6,  popularity:75 },
  { id:"TPL-114", name:"Whistleblower & Speak-Up Policy",         category:"HR",            frameworks:["EU Whistleblower Directive","ISO 37001"],    description:"Anonymous reporting channels, non-retaliation protections and escalation.",                           pages:8,  popularity:74 },
  { id:"TPL-115", name:"Code of Conduct Policy",                  category:"HR",            frameworks:["ISO 37001","ISO 27001"],                    description:"Ethical conduct standards, gifts, hospitality and anti-bribery.",                                     pages:10, popularity:78 },
  { id:"TPL-116", name:"Non-Disclosure Agreement Policy",         category:"HR",            frameworks:["ISO 27001"],                                description:"NDA execution process, scope, duration and breach consequences.",                                     pages:5,  popularity:77 },
  { id:"TPL-117", name:"Insider Threat Policy",                   category:"HR",            frameworks:["ISO 27001","NIST SP 800-53"],               description:"Detection, investigation and response for insider threat scenarios.",                                  pages:12, popularity:70 },
  { id:"TPL-118", name:"Employee Monitoring Policy",              category:"HR",            frameworks:["GDPR","ISO 27001"],                         description:"Permitted monitoring activities, notice requirements and data handling.",                               pages:8,  popularity:72 },
  { id:"TPL-119", name:"Flexible & Remote Work Security Policy",  category:"HR",            frameworks:["ISO 27001","NIST CSF"],                     description:"Home office security requirements, equipment provision and VPN usage.",                                pages:8,  popularity:80 },
  // THIRD PARTY & SUPPLY CHAIN (120-131)
  { id:"TPL-120", name:"Vendor Risk Management Policy",           category:"TPRM",          frameworks:["ISO 27001","SOC 2","NIS2"],                 description:"Vendor risk tiering, due diligence, SLAs and ongoing monitoring.",                                    pages:13, popularity:83 },
  { id:"TPL-121", name:"Third Party Information Security Policy", category:"TPRM",          frameworks:["ISO 27001","SOC 2"],                        description:"Mandatory security requirements flowed down to all third parties.",                                   pages:9,  popularity:80 },
  { id:"TPL-122", name:"Supply Chain Security Policy",            category:"TPRM",          frameworks:["ISO 28000","NIST SP 800-161","DORA"],       description:"Software and hardware supply chain integrity, provenance verification.",                               pages:12, popularity:76 },
  { id:"TPL-123", name:"Software Composition Analysis Policy",    category:"TPRM",          frameworks:["ISO 27001","NIST SP 800-161"],              description:"Open-source and third-party component inventory, licence and vulnerability scanning.",                pages:8,  popularity:74 },
  { id:"TPL-124", name:"Open Source Usage Policy",               category:"TPRM",          frameworks:["ISO 27001","NIST"],                         description:"Approved licences, contribution rules, dependency hygiene.",                                          pages:7,  popularity:72 },
  { id:"TPL-125", name:"Contractor & Consultant Access Policy",   category:"TPRM",          frameworks:["ISO 27001","SOC 2"],                        description:"Temporary access scoping, NDA requirements and background checks.",                                   pages:8,  popularity:78 },
  { id:"TPL-126", name:"Outsourcing Security Policy",             category:"TPRM",          frameworks:["ISO 27001","SOC 2","DORA"],                 description:"Security obligations for outsourced processing, audit rights and exit.",                               pages:10, popularity:76 },
  { id:"TPL-127", name:"Sub-processor Management Policy",         category:"TPRM",          frameworks:["GDPR","ISO 27001"],                         description:"Sub-processor approval, notification and controller obligation flow-down.",                            pages:7,  popularity:74 },
  { id:"TPL-128", name:"Vendor Due Diligence Policy",             category:"TPRM",          frameworks:["ISO 27001","SOC 2"],                        description:"Pre-engagement assessment questionnaire, site visit and scoring.",                                    pages:8,  popularity:77 },
  { id:"TPL-129", name:"Third Party Audit Rights Policy",         category:"TPRM",          frameworks:["ISO 27001","GDPR","DORA"],                  description:"Contractual audit provisions, scheduling and evidence collection.",                                   pages:6,  popularity:70 },
  { id:"TPL-130", name:"Vendor Exit & Transition Policy",         category:"TPRM",          frameworks:["ISO 27001","DORA"],                         description:"Data return/destruction, transition planning and service continuity.",                                 pages:8,  popularity:72 },
  { id:"TPL-131", name:"Fourth-Party Risk Policy",                category:"TPRM",          frameworks:["ISO 27001","DORA"],                         description:"Visibility into sub-contractors of critical third parties and concentration risk.",                   pages:8,  popularity:67 },
  // APPLICATION & SOFTWARE SECURITY (132-146)
  { id:"TPL-132", name:"Secure Software Development Policy",      category:"AppSec",        frameworks:["ISO 27001","OWASP SAMM","NIST SP 800-218"], description:"Security requirements at every SDLC gate from design to deployment.",                                 pages:13, popularity:77 },
  { id:"TPL-133", name:"Code Review & Peer Review Policy",        category:"AppSec",        frameworks:["ISO 27001","OWASP SAMM"],                   description:"Mandatory review triggers, tooling standards and reviewer qualifications.",                           pages:7,  popularity:74 },
  { id:"TPL-134", name:"Static Application Security Testing Policy",category:"AppSec",      frameworks:["ISO 27001","OWASP SAMM","PCI DSS"],         description:"SAST tool requirements, severity thresholds and build-gate enforcement.",                             pages:8,  popularity:75 },
  { id:"TPL-135", name:"Dynamic Application Security Testing Policy",category:"AppSec",     frameworks:["ISO 27001","OWASP SAMM","PCI DSS"],         description:"DAST scan cadence, authenticated testing and defect SLAs.",                                          pages:8,  popularity:73 },
  { id:"TPL-136", name:"API Security Policy",                     category:"AppSec",        frameworks:["ISO 27001","OWASP API Security"],           description:"API design standards, authentication, rate limiting and versioning.",                                 pages:9,  popularity:78 },
  { id:"TPL-137", name:"Web Application Security Policy",         category:"AppSec",        frameworks:["ISO 27001","OWASP ASVS","PCI DSS"],         description:"OWASP Top 10 controls, WAF requirements and secure coding standards.",                                pages:11, popularity:79 },
  { id:"TPL-138", name:"Mobile Application Security Policy",      category:"AppSec",        frameworks:["ISO 27001","OWASP MASVS"],                  description:"Mobile security requirements, certificate pinning and secure storage.",                               pages:10, popularity:74 },
  { id:"TPL-139", name:"DevSecOps Policy",                        category:"AppSec",        frameworks:["ISO 27001","OWASP SAMM","NIST"],            description:"Security automation, shift-left practices and pipeline gate standards.",                               pages:11, popularity:76 },
  { id:"TPL-140", name:"Penetration Testing Policy",              category:"AppSec",        frameworks:["ISO 27001","PCI DSS","CREST"],              description:"Pentest scope, methodology, vendor selection and findings management.",                                pages:10, popularity:75 },
  { id:"TPL-141", name:"Bug Bounty Programme Policy",             category:"AppSec",        frameworks:["ISO 27001","OWASP"],                        description:"Scope definition, reward structure, triage SLA and researcher terms.",                                pages:9,  popularity:70 },
  { id:"TPL-142", name:"Software License Management Policy",      category:"AppSec",        frameworks:["ISO 27001","ITAM"],                         description:"Approved software registry, audit compliance and unlicensed software.",                                pages:7,  popularity:72 },
  { id:"TPL-143", name:"Security Requirements Engineering Policy", category:"AppSec",       frameworks:["ISO 27001","OWASP SAMM"],                   description:"Functional and non-functional security requirements elicitation and review.",                          pages:8,  popularity:69 },
  { id:"TPL-144", name:"Dependency & Package Management Policy",  category:"AppSec",        frameworks:["ISO 27001","NIST SP 800-161"],              description:"Approved registries, private mirrors, integrity verification.",                                       pages:7,  popularity:71 },
  { id:"TPL-145", name:"Secrets & Credential Management Policy",  category:"AppSec",        frameworks:["ISO 27001","CIS 18","OWASP"],               description:"No hard-coded secrets, vault integration, rotation automation.",                                      pages:8,  popularity:80 },
  { id:"TPL-146", name:"Container & Image Hardening Policy",      category:"AppSec",        frameworks:["CIS Docker","NIST SP 800-190"],             description:"Base image standards, build-time scanning and runtime admission.",                                   pages:9,  popularity:72 },
  // AI & EMERGING TECHNOLOGY (147-156)
  { id:"TPL-147", name:"AI Governance Policy",                    category:"AI",            frameworks:["ISO 42001","EU AI Act","NIST AI RMF"],      description:"AI oversight structure, use case approval and prohibited applications.",                               pages:12, popularity:78 },
  { id:"TPL-148", name:"Generative AI Acceptable Use Policy",     category:"AI",            frameworks:["ISO 42001","EU AI Act"],                    description:"Approved GenAI tools, prohibited inputs, output review and data controls.",                            pages:9,  popularity:82 },
  { id:"TPL-149", name:"Machine Learning Model Risk Policy",      category:"AI",            frameworks:["SR 11-7","ISO 42001","NIST AI RMF"],        description:"Model risk tiering, validation, monitoring and retirement standards.",                                 pages:11, popularity:74 },
  { id:"TPL-150", name:"AI Ethics & Fairness Policy",             category:"AI",            frameworks:["ISO 42001","EU AI Act","NIST AI RMF"],      description:"Bias testing, fairness metrics, human oversight and appeal mechanisms.",                               pages:10, popularity:73 },
  { id:"TPL-151", name:"AI Training Data Policy",                 category:"AI",            frameworks:["GDPR","ISO 42001"],                         description:"Lawful basis for training data, provenance, quality and consent.",                                    pages:9,  popularity:71 },
  { id:"TPL-152", name:"Algorithm Transparency Policy",           category:"AI",            frameworks:["EU AI Act","GDPR"],                         description:"Explainability requirements, right to explanation and model documentation.",                            pages:8,  popularity:70 },
  { id:"TPL-153", name:"IoT Security Policy",                     category:"AI",            frameworks:["ETSI EN 303 645","NIST","ISO 27001"],       description:"Device onboarding, firmware update, network isolation and decommission.",                              pages:10, popularity:68 },
  { id:"TPL-154", name:"Blockchain & Distributed Ledger Policy",  category:"AI",            frameworks:["ISO 27001","NIST"],                         description:"Node governance, key custody, smart contract audit and network risk.",                                 pages:9,  popularity:62 },
  { id:"TPL-155", name:"Quantum Computing Risk Policy",           category:"AI",            frameworks:["NIST PQC","ISO 27001"],                     description:"Cryptographic inventory, migration roadmap and quantum-safe algorithms.",                              pages:10, popularity:65 },
  { id:"TPL-156", name:"Robotic Process Automation Security Policy",category:"AI",          frameworks:["ISO 27001","COBIT"],                        description:"RPA bot credentials, audit trails, exception handling and access scope.",                              pages:8,  popularity:64 },
  // AUDIT & MONITORING (157-166)
  { id:"TPL-157", name:"Audit Management Policy",                 category:"Audit",         frameworks:["ISO 27001","SOC 2","ISAE 3000"],            description:"Internal audit programme, scope setting, evidence and report distribution.",                           pages:12, popularity:78 },
  { id:"TPL-158", name:"Internal Audit Charter",                  category:"Audit",         frameworks:["IIA Standards","ISO 27001"],                description:"Audit function mandate, independence, authority and reporting lines.",                                pages:8,  popularity:74 },
  { id:"TPL-159", name:"Log Management Policy",                   category:"Audit",         frameworks:["ISO 27001","SOC 2","PCI DSS"],              description:"Log sources, formats, retention periods and access controls.",                                        pages:9,  popularity:80 },
  { id:"TPL-160", name:"SIEM Governance Policy",                  category:"Audit",         frameworks:["ISO 27001","NIST","SOC 2"],                 description:"SIEM platform governance, use cases, alert tuning and playbooks.",                                    pages:10, popularity:76 },
  { id:"TPL-161", name:"Security Operations Centre Policy",       category:"Audit",         frameworks:["ISO 27001","NIST CSF"],                     description:"SOC operating model, shift structure, escalation and playbook governance.",                           pages:12, popularity:74 },
  { id:"TPL-162", name:"Threat Intelligence Policy",              category:"Audit",         frameworks:["ISO 27001","MITRE ATT&CK","NIST"],          description:"TI platform governance, feed management, sharing and operationalisation.",                            pages:10, popularity:72 },
  { id:"TPL-163", name:"Continuous Control Monitoring Policy",    category:"Audit",         frameworks:["SOC 2","ISO 27001","COBIT"],                description:"Automated control testing, exception alerting and remediation tracking.",                              pages:9,  popularity:74 },
  { id:"TPL-164", name:"Compliance Monitoring Policy",            category:"Audit",         frameworks:["ISO 27001","SOC 2"],                        description:"Regulatory horizon scanning, control effectiveness and reporting obligations.",                         pages:8,  popularity:76 },
  { id:"TPL-165", name:"Threat Hunting Policy",                   category:"Audit",         frameworks:["MITRE ATT&CK","ISO 27001"],                 description:"Proactive hunt methodology, tooling, cadence and findings integration.",                               pages:9,  popularity:69 },
  { id:"TPL-166", name:"IT Audit Policy",                         category:"Audit",         frameworks:["COBIT","ISACA","ISO 27001"],                description:"IT audit scope, evidence standards, sampling and report governance.",                                  pages:10, popularity:72 },
  // INCIDENT RESPONSE & CRISIS (167-178)
  { id:"TPL-167", name:"Cybersecurity Incident Response Policy",  category:"Incident",      frameworks:["NIST SP 800-61","ISO 27001","NIS2"],        description:"IR lifecycle, SIRT roles, containment and eradication procedures.",                                   pages:14, popularity:90 },
  { id:"TPL-168", name:"Ransomware Response Policy",              category:"Incident",      frameworks:["NIST SP 800-61","CISA","ISO 27001"],        description:"Ransomware playbook, no-pay decision tree, negotiation and recovery.",                                pages:12, popularity:85 },
  { id:"TPL-169", name:"DDoS Response Policy",                    category:"Incident",      frameworks:["ISO 27001","NIST CSF"],                     description:"DDoS detection, scrubbing activation, ISP liaison and post-attack review.",                           pages:9,  popularity:76 },
  { id:"TPL-170", name:"Social Engineering Response Policy",      category:"Incident",      frameworks:["ISO 27001","NIST"],                         description:"Phishing, vishing, pretexting response and user reporting procedures.",                               pages:8,  popularity:78 },
  { id:"TPL-171", name:"Crisis Communications Policy",            category:"Incident",      frameworks:["ISO 22301","ISO 27001"],                    description:"Spokesperson designation, message approval and media engagement.",                                    pages:9,  popularity:74 },
  { id:"TPL-172", name:"Executive Crisis Protocol",               category:"Incident",      frameworks:["ISO 22301"],                                description:"Board notification thresholds, war-room setup and decision authority.",                                pages:8,  popularity:73 },
  { id:"TPL-173", name:"Forensics & Evidence Handling Policy",    category:"Incident",      frameworks:["ISO 27001","NIST SP 800-86"],               description:"Chain of custody, evidence preservation, forensic imaging and legal holds.",                          pages:10, popularity:72 },
  { id:"TPL-174", name:"Lessons Learned & PIR Policy",            category:"Incident",      frameworks:["ISO 27001","ISO 22301"],                    description:"Post-incident review process, corrective actions and KPI tracking.",                                  pages:7,  popularity:76 },
  { id:"TPL-175", name:"Insider Threat Response Policy",          category:"Incident",      frameworks:["ISO 27001","NIST SP 800-53"],               description:"Investigation protocol, HR and legal involvement and evidence handling.",                              pages:10, popularity:70 },
  { id:"TPL-176", name:"Supply Chain Compromise Response Policy", category:"Incident",      frameworks:["NIST SP 800-161","ISO 27001"],              description:"Third-party breach response, isolation, notification and recovery.",                                   pages:10, popularity:68 },
  { id:"TPL-177", name:"Nation-State Attack Response Policy",     category:"Incident",      frameworks:["CISA","NIST SP 800-61"],                    description:"Attribution process, government liaison, CISA reporting and hardening.",                               pages:11, popularity:65 },
  { id:"TPL-178", name:"Vulnerability Disclosure Policy",         category:"Incident",      frameworks:["ISO 29147","ISO 27001"],                    description:"Coordinated disclosure process, researcher engagement and patch timelines.",                           pages:8,  popularity:74 },
  // NETWORK & COMMUNICATIONS (179-190)
  { id:"TPL-179", name:"Network Security Policy",                 category:"Network",       frameworks:["ISO 27001","NIST CSF","PCI DSS"],           description:"Network architecture standards, segmentation and access control.",                                   pages:12, popularity:82 },
  { id:"TPL-180", name:"Firewall & Perimeter Security Policy",    category:"Network",       frameworks:["ISO 27001","PCI DSS","CIS 18"],             description:"Firewall rule lifecycle, review cadence and DMZ configuration.",                                     pages:9,  popularity:78 },
  { id:"TPL-181", name:"VPN & Secure Remote Access Policy",       category:"Network",       frameworks:["ISO 27001","NIST","CIS 18"],                description:"VPN client standards, split-tunnelling, MFA and device compliance.",                                 pages:9,  popularity:82 },
  { id:"TPL-182", name:"Wireless Network Security Policy",        category:"Network",       frameworks:["ISO 27001","PCI DSS","CIS 18"],             description:"SSID governance, WPA3 standards, guest isolation and rogue AP detection.",                           pages:8,  popularity:76 },
  { id:"TPL-183", name:"Network Segmentation Policy",             category:"Network",       frameworks:["ISO 27001","PCI DSS","NIST"],               description:"VLAN design, micro-segmentation, east-west traffic controls.",                                       pages:10, popularity:80 },
  { id:"TPL-184", name:"DNS Security Policy",                     category:"Network",       frameworks:["ISO 27001","NIST"],                         description:"DNSSEC implementation, resolver filtering and DNS logging.",                                         pages:7,  popularity:72 },
  { id:"TPL-185", name:"Email & Messaging Security Policy",       category:"Network",       frameworks:["ISO 27001","CIS 18"],                       description:"SPF/DKIM/DMARC, encrypted email, DLP and phishing simulation.",                                     pages:8,  popularity:81 },
  { id:"TPL-186", name:"Web Filtering & Proxy Policy",            category:"Network",       frameworks:["ISO 27001","CIS 18"],                       description:"URL categorisation, SSL inspection and bypassing exception process.",                                pages:7,  popularity:74 },
  { id:"TPL-187", name:"Network Access Control Policy",           category:"Network",       frameworks:["ISO 27001","NIST","CIS 18"],                description:"NAC posture checks, quarantine VLAN, remediation and authentication.",                               pages:9,  popularity:75 },
  { id:"TPL-188", name:"Network Monitoring Policy",               category:"Network",       frameworks:["ISO 27001","SOC 2"],                        description:"NetFlow analysis, IDS/IPS governance, alert tuning and escalation.",                                pages:9,  popularity:74 },
  { id:"TPL-189", name:"DDoS Protection Policy",                  category:"Network",       frameworks:["ISO 27001","NIST CSF"],                     description:"On-premise and cloud-based DDoS scrubbing, threshold setting.",                                      pages:8,  popularity:73 },
  { id:"TPL-190", name:"SD-WAN Security Policy",                  category:"Network",       frameworks:["ISO 27001","NIST"],                         description:"SD-WAN encryption, traffic prioritisation and zero-trust integration.",                               pages:9,  popularity:68 },
  // DATA MANAGEMENT (191-205)
  { id:"TPL-191", name:"Data Governance Policy",                  category:"Data",          frameworks:["ISO 27001","DAMA DMBOK","GDPR"],            description:"Data ownership, stewardship, quality standards and lifecycle.",                                      pages:12, popularity:80 },
  { id:"TPL-192", name:"Database Security Policy",                category:"Data",          frameworks:["ISO 27001","CIS 18","PCI DSS"],             description:"Database hardening, access controls, encryption and activity monitoring.",                            pages:10, popularity:77 },
  { id:"TPL-193", name:"Data Encryption Policy",                  category:"Data",          frameworks:["ISO 27001","PCI DSS","HIPAA"],              description:"Encryption standards for data at rest and in transit, key management.",                               pages:9,  popularity:83 },
  { id:"TPL-194", name:"Data Loss Prevention Policy",             category:"Data",          frameworks:["ISO 27001","GDPR","PCI DSS"],               description:"DLP tool governance, channel controls, incident response and exceptions.",                            pages:10, popularity:81 },
  { id:"TPL-195", name:"Master Data Management Policy",           category:"Data",          frameworks:["ISO 27001","DAMA DMBOK"],                   description:"Golden record governance, deduplication, stewardship and synchronisation.",                          pages:9,  popularity:70 },
  { id:"TPL-196", name:"Data Quality Policy",                     category:"Data",          frameworks:["ISO 27001","DAMA DMBOK"],                   description:"Accuracy, completeness, consistency standards and remediation processes.",                            pages:8,  popularity:71 },
  { id:"TPL-197", name:"Data Sharing Agreement Policy",           category:"Data",          frameworks:["ISO 27001","GDPR"],                         description:"Internal and external data sharing governance, DSA templates and approvals.",                         pages:8,  popularity:76 },
  { id:"TPL-198", name:"Data Sovereignty Policy",                 category:"Data",          frameworks:["GDPR","ISO 27001","PIPL"],                  description:"Data residency requirements, cross-border transfer controls.",                                        pages:9,  popularity:74 },
  { id:"TPL-199", name:"Data Pipeline Security Policy",           category:"Data",          frameworks:["ISO 27001","NIST"],                         description:"ETL/ELT security, transformation logging and data lineage.",                                         pages:8,  popularity:69 },
  { id:"TPL-200", name:"Analytics & BI Governance Policy",        category:"Data",          frameworks:["ISO 27001","GDPR"],                         description:"Self-service BI access, dataset publication and insight sharing.",                                   pages:8,  popularity:70 },
  { id:"TPL-201", name:"Big Data Security Policy",                category:"Data",          frameworks:["ISO 27001","NIST","CSA CCM"],               description:"Data lake access controls, anonymisation and egress monitoring.",                                   pages:10, popularity:68 },
  { id:"TPL-202", name:"Data Catalogue Policy",                   category:"Data",          frameworks:["ISO 27001","DAMA DMBOK"],                   description:"Catalogue governance, metadata standards, access and sensitivity tagging.",                          pages:7,  popularity:67 },
  { id:"TPL-203", name:"Data Lineage Policy",                     category:"Data",          frameworks:["GDPR","DAMA DMBOK"],                        description:"End-to-end data tracing, transformation documentation and audit.",                                   pages:7,  popularity:66 },
  { id:"TPL-204", name:"Data Architecture & Modelling Policy",    category:"Data",          frameworks:["ISO 27001","TOGAF","DAMA DMBOK"],           description:"Architecture review board, model standards and security pattern requirements.",                      pages:10, popularity:65 },
  { id:"TPL-205", name:"Test Data Management Policy",             category:"Data",          frameworks:["GDPR","ISO 27001"],                         description:"Prohibition on production data in non-prod, masking standards.",                                    pages:7,  popularity:79 },
  // IT GOVERNANCE (206-212)
  { id:"TPL-206", name:"IT Governance Policy",                    category:"Governance",    frameworks:["COBIT","ISO 38500","ISO 27001"],            description:"IT steering committee mandate, decision rights and performance reporting.",                           pages:12, popularity:75 },
  { id:"TPL-207", name:"Change Management Policy",                category:"Governance",    frameworks:["ISO 27001","SOC 2","ITIL 4"],               description:"RFC lifecycle, CAB governance, emergency change and rollback.",                                      pages:10, popularity:84 },
  { id:"TPL-208", name:"Configuration Management Policy",         category:"Governance",    frameworks:["ISO 27001","ITIL 4","CIS 18"],              description:"CMDB governance, configuration item standards and drift detection.",                                 pages:9,  popularity:79 },
  { id:"TPL-209", name:"IT Service Management Policy",            category:"Governance",    frameworks:["ITIL 4","ISO 27001","ISO 20000"],           description:"ITSM platform governance, SLA/OLA definitions and escalation.",                                     pages:10, popularity:78 },
  { id:"TPL-210", name:"IT Project Governance Policy",            category:"Governance",    frameworks:["COBIT","PMI PMBOK","ISO 27001"],            description:"Security gates in project lifecycle, CISO engagement and risk sign-off.",                            pages:9,  popularity:76 },
  { id:"TPL-211", name:"Software Development Lifecycle Policy",   category:"Governance",    frameworks:["ISO 27001","OWASP SAMM","NIST"],            description:"SDLC phases, approval gates, review boards and release criteria.",                                   pages:11, popularity:80 },
  { id:"TPL-212", name:"Technical Debt Management Policy",        category:"Governance",    frameworks:["ISO 27001","COBIT"],                        description:"Debt cataloguing, risk scoring, resolution timelines and reporting.",                                 pages:7,  popularity:67 },
];


export class GovernanceService {
  // ── Templates (static reference data — intentionally in-memory) ────────────
  getTemplates(category?: string, framework?: string): PolicyTemplate[] {
    let list = TEMPLATES;
    if (category && category !== "All") list = list.filter(t => t.category === category);
    if (framework) list = list.filter(t => t.frameworks.some(f => f.toLowerCase().includes(framework.toLowerCase())));
    return list.sort((a, b) => b.popularity - a.popularity);
  }
  getTemplate(id: string): PolicyTemplate | undefined { return TEMPLATES.find(t => t.id === id); }
  getTemplateCount(): number { return TEMPLATES.length; }
}

export const governanceService = new GovernanceService();
