// ── Shared Agent & Connector types / data ─────────────────────────────────────
// Imported by both Agents.tsx and Settings.tsx

export type AgentOS = "windows" | "linux" | "macos" | "mobile" | "cloud" | "docker" | "kubernetes" | "aws" | "azure" | "gcp";

export interface ConnDef {
  id: string; name: string; cat: string; color: string; ini: string;
  authType: string; featured: boolean; description: string;
  logoUrl?: string;   // ClearBit logo URL — rendered with ini fallback
  live?: boolean;     // Has a real adapter implementation in the backend
  dataTypes?: string[];
}

// ── Connector Catalog ─────────────────────────────────────────────────────────
export const CATALOG: ConnDef[] = [

  // ── Cloud ──────────────────────────────────────────────────────────────────
  {id:"aws",              name:"Amazon Web Services",         cat:"Cloud",          color:"#FF9900", ini:"A", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/aws.amazon.com",       description:"Security Hub, GuardDuty, Config rules, CloudTrail, IAM findings"},
  {id:"azure",            name:"Microsoft Azure",             cat:"Cloud",          color:"#0078D4", ini:"A", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/azure.microsoft.com",  description:"Subscriptions, Resource Graph, Defender for Cloud, Entra"},
  {id:"gcp",              name:"Google Cloud Platform",       cat:"Cloud",          color:"#4285F4", ini:"G", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/cloud.google.com",     description:"GCP projects, SCC findings, Pub/Sub, GKE, IAM"},
  {id:"oracle-cloud",     name:"Oracle Cloud",                cat:"Cloud",          color:"#F80000", ini:"O", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/oracle.com",           description:"OCI compartments, IAM policies, audit events, security zones"},
  {id:"alibaba-cloud",    name:"Alibaba Cloud",               cat:"Cloud",          color:"#FF6A00", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/alibabacloud.com",     description:"RAM, OSS, ECS security posture, ActionTrail"},
  {id:"digitalocean",     name:"DigitalOcean",                cat:"Cloud",          color:"#0080FF", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/digitalocean.com",     description:"Droplets, Spaces, Kubernetes, alerts, firewall rules"},
  {id:"ibm-cloud",        name:"IBM Cloud",                   cat:"Cloud",          color:"#0F62FE", ini:"I", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/ibm.com",              description:"IBM Cloud IAM, Security & Compliance Center, Activity Tracker"},
  {id:"linode",           name:"Linode / Akamai Cloud",       cat:"Cloud",          color:"#00B050", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/linode.com",           description:"Instances, object storage, Kubernetes, firewall logs"},
  {id:"prisma-cloud",     name:"Palo Alto Prisma Cloud",      cat:"Cloud",          color:"#FA582D", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/paloaltonetworks.com", description:"Prisma Cloud CSPM, container security, IaC scanning, runtime"},
  {id:"cloudflare",       name:"Cloudflare",                  cat:"Cloud",          color:"#F48120", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cloudflare.com",       description:"WAF events, DDoS protection, DNS analytics, Zero Trust, Workers"},
  {id:"vultr",            name:"Vultr",                       cat:"Cloud",          color:"#007BFC", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/vultr.com",            description:"Cloud instances, Kubernetes, object storage, firewall rules"},
  {id:"hetzner",          name:"Hetzner Cloud",               cat:"Cloud",          color:"#D50C2D", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/hetzner.com",          description:"Servers, load balancers, firewall rules, audit log"},
  {id:"scaleway",         name:"Scaleway",                    cat:"Cloud",          color:"#4F0599", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/scaleway.com",         description:"Instances, Kubernetes Kapsule, object storage, IAM"},
  {id:"ovh",              name:"OVHcloud",                    cat:"Cloud",          color:"#123F6D", ini:"O", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/ovhcloud.com",         description:"Dedicated servers, Hosted Private Cloud, Public Cloud logs"},
  {id:"heroku",           name:"Heroku",                      cat:"Cloud",          color:"#430098", ini:"H", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/heroku.com",           description:"Dyno activity, add-on audit, release history, access logs"},
  {id:"vercel",           name:"Vercel",                      cat:"Cloud",          color:"#000000", ini:"▲", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/vercel.com",           description:"Deployment events, edge access logs, environment security"},
  {id:"netlify",          name:"Netlify",                     cat:"Cloud",          color:"#00AD9F", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/netlify.com",          description:"Build logs, deploy events, form submissions, access audit"},

  // ── Identity ───────────────────────────────────────────────────────────────
  {id:"okta",             name:"Okta",                        cat:"Identity",       color:"#007DC1", ini:"O", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/okta.com",             description:"User provisioning, SSO sessions, MFA policy, system log"},
  {id:"entra-id",         name:"Microsoft Entra ID",          cat:"Identity",       color:"#0078D4", ini:"E", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Users, PIM roles, Conditional Access, sign-in risk, MFA"},
  {id:"active-directory", name:"Active Directory",            cat:"Identity",       color:"#0078D4", ini:"⊞", authType:"certificate", featured:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"On-prem AD: users, computers, GPOs, privilege paths, Kerberos"},
  {id:"google-workspace", name:"Google Workspace",            cat:"Identity",       color:"#4285F4", ini:"G", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/google.com",           description:"Workspace users, Drive sharing, Gmail security, Admin SDK"},
  {id:"onelogin",         name:"OneLogin",                    cat:"Identity",       color:"#003580", ini:"O", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/onelogin.com",         description:"SSO events, user lifecycle, MFA enforcement, smart factors"},
  {id:"pingidentity",     name:"PingIdentity",                cat:"Identity",       color:"#E1001A", ini:"P", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/pingidentity.com",     description:"PingFederate, PingOne SSO events, MFA enforcement"},
  {id:"auth0",            name:"Auth0",                       cat:"Identity",       color:"#EB5424", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/auth0.com",            description:"Tenant users, log streams, anomaly detection, MFA"},
  {id:"duo-security",     name:"Duo Security",                cat:"Identity",       color:"#6BBD45", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/duo.com",              description:"MFA events, device trust, bypass codes, admin activity"},
  {id:"sailpoint",        name:"SailPoint IdentityIQ",        cat:"Identity",       color:"#006CB7", ini:"S", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/sailpoint.com",        description:"Identity governance, access certifications, role mining"},
  {id:"forgerock",        name:"ForgeRock",                   cat:"Identity",       color:"#EF5B25", ini:"F", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/forgerock.com",        description:"ForgeRock AM/IDM identity & access management, OAuth"},
  {id:"jumpcloud",        name:"JumpCloud",                   cat:"Identity",       color:"#1C5ECF", ini:"J", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/jumpcloud.com",        description:"Directory-as-a-service, device management, SSO, MFA"},
  {id:"cyberark-identity",name:"CyberArk Identity",           cat:"Identity",       color:"#1A3A5C", ini:"C", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/cyberark.com",         description:"Workforce identity SSO, adaptive MFA, lifecycle management"},
  {id:"saviynt-iga",      name:"Saviynt IGA",                 cat:"Identity",       color:"#2D7DD2", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/saviynt.com",          description:"Identity governance, cloud PAM, access certification"},
  {id:"venafi",           name:"Venafi Machine Identity",     cat:"Identity",       color:"#E8B84B", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/venafi.com",           description:"TLS/SSL certificate lifecycle, code signing, SSH keys"},
  {id:"beyond-identity",  name:"Beyond Identity",             cat:"Identity",       color:"#5045E5", ini:"B", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/beyondidentity.com",   description:"Passwordless MFA, device trust, FIDO2 authentication"},

  // ── EDR/XDR ────────────────────────────────────────────────────────────────
  {id:"crowdstrike",      name:"CrowdStrike Falcon",          cat:"EDR/XDR",        color:"#E01B22", ini:"C", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/crowdstrike.com",      description:"Falcon telemetry, detections, device inventory, identity"},
  {id:"sentinelone",      name:"SentinelOne",                 cat:"EDR/XDR",        color:"#6C3EC5", ini:"S", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/sentinelone.com",      description:"Agents, detections, threats, network quarantine, storyline"},
  {id:"defender",         name:"Microsoft Defender XDR",      cat:"EDR/XDR",        color:"#0078D4", ini:"D", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Endpoints, identity, email, cloud app alerts, XDR signal"},
  {id:"carbon-black",     name:"VMware Carbon Black",         cat:"EDR/XDR",        color:"#007F00", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/carbonblack.com",      description:"Carbon Black Cloud detections, watchlists, device inventory"},
  {id:"symantec",         name:"Symantec Endpoint Security",  cat:"EDR/XDR",        color:"#FFD200", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/broadcom.com",         description:"EP detections, policy compliance, device inventory, DLP"},
  {id:"bitdefender",      name:"Bitdefender GravityZone",     cat:"EDR/XDR",        color:"#ED1C24", ini:"B", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/bitdefender.com",      description:"GravityZone incidents, device inventory, risk assessment"},
  {id:"sophos",           name:"Sophos Intercept X",          cat:"EDR/XDR",        color:"#005CB9", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/sophos.com",           description:"Sophos Central alerts, devices, XDR detections, threat intel"},
  {id:"trendmicro",       name:"Trend Micro Vision One",      cat:"EDR/XDR",        color:"#EE3124", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/trendmicro.com",       description:"Vision One detections, attack surface risk, workbench"},
  {id:"eset-protect",     name:"ESET PROTECT",                cat:"EDR/XDR",        color:"#006DB7", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/eset.com",             description:"ESET PROTECT detections, managed devices, threat reports"},
  {id:"blackberry-cylance",name:"BlackBerry Cylance",         cat:"EDR/XDR",        color:"#000000", ini:"B", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/blackberry.com",       description:"CylancePROTECT, CylanceOPTICS threat detections"},
  {id:"huntress",         name:"Huntress",                    cat:"EDR/XDR",        color:"#FF6633", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/huntress.com",         description:"Managed threat detection, ITDR, persistent foothold reports"},
  {id:"cybereason",       name:"Cybereason",                  cat:"EDR/XDR",        color:"#FF0032", ini:"C", authType:"api-key",      featured:false, logoUrl:"https://logo.clearbit.com/cybereason.com",      description:"MalOps, detections, endpoint and user behaviour analytics"},
  {id:"ms-intune",        name:"Microsoft Intune",            cat:"EDR/XDR",        color:"#0078D4", ini:"I", authType:"oauth2",      featured:false, live:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Device compliance, MDM enrollment, configuration profiles"},
  {id:"cynet",            name:"Cynet 360 AutoXDR",           cat:"EDR/XDR",        color:"#C41230", ini:"C", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/cynet.com",            description:"All-in-one XDR: endpoint, network, user & deception — autonomous breach protection"},
  {id:"trellix-xdr",      name:"Trellix XDR",                 cat:"EDR/XDR",        color:"#C8102E", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/trellix.com",          description:"Trellix XDR detections, Helix SIEM integration, endpoint telemetry"},
  {id:"watchguard-edr",   name:"WatchGuard EPDR",             cat:"EDR/XDR",        color:"#CC0000", ini:"W", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/watchguard.com",       description:"WatchGuard EPDR / ThreatSync: Zero-Trust App Service, device inventory"},
  {id:"deep-instinct",    name:"Deep Instinct",               cat:"EDR/XDR",        color:"#5C2D91", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/deepinstinct.com",     description:"Deep learning pre-execution prevention, D-Brain engine, incident events"},
  {id:"malwarebytes-edr", name:"Malwarebytes EDR",            cat:"EDR/XDR",        color:"#0073E6", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/malwarebytes.com",     description:"Endpoint detections, quarantine, vulnerability assessment, OneView"},

  // ── PAM ────────────────────────────────────────────────────────────────────
  {id:"cyberark",         name:"CyberArk PAM",                cat:"PAM",            color:"#1A3A5C", ini:"C", authType:"certificate", featured:true,  logoUrl:"https://logo.clearbit.com/cyberark.com",         description:"Privileged accounts, session recordings, vault policies, PEDM"},
  {id:"beyondtrust",      name:"BeyondTrust",                 cat:"PAM",            color:"#E5001C", ini:"B", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/beyondtrust.com",      description:"PAM sessions, endpoint privilege management, remote access"},
  {id:"hashicorp-vault",  name:"HashiCorp Vault",             cat:"PAM",            color:"#7B42BC", ini:"V", authType:"certificate", featured:false, logoUrl:"https://logo.clearbit.com/hashicorp.com",        description:"Secrets engine, PKI, dynamic credentials, lease management"},
  {id:"delinea",          name:"Delinea Secret Server",       cat:"PAM",            color:"#0066CC", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/delinea.com",          description:"Secret Server vaults, check-out policies, privileged sessions"},
  {id:"strongdm",         name:"StrongDM",                    cat:"PAM",            color:"#1E3A5F", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/strongdm.com",         description:"Infrastructure access, audit logs, SSH/RDP sessions, queries"},
  {id:"teleport",         name:"Teleport",                    cat:"PAM",            color:"#512FC9", ini:"T", authType:"certificate", featured:false, logoUrl:"https://logo.clearbit.com/goteleport.com",       description:"Zero-trust access, SSH/RDP/Kubernetes, session recording"},
  {id:"manageengine-pam", name:"ManageEngine PAM360",         cat:"PAM",            color:"#E8472A", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/manageengine.com",     description:"PAM360 vault, credential discovery, privileged session audit"},

  // ── ITSM ───────────────────────────────────────────────────────────────────
  {id:"jira",             name:"Jira",                        cat:"ITSM",           color:"#0052CC", ini:"J", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/atlassian.com",        description:"Issues, projects, epics, SLA tracking, security advisories"},
  {id:"servicenow",       name:"ServiceNow",                  cat:"ITSM",           color:"#62D84E", ini:"S", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/servicenow.com",       description:"ITSM: incidents, changes, CMDB, problem records, GRC module"},
  {id:"freshservice",     name:"Freshservice",                cat:"ITSM",           color:"#32A960", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/freshservice.com",     description:"Freshservice tickets, CMDB, change advisory board, SLA"},
  {id:"bmc-remedy",       name:"BMC Helix / Remedy",          cat:"ITSM",           color:"#E30D13", ini:"B", authType:"basic",       featured:false, logoUrl:"https://logo.clearbit.com/bmc.com",              description:"Remedy incidents, change requests, CMDB assets, SLA monitor"},
  {id:"zendesk",          name:"Zendesk",                     cat:"ITSM",           color:"#03363D", ini:"Z", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/zendesk.com",          description:"Zendesk tickets, SLAs, audit log, customer satisfaction"},
  {id:"linear",           name:"Linear",                      cat:"ITSM",           color:"#5E6AD2", ini:"L", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/linear.app",           description:"Linear issues, cycles, projects, security triage workflows"},
  {id:"monday",           name:"Monday.com",                  cat:"ITSM",           color:"#FF3D57", ini:"M", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/monday.com",           description:"Monday boards, items, automations, GRC project tracking"},
  {id:"topdesk",          name:"TOPdesk",                     cat:"ITSM",           color:"#E4002B", ini:"T", authType:"basic",       featured:false, logoUrl:"https://logo.clearbit.com/topdesk.com",          description:"Service requests, change management, CMDB, asset tracking"},
  {id:"ivanti",           name:"Ivanti Service Manager",      cat:"ITSM",           color:"#7B2D8B", ini:"I", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/ivanti.com",           description:"Ivanti ITSM incidents, CMDB, endpoint management, patches"},
  {id:"hubspot-service",  name:"HubSpot Service Hub",         cat:"ITSM",           color:"#FF7A59", ini:"H", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/hubspot.com",          description:"HubSpot support tickets, SLA compliance, customer feedback"},
  {id:"pagerduty",        name:"PagerDuty",                   cat:"ITSM",           color:"#06AC38", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/pagerduty.com",        description:"Incident alerts, on-call schedules, runbooks, postmortems"},
  {id:"opsgenie",         name:"Atlassian Opsgenie",          cat:"ITSM",           color:"#0052CC", ini:"O", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/atlassian.com",        description:"Alert routing, on-call management, incident timelines"},

  // ── DevSecOps ──────────────────────────────────────────────────────────────
  {id:"github",           name:"GitHub",                      cat:"DevSecOps",      color:"#24292F", ini:"⌥", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/github.com",           description:"Code scanning, secret detection, Dependabot, Advanced Security"},
  {id:"gitlab",           name:"GitLab",                      cat:"DevSecOps",      color:"#FC6D26", ini:"G", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/gitlab.com",           description:"GitLab SAST/DAST, container scanning, dependency scanning"},
  {id:"bitbucket",        name:"Bitbucket",                   cat:"DevSecOps",      color:"#0052CC", ini:"B", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/atlassian.com",        description:"Bitbucket pipelines, code insights, audit events, Pipe security"},
  {id:"jenkins",          name:"Jenkins",                     cat:"DevSecOps",      color:"#D33833", ini:"J", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/jenkins.io",           description:"Pipeline runs, build history, plugin security audit, RBAC"},
  {id:"azure-devops",     name:"Azure DevOps",                cat:"DevSecOps",      color:"#0078D4", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"ADO pipelines, work items, SAST scans, artifact security"},
  {id:"sonarqube",        name:"SonarQube",                   cat:"DevSecOps",      color:"#4E9BCD", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/sonarqube.org",        description:"Quality gate, SAST findings, tech debt, security hotspots"},
  {id:"snyk",             name:"Snyk",                        cat:"DevSecOps",      color:"#4C4A73", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/snyk.io",              description:"Open Source, Container, IaC, Code vulnerabilities, license"},
  {id:"checkmarx",        name:"Checkmarx",                   cat:"DevSecOps",      color:"#FF6B35", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/checkmarx.com",        description:"SAST, SCA, API security findings, CxOne results"},
  {id:"veracode",         name:"Veracode",                    cat:"DevSecOps",      color:"#00B4E3", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/veracode.com",         description:"Veracode policy scans, SCA, DAST, sandbox results"},
  {id:"aqua-security",    name:"Aqua Security",               cat:"DevSecOps",      color:"#00ADEF", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/aquasec.com",          description:"Container & Kubernetes security, runtime policies, supply chain"},
  {id:"terraform",        name:"HashiCorp Terraform",         cat:"DevSecOps",      color:"#7B42BC", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/hashicorp.com",        description:"Terraform Cloud runs, IaC drift, workspace state audit"},
  {id:"argocd",           name:"ArgoCD",                      cat:"DevSecOps",      color:"#EF7B4D", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/argoproj.github.io",   description:"Application sync status, drift, deployment audit trail"},
  {id:"ansible",          name:"Ansible / AAP",               cat:"DevSecOps",      color:"#EE0000", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/ansible.com",          description:"Automation jobs, playbook audit, compliance drift detection"},
  {id:"semgrep",          name:"Semgrep",                     cat:"DevSecOps",      color:"#04A07B", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/semgrep.com",          description:"SAST findings, supply chain security, CI scan results"},
  {id:"mend",             name:"Mend.io (WhiteSource)",       cat:"DevSecOps",      color:"#00A3E0", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/mend.io",              description:"Open source vulnerabilities, license compliance, SBOM"},
  {id:"gitguardian",      name:"GitGuardian",                 cat:"DevSecOps",      color:"#FF4A4A", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/gitguardian.com",      description:"Secret detection across Git history, code leaks, NHI"},
  {id:"jfrog",            name:"JFrog Artifactory",           cat:"DevSecOps",      color:"#40BE46", ini:"J", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/jfrog.com",            description:"Artifact security, vulnerability scanning, binary repo"},
  {id:"circleci",         name:"CircleCI",                    cat:"DevSecOps",      color:"#343434", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/circleci.com",         description:"Pipeline history, security scan results, context audit"},
  {id:"sonatype",         name:"Sonatype Nexus",              cat:"DevSecOps",      color:"#1B8452", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/sonatype.com",         description:"Component intelligence, SCA, open source risk, quarantine"},

  // ── SIEM / SOAR ────────────────────────────────────────────────────────────
  {id:"splunk",           name:"Splunk",                      cat:"SIEM/SOAR",      color:"#65A637", ini:"S", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/splunk.com",           description:"Splunk searches, notable events, indexes, alerts, ES correlation"},
  {id:"sentinel",         name:"Microsoft Sentinel",          cat:"SIEM/SOAR",      color:"#0078D4", ini:"⊕", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Sentinel incidents, analytics rules, playbooks, workbooks"},
  {id:"qradar",           name:"IBM QRadar",                  cat:"SIEM/SOAR",      color:"#006699", ini:"Q", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/ibm.com",              description:"QRadar offenses, log sources, custom rules, flows, UBA"},
  {id:"elastic-siem",     name:"Elastic SIEM",                cat:"SIEM/SOAR",      color:"#FEC514", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/elastic.co",           description:"Elastic alerts, cases, fleet enrolled agents, ML anomalies"},
  {id:"sumo-logic",       name:"Sumo Logic",                  cat:"SIEM/SOAR",      color:"#004A76", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/sumologic.com",        description:"Cloud SIEM signals, insights, entities, scheduled searches"},
  {id:"chronicle",        name:"Google Chronicle SIEM",       cat:"SIEM/SOAR",      color:"#4285F4", ini:"C", authType:"oauth2",      featured:false, live:true,  logoUrl:"https://logo.clearbit.com/google.com",           description:"Chronicle UDM events, YARA-L detections, retrohunts, IOCs"},
  {id:"logrhythm",        name:"LogRhythm",                   cat:"SIEM/SOAR",      color:"#B7242A", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/logrhythm.com",        description:"LogRhythm alarms, cases, log source health, UEBA"},
  {id:"exabeam",          name:"Exabeam",                     cat:"SIEM/SOAR",      color:"#2A4DAD", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/exabeam.com",          description:"UEBA risk scores, sessions, notable users, threat intelligence"},
  {id:"cortex-xsoar",     name:"Palo Alto XSOAR",             cat:"SIEM/SOAR",      color:"#FA582D", ini:"X", authType:"api-key",     featured:false, live:true,  logoUrl:"https://logo.clearbit.com/paloaltonetworks.com", description:"XSOAR incidents, playbook runs, indicator ingestion, SOAR"},
  {id:"datadog",          name:"Datadog",                     cat:"SIEM/SOAR",      color:"#632CA6", ini:"D", authType:"api-key",     featured:false, live:true,  logoUrl:"https://logo.clearbit.com/datadog.com",           description:"Monitors, security signals, APM traces, logs, CSPM findings"},
  {id:"securonix",        name:"Securonix SIEM",              cat:"SIEM/SOAR",      color:"#003865", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/securonix.com",        description:"UEBA incidents, threat chains, policy violations, enrichment"},
  {id:"graylog",          name:"Graylog",                     cat:"SIEM/SOAR",      color:"#FF3633", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/graylog.org",          description:"Log management, security events, streams, alerts, dashboards"},
  {id:"wazuh",            name:"Wazuh",                       cat:"SIEM/SOAR",      color:"#009BDE", ini:"W", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/wazuh.com",            description:"Open-source SIEM/XDR, FIM, compliance checks, vulnerability"},
  {id:"tines",            name:"Tines",                       cat:"SIEM/SOAR",      color:"#FF5533", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/tines.com",            description:"No-code security automation, story audit, action logs"},
  {id:"stellar-cyber",    name:"Stellar Cyber Open XDR",      cat:"SIEM/SOAR",      color:"#0057FF", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/stellarcyber.ai",      description:"Open XDR SIEM/SOAR: AI-driven detections, NDR, UEBA, correlation"},
  {id:"swimlane",         name:"Swimlane SOAR",               cat:"SIEM/SOAR",      color:"#00A3E0", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/swimlane.com",         description:"Low-code SOAR: case management, playbooks, automation metrics"},
  {id:"devo",             name:"Devo Technology",             cat:"SIEM/SOAR",      color:"#00B2A9", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/devo.com",             description:"Cloud-native SIEM: real-time search, ML detections, streaming pipeline"},
  {id:"rapid7-idr",       name:"Rapid7 InsightIDR",           cat:"SIEM/SOAR",      color:"#E2231A", ini:"R", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/rapid7.com",           description:"Cloud SIEM/SOAR, UEBA, attacker behaviour analytics, MDR integration"},
  {id:"alienvault-usm",   name:"AT&T USM Anywhere",           cat:"SIEM/SOAR",      color:"#009FDB", ini:"U", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/alienvault.com",       description:"Unified security management, OTX threat intel, SIEM alarms, NIDS"},
  {id:"logscale",         name:"CrowdStrike LogScale",        cat:"SIEM/SOAR",      color:"#E01B22", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/crowdstrike.com",      description:"Petabyte-scale log management, real-time streaming queries, Falcon Fusion"},

  // ── Network ────────────────────────────────────────────────────────────────
  {id:"paloalto",         name:"Palo Alto Networks",          cat:"Network",        color:"#FA582D", ini:"P", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/paloaltonetworks.com", description:"NGFW rules, threat logs, URL filtering, WildFire submissions"},
  {id:"cisco-secure",     name:"Cisco Secure Analytics",      cat:"Network",        color:"#00BCEB", ini:"C", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/cisco.com",            description:"NetFlow/IPFIX analysis, security events, encrypted traffic"},
  {id:"zscaler",          name:"Zscaler",                     cat:"Network",        color:"#005DAA", ini:"Z", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/zscaler.com",          description:"ZIA/ZPA events, DLP incidents, user activity, tunnel logs"},
  {id:"fortinet",         name:"Fortinet FortiGate",          cat:"Network",        color:"#EE3124", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/fortinet.com",         description:"FortiGate traffic logs, IPS events, VPN sessions, botnet"},
  {id:"checkpoint",       name:"Check Point",                 cat:"Network",        color:"#CC0000", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/checkpoint.com",       description:"Check Point SmartConsole logs, threat prevention, HTTPS inspection"},
  {id:"cisco-umbrella",   name:"Cisco Umbrella",              cat:"Network",        color:"#00BCEB", ini:"U", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cisco.com",            description:"Umbrella DNS security events, proxy logs, identity mapping"},
  {id:"cisco-meraki",     name:"Cisco Meraki",                cat:"Network",        color:"#00BCEB", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/meraki.com",           description:"Meraki network events, client devices, MX security appliance"},
  {id:"f5-bigip",         name:"F5 BIG-IP",                   cat:"Network",        color:"#E4003A", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/f5.com",               description:"BIG-IP WAF events, AFM policies, ASM blocking logs, iRules"},
  {id:"juniper",          name:"Juniper Networks",            cat:"Network",        color:"#84BD00", ini:"J", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/juniper.net",          description:"Juniper SRX security events, routing policy, MPLS logs"},
  {id:"darktrace",        name:"Darktrace",                   cat:"Network",        color:"#003B5C", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/darktrace.com",        description:"AI-driven anomaly detection, model breaches, device risk"},
  {id:"vectra",           name:"Vectra AI",                   cat:"Network",        color:"#7B2FBE", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/vectra.ai",            description:"NDR detections, account takeover, lateral movement, C2"},
  {id:"extrahop",         name:"ExtraHop Reveal(x)",          cat:"Network",        color:"#00A9FF", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/extrahop.com",         description:"Network detection, encrypted traffic analysis, east-west"},
  {id:"nozomi",           name:"Nozomi Networks",             cat:"Network",        color:"#1A6FBA", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/nozomi.com",           description:"OT/ICS asset visibility, alerts, vulnerability assessment"},
  {id:"corelight",        name:"Corelight",                   cat:"Network",        color:"#003865", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/corelight.com",        description:"Open NDR: Zeek-based network visibility, encrypted traffic analysis"},
  {id:"illumio",          name:"Illumio Zero Trust",          cat:"Network",        color:"#FF5500", ini:"I", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/illumio.com",          description:"Micro-segmentation, workload visibility, policy simulation, breach containment"},
  {id:"guardicore",       name:"Akamai Guardicore",           cat:"Network",        color:"#009BDE", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/akamai.com",           description:"Micro-segmentation, ransomware containment, network flow visibility"},
  {id:"netwitness",       name:"NetWitness Platform",         cat:"Network",        color:"#0066CC", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/netwitness.com",       description:"Full packet capture, SIEM/NDR, threat detection, behavioral analytics"},

  // ── Vuln Mgmt ──────────────────────────────────────────────────────────────
  {id:"tenable",          name:"Tenable.io",                  cat:"Vuln Mgmt",      color:"#00B4E3", ini:"T", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/tenable.com",          description:"Vulnerability scans, asset tracking, web app scanning, EPSS"},
  {id:"qualys",           name:"Qualys VMDR",                 cat:"Vuln Mgmt",      color:"#ED1C24", ini:"Q", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/qualys.com",           description:"VMDR detections, asset inventory, patch priority, CSAM"},
  {id:"rapid7",           name:"Rapid7 InsightVM",            cat:"Vuln Mgmt",      color:"#E2231A", ini:"R", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/rapid7.com",           description:"InsightVM vulnerabilities, remediation projects, SOAR actions"},
  {id:"wiz",              name:"Wiz CNAPP",                   cat:"Vuln Mgmt",      color:"#00B4E0", ini:"W", authType:"oauth2",      featured:false, live:true,  logoUrl:"https://logo.clearbit.com/wiz.io",               description:"Wiz issues, cloud attack paths, CIEM, IaC security, agentless"},
  {id:"lacework",         name:"Lacework",                    cat:"Vuln Mgmt",      color:"#3B1D8E", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/lacework.com",         description:"Cloud security, runtime anomalies, container vuln scanning"},
  {id:"orca-security",    name:"Orca Security",               cat:"Vuln Mgmt",      color:"#FF5A00", ini:"O", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/orca.security",        description:"Agentless cloud scanning, risk priorities, attack paths, SBOM"},
  {id:"nessus",           name:"Nessus Professional",         cat:"Vuln Mgmt",      color:"#00B4E3", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/tenable.com",          description:"Nessus vulnerability detections, compliance checks, plugins"},
  {id:"openvas",          name:"Greenbone / OpenVAS",         cat:"Vuln Mgmt",      color:"#4CAF50", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/greenbone.net",        description:"Open-source vulnerability scanning, NVT feed, reports"},
  {id:"kenna",            name:"Cisco Vulnerability Mgmt",    cat:"Vuln Mgmt",      color:"#00BCEB", ini:"K", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cisco.com",            description:"Risk-based vulnerability management, asset risk scoring"},
  {id:"hackerone",        name:"HackerOne",                   cat:"Vuln Mgmt",      color:"#494A4D", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/hackerone.com",        description:"Bug bounty reports, triage, CVE coordination, pentest results"},
  {id:"bugcrowd",         name:"Bugcrowd",                    cat:"Vuln Mgmt",      color:"#F26522", ini:"B", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/bugcrowd.com",         description:"Vulnerability submissions, crowdsourced security, VDP"},
  {id:"invicti",          name:"Invicti (Netsparker)",        cat:"Vuln Mgmt",      color:"#E83E8C", ini:"I", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/invicti.com",          description:"DAST web application scanning, API security, proof-based"},

  // ── SaaS ───────────────────────────────────────────────────────────────────
  {id:"slack",            name:"Slack",                       cat:"SaaS",           color:"#4A154B", ini:"S", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/slack.com",            description:"Audit logs, DLP events, app access, workspace security"},
  {id:"m365",             name:"Microsoft 365",               cat:"SaaS",           color:"#0078D4", ini:"M", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Security score, DLP, Exchange ATP, Teams activity, Purview"},
  {id:"ms-teams",         name:"Microsoft Teams",             cat:"SaaS",           color:"#464EB8", ini:"T", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Teams audit log, meeting recordings, channel governance"},
  {id:"zoom",             name:"Zoom",                        cat:"SaaS",           color:"#2D8CFF", ini:"Z", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/zoom.us",              description:"Operations log, recording access, security settings, users"},
  {id:"salesforce",       name:"Salesforce",                  cat:"SaaS",           color:"#00A1E0", ini:"S", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/salesforce.com",       description:"Event Monitoring, field audit trail, setup audit, Shield"},
  {id:"hubspot",          name:"HubSpot",                     cat:"SaaS",           color:"#FF7A59", ini:"H", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/hubspot.com",          description:"Activity log, data exports, user permissions, data privacy"},
  {id:"box",              name:"Box",                         cat:"SaaS",           color:"#0061D5", ini:"B", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/box.com",              description:"Events, external sharing, DLP policies, Shield anomalies"},
  {id:"dropbox",          name:"Dropbox Business",            cat:"SaaS",           color:"#0061FE", ini:"D", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/dropbox.com",          description:"Team activity, sharing links, external user access, devices"},
  {id:"confluence",       name:"Atlassian Confluence",        cat:"SaaS",           color:"#0052CC", ini:"C", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/atlassian.com",        description:"Spaces, page access, audit log, data residency settings"},
  {id:"notion",           name:"Notion",                      cat:"SaaS",           color:"#494949", ini:"N", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/notion.so",            description:"Audit log, page access, member permissions, integrations"},
  {id:"docusign",         name:"DocuSign",                    cat:"SaaS",           color:"#FFB400", ini:"D", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/docusign.com",         description:"Envelope audit, user activity, credential usage, eSign events"},
  {id:"figma",            name:"Figma",                       cat:"SaaS",           color:"#F24E1E", ini:"F", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/figma.com",            description:"File access audit, sharing settings, plugin permissions"},
  {id:"asana",            name:"Asana",                       cat:"SaaS",           color:"#F06A6A", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/asana.com",            description:"Project audit log, user access, data export events"},
  {id:"webex",            name:"Cisco Webex",                 cat:"SaaS",           color:"#00BCEB", ini:"W", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/webex.com",            description:"Meeting recordings, messaging audit, security events, compliance"},

  // ── Data ───────────────────────────────────────────────────────────────────
  {id:"snowflake",        name:"Snowflake",                   cat:"Data",           color:"#29B5E8", ini:"❄", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/snowflake.com",        description:"Access history, GRANT audit, object tagging, data sharing"},
  {id:"databricks",       name:"Databricks",                  cat:"Data",           color:"#FF3621", ini:"◆", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/databricks.com",       description:"Audit log, cluster activity, data lineage, workspace permissions"},
  {id:"tableau",          name:"Tableau",                     cat:"Data",           color:"#E8762D", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/tableau.com",          description:"Content access, user activity, permissions audit, data sources"},
  {id:"powerbi",          name:"Microsoft Power BI",          cat:"Data",           color:"#F2C80F", ini:"P", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Activity log, workspace access, dataset lineage, export audit"},
  {id:"dbt-cloud",        name:"dbt Cloud",                   cat:"Data",           color:"#FF694A", ini:"d", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/getdbt.com",           description:"Run history, exposure audit, data lineage metadata"},
  {id:"mongodb-atlas",    name:"MongoDB Atlas",               cat:"Data",           color:"#47A248", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/mongodb.com",          description:"Audit events, database access, network logs, compliance"},
  {id:"bigquery",         name:"Google BigQuery",             cat:"Data",           color:"#4285F4", ini:"B", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/google.com",           description:"Data access audit, job history, IAM policy changes, DLP scan"},
  {id:"redshift",         name:"Amazon Redshift",             cat:"Data",           color:"#FF9900", ini:"R", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/aws.amazon.com",       description:"Connection log, query audit, privilege grants, STL tables"},
  {id:"elastic",          name:"Elasticsearch",               cat:"Data",           color:"#FEC514", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/elastic.co",           description:"Index audit, document access, snapshot policies, ILM"},
  {id:"fivetran",         name:"Fivetran",                    cat:"Data",           color:"#0073E6", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/fivetran.com",         description:"Connector sync logs, audit events, destination access"},

  // ── HR & People ────────────────────────────────────────────────────────────
  {id:"workday",          name:"Workday",                     cat:"HR & People",    color:"#F5821F", ini:"W", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/workday.com",          description:"Workers, joiner/mover/leaver triggers, org structure"},
  {id:"bamboohr",         name:"BambooHR",                    cat:"HR & People",    color:"#73C41D", ini:"B", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/bamboohr.com",         description:"Employee directory, offboarding triggers, org data, time-off"},
  {id:"adp",              name:"ADP Workforce Now",           cat:"HR & People",    color:"#CC0000", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/adp.com",              description:"Worker data, employment status, payroll period audit"},
  {id:"sap-sf",           name:"SAP SuccessFactors",          cat:"HR & People",    color:"#0070C0", ini:"S", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/sap.com",              description:"Employees, learning completions, org hierarchy, JML events"},
  {id:"rippling",         name:"Rippling",                    cat:"HR & People",    color:"#F7C844", ini:"R", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/rippling.com",         description:"Employees, app provisioning, device management, payroll"},
  {id:"greenhouse",       name:"Greenhouse",                  cat:"HR & People",    color:"#24A47F", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/greenhouse.io",        description:"Hiring pipeline, offer events, employee start dates, GDPR"},
  {id:"hibob",            name:"HiBob HRIS",                  cat:"HR & People",    color:"#FF5C35", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/hibob.com",            description:"Employee lifecycle, org chart, time-off, performance data"},
  {id:"personio",         name:"Personio",                    cat:"HR & People",    color:"#0078D4", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/personio.com",         description:"HR records, recruiting, onboarding, payroll, absence tracking"},
  {id:"ukg",              name:"UKG Pro",                     cat:"HR & People",    color:"#00A3A1", ini:"U", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/ukg.com",              description:"Workforce management, scheduling, absence, labour analytics"},
  {id:"lattice",          name:"Lattice",                     cat:"HR & People",    color:"#4B3BD5", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/lattice.com",          description:"Performance reviews, engagement, goals, HRIS integration"},

  // ── Email Security ─────────────────────────────────────────────────────────
  {id:"proofpoint",       name:"Proofpoint Email Security",   cat:"Email Security", color:"#D71920", ini:"P", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/proofpoint.com",       description:"Email threat log, TAP alerts, DLP incidents, TRAP remediation"},
  {id:"mimecast",         name:"Mimecast",                    cat:"Email Security", color:"#F7941D", ini:"M", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/mimecast.com",         description:"Email threat events, held messages, URL protection, audit log"},
  {id:"barracuda-email",  name:"Barracuda Email Security",    cat:"Email Security", color:"#D5390D", ini:"B", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/barracuda.com",        description:"Inbound/outbound threat log, quarantine, phishing reports"},
  {id:"abnormal-security",name:"Abnormal Security",           cat:"Email Security", color:"#2B4EFF", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/abnormalsecurity.com", description:"BEC, phishing, account takeover, threat campaign detection"},
  {id:"ironscales",       name:"IRONSCALES",                  cat:"Email Security", color:"#FF3C00", ini:"I", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/ironscales.com",       description:"Phishing simulations, incident response, email threat intel"},
  {id:"cofense",          name:"Cofense PhishMe",             cat:"Email Security", color:"#0066CC", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cofense.com",          description:"Phishing simulation results, reporter events, threat intel"},
  {id:"tessian",          name:"Tessian",                     cat:"Email Security", color:"#4200FF", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/tessian.com",          description:"Human Layer Security: misdirected email, data exfil, account takeover"},
  {id:"avanan",           name:"Avanan (Check Point)",        cat:"Email Security", color:"#CC0000", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/checkpoint.com",       description:"Cloud email security, attachment sandboxing, account protection"},
  {id:"agari",            name:"Agari Brand Protection",      cat:"Email Security", color:"#0E3D7B", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/agari.com",            description:"DMARC enforcement, brand spoofing, BEC protection, threat log"},
  {id:"defender-o365",    name:"Microsoft Defender for M365", cat:"Email Security", color:"#0078D4", ini:"D", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Safe Links, Safe Attachments, anti-phishing, threat explorer"},
  {id:"vade",             name:"Vade Email Security",         cat:"Email Security", color:"#0099CC", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/vadesecure.com",       description:"AI-powered email security: phishing, spear-phishing, malware, BEC"},
  {id:"slashnext",        name:"SlashNext Email+",            cat:"Email Security", color:"#FF4D00", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/slashnext.com",        description:"Gen-AI phishing defence: URL/attachment analysis, business email threats"},
  {id:"perception-point", name:"Perception Point",           cat:"Email Security", color:"#4B3FD1", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/perception-point.io",  description:"Advanced email & collaboration security, malware sandbox, IR team"},
  {id:"area1",            name:"Cloudflare Area 1",           cat:"Email Security", color:"#F48120", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cloudflare.com",       description:"Preemptive email security, phishing risk score, cloud-based sandboxing"},
  {id:"egress",           name:"Egress Email Security",       cat:"Email Security", color:"#0057B8", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/egress.com",           description:"Intelligent email DLP, misdirected email prevention, account takeover"},

  // ── DLP / CASB ─────────────────────────────────────────────────────────────
  {id:"purview-dlp",      name:"Microsoft Purview DLP",       cat:"DLP/CASB",       color:"#0078D4", ini:"P", authType:"oauth2",      featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/microsoft.com",        description:"Policy matches, sensitive info types, endpoint & cloud DLP"},
  {id:"netskope",         name:"Netskope",                    cat:"DLP/CASB",       color:"#003087", ini:"N", authType:"api-key",     featured:true,  live:true,  logoUrl:"https://logo.clearbit.com/netskope.com",         description:"CASB, SWG, DLP incidents, shadow IT, ZTNA access events"},
  {id:"forcepoint-dlp",   name:"Forcepoint DLP",              cat:"DLP/CASB",       color:"#E8392F", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/forcepoint.com",       description:"Policy violations, endpoint DLP, email & web channel events"},
  {id:"digital-guardian", name:"Digital Guardian",            cat:"DLP/CASB",       color:"#00529C", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/digitalguardian.com",  description:"Data-aware protection, insider threat events, USB DLP"},
  {id:"symantec-dlp",     name:"Symantec DLP",                cat:"DLP/CASB",       color:"#FFD200", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/broadcom.com",         description:"Discover, monitor, protect: endpoint, network, storage DLP"},
  {id:"varonis",          name:"Varonis Data Security",       cat:"DLP/CASB",       color:"#E94E1B", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/varonis.com",          description:"File access auditing, data classification, UEBA, ransomware"},
  {id:"code42",           name:"Code42 Insider Risk",         cat:"DLP/CASB",       color:"#003087", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/code42.com",           description:"File exfiltration, departing employee alerts, cloud sync DLP"},
  {id:"mcafee-dlp",       name:"Trellix (McAfee) DLP",        cat:"DLP/CASB",       color:"#C8102E", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/trellix.com",          description:"Trellix DLP policy violations, incident management, discovery"},
  {id:"lookout",          name:"Lookout Mobile Security",     cat:"DLP/CASB",       color:"#007DC1", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/lookout.com",          description:"Mobile threat defense, phishing, network attacks, CASB"},

  // ── GRC / Compliance ───────────────────────────────────────────────────────
  {id:"vanta",            name:"Vanta",                       cat:"GRC/Compliance", color:"#6B3BE2", ini:"V", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/vanta.com",            description:"SOC 2, ISO 27001, HIPAA automation, evidence collection"},
  {id:"drata",            name:"Drata",                       cat:"GRC/Compliance", color:"#6C47FF", ini:"D", authType:"oauth2",      featured:true,  logoUrl:"https://logo.clearbit.com/drata.com",            description:"Continuous compliance monitoring, control evidence, risk"},
  {id:"secureframe",      name:"Secureframe",                 cat:"GRC/Compliance", color:"#0068FF", ini:"S", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/secureframe.com",      description:"Compliance automation, vendor questionnaires, audit readiness"},
  {id:"auditboard",       name:"AuditBoard",                  cat:"GRC/Compliance", color:"#FF6B00", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/auditboard.com",       description:"Audit management, SOX, risk register, issue tracking"},
  {id:"workiva",          name:"Workiva",                     cat:"GRC/Compliance", color:"#007DC1", ini:"W", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/workiva.com",          description:"SOX, ESG reporting, financial controls, audit workflow"},
  {id:"logicgate",        name:"LogicGate Risk Cloud",        cat:"GRC/Compliance", color:"#00A0DF", ini:"L", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/logicgate.com",        description:"Risk management, compliance programs, control testing"},
  {id:"hyperproof",       name:"Hyperproof",                  cat:"GRC/Compliance", color:"#5C2D91", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/hyperproof.io",        description:"Compliance operations, evidence management, GRC workflows"},
  {id:"rsa-archer",       name:"RSA Archer GRC",              cat:"GRC/Compliance", color:"#003087", ini:"R", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/rsa.com",              description:"Enterprise risk management, compliance, audit, issues"},
  {id:"servicenow-grc",   name:"ServiceNow GRC",              cat:"GRC/Compliance", color:"#62D84E", ini:"S", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/servicenow.com",       description:"Integrated risk management, policy management, audit workflow"},
  {id:"sprinto",          name:"Sprinto",                     cat:"GRC/Compliance", color:"#5B4FE9", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/sprinto.com",          description:"Compliance automation, control monitoring, evidence vault"},
  {id:"scrut",            name:"Scrut Automation",            cat:"GRC/Compliance", color:"#0066CC", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/scrut.io",             description:"Security program management, compliance, vendor risk"},
  {id:"tugboat",          name:"Tugboat Logic",               cat:"GRC/Compliance", color:"#0E76A8", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/tugboatlogic.com",     description:"Policy management, evidence collection, audit readiness"},

  // ── Observability ──────────────────────────────────────────────────────────
  {id:"new-relic",        name:"New Relic",                   cat:"Observability",  color:"#00AC69", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/newrelic.com",         description:"Alerts, violations, APM transactions, security events"},
  {id:"dynatrace",        name:"Dynatrace",                   cat:"Observability",  color:"#1496FF", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/dynatrace.com",        description:"Davis AI detections, log management, security findings"},
  {id:"grafana-cloud",    name:"Grafana Cloud",               cat:"Observability",  color:"#FF6600", ini:"G", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/grafana.com",          description:"Dashboards, alerting, Loki logs, Mimir metrics, on-call"},
  {id:"appdynamics",      name:"AppDynamics",                 cat:"Observability",  color:"#00BCEB", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/appdynamics.com",      description:"APM, business transactions, anomaly detection, security"},
  {id:"solarwinds",       name:"SolarWinds",                  cat:"Observability",  color:"#F89820", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/solarwinds.com",       description:"Network performance, alerts, configuration compliance, log"},
  {id:"zabbix",           name:"Zabbix",                      cat:"Observability",  color:"#CC0000", ini:"Z", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/zabbix.com",           description:"Monitoring alerts, availability, performance trends, audit"},
  {id:"prtg",             name:"PRTG Network Monitor",        cat:"Observability",  color:"#FF6600", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/paessler.com",         description:"Network monitoring, bandwidth, uptime alerts, device health"},
  {id:"nagios",           name:"Nagios XI",                   cat:"Observability",  color:"#005B94", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/nagios.com",           description:"Host/service monitoring, alerts, availability reports"},
  {id:"elastic-apm",      name:"Elastic APM",                 cat:"Observability",  color:"#FEC514", ini:"E", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/elastic.co",           description:"Application performance, error tracking, service map, tracing"},
  {id:"honeycomb",        name:"Honeycomb.io",                cat:"Observability",  color:"#F5A623", ini:"H", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/honeycomb.io",         description:"Distributed tracing, high-cardinality event analysis, SLOs"},
  {id:"victorops",        name:"Splunk On-Call",              cat:"Observability",  color:"#65A637", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/splunk.com",           description:"On-call schedules, incident timeline, postmortem tracking"},

  // ── Backup / DR ────────────────────────────────────────────────────────────
  {id:"veeam",            name:"Veeam Backup",                cat:"Backup/DR",      color:"#00B336", ini:"V", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/veeam.com",            description:"Backup jobs, restore points, replication, compliance reporting"},
  {id:"commvault",        name:"Commvault",                   cat:"Backup/DR",      color:"#0066CC", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/commvault.com",        description:"Data protection jobs, audit log, ransomware detection, SLA"},
  {id:"rubrik",           name:"Rubrik",                      cat:"Backup/DR",      color:"#003366", ini:"R", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/rubrik.com",           description:"Cloud data management, policy compliance, anomaly detection"},
  {id:"cohesity",         name:"Cohesity",                    cat:"Backup/DR",      color:"#0078D4", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cohesity.com",         description:"DataProtect, data governance, AI-driven anomaly detection"},
  {id:"veritas",          name:"Veritas NetBackup",           cat:"Backup/DR",      color:"#CC0000", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/veritas.com",          description:"NetBackup jobs, catalog, anomaly alerts, cloud DR"},
  {id:"zerto",            name:"Zerto",                       cat:"Backup/DR",      color:"#0D6EFD", ini:"Z", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/zerto.com",            description:"Continuous replication, RTO/RPO metrics, DR test automation"},
  {id:"druva",            name:"Druva",                       cat:"Backup/DR",      color:"#4CB050", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/druva.com",            description:"Cloud backup, data resiliency, ransomware recovery, eDiscovery"},
  {id:"acronis",          name:"Acronis Cyber Protect",       cat:"Backup/DR",      color:"#DC143C", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/acronis.com",          description:"Backup + security, malware protection, patch management"},
  {id:"aws-backup",       name:"AWS Backup",                  cat:"Backup/DR",      color:"#FF9900", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/aws.amazon.com",       description:"AWS cross-service backup, recovery points, compliance reports"},

  // ── Collaboration ──────────────────────────────────────────────────────────
  {id:"ringcentral",      name:"RingCentral",                 cat:"Collaboration",  color:"#FF8200", ini:"R", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/ringcentral.com",      description:"Call records, message audit, compliance recording, analytics"},
  {id:"mattermost",       name:"Mattermost",                  cat:"Collaboration",  color:"#0058CC", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/mattermost.com",       description:"Self-hosted messaging audit, compliance export, user events"},
  {id:"trello",           name:"Trello",                      cat:"Collaboration",  color:"#0052CC", ini:"T", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/trello.com",           description:"Board activity, member access, power-up audit, card history"},
  {id:"clickup",          name:"ClickUp",                     cat:"Collaboration",  color:"#7B68EE", ini:"C", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/clickup.com",          description:"Task activity, workspace audit, guest access, time tracking"},
  {id:"miro",             name:"Miro",                        cat:"Collaboration",  color:"#FFD02F", ini:"M", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/miro.com",             description:"Board access, sharing settings, export events, team audit"},
  {id:"airtable",         name:"Airtable",                    cat:"Collaboration",  color:"#18BFFF", ini:"A", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/airtable.com",         description:"Record changes, workspace sharing, automation audit log"},
  {id:"loom",             name:"Loom",                        cat:"Collaboration",  color:"#625DF5", ini:"L", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/loom.com",             description:"Video recording access, workspace members, sharing controls"},
  {id:"google-meet",      name:"Google Meet",                 cat:"Collaboration",  color:"#00897B", ini:"G", authType:"oauth2",      featured:false, logoUrl:"https://logo.clearbit.com/google.com",           description:"Meeting audit, recording access, Meet Admin report, attendance"},
  {id:"discord-biz",      name:"Discord for Business",        cat:"Collaboration",  color:"#5865F2", ini:"D", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/discord.com",          description:"Server audit log, role assignments, channel access, bans"},
  {id:"twist",            name:"Twist by Doist",              cat:"Collaboration",  color:"#CF4647", ini:"T", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/twist.com",            description:"Async team communication, workspace audit, data export"},

  // ── SSE (Security Service Edge) ────────────────────────────────────────────
  {id:"cato-networks",    name:"Cato Networks SASE",          cat:"SSE",            color:"#0072BC", ini:"C", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/catonetworks.com",     description:"SASE cloud: SWG, CASB, FWaaS, ZTNA, SD-WAN — single-pass inspection"},
  {id:"iboss",            name:"iboss Zero Trust",            cat:"SSE",            color:"#003087", ini:"i", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/iboss.com",            description:"Zero Trust cloud security: SWG, CASB, ZTNA, DLP, browser isolation"},
  {id:"prisma-access",    name:"Palo Alto Prisma Access",     cat:"SSE",            color:"#FA582D", ini:"P", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/paloaltonetworks.com", description:"SASE/SSE: GlobalProtect, SWG, CASB, FWaaS, cloud-delivered NGFW"},
  {id:"skyhigh-security", name:"Skyhigh Security",            cat:"SSE",            color:"#E8392F", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/skyhighsecurity.com",  description:"SSE platform: SWG, CASB, ZTNA, DLP, shadow IT, remote browser isolation"},
  {id:"menlo-security",   name:"Menlo Security",              cat:"SSE",            color:"#00B2FF", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/menlosecurity.com",    description:"Secure cloud browser: isolation-based SWG, phishing prevention, CASB"},
  {id:"versa-networks",   name:"Versa Networks",              cat:"SSE",            color:"#4B2D8F", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/versa-networks.com",   description:"SASE: SD-WAN, SWG, CASB, NGFW, ZTNA, AI/ML-driven threat analytics"},
  {id:"aryaka",           name:"Aryaka",                      cat:"SSE",            color:"#0066CC", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/aryaka.com",           description:"Unified SASE: SD-WAN, SWG, CASB, WAN optimisation, cloud access"},
  {id:"forcepoint-one",   name:"Forcepoint ONE SSE",          cat:"SSE",            color:"#E8392F", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/forcepoint.com",       description:"Cloud-native SSE: SWG, CASB, ZTNA, data-first security, DLP"},
  {id:"cloudflare-zt",    name:"Cloudflare Zero Trust",       cat:"SSE",            color:"#F48120", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cloudflare.com",       description:"ZTNA, SWG, CASB, Email security, DLP, Magic WAN, Gateway access logs"},
  {id:"netskope-sse",     name:"Netskope Intelligent SSE",    cat:"SSE",            color:"#003087", ini:"N", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/netskope.com",         description:"Intelligent SSE: CASB, SWG, ZTNA, inline DLP, real-time threat protection"},

  // ── Threat Intelligence ────────────────────────────────────────────────────
  {id:"recorded-future",  name:"Recorded Future",             cat:"Threat Intel",   color:"#CC0000", ini:"R", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/recordedfuture.com",   description:"Threat intel: malware, C2, CVE, dark web — AI-powered risk scoring"},
  {id:"threatconnect",    name:"ThreatConnect",               cat:"Threat Intel",   color:"#0066FF", ini:"T", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/threatconnect.com",    description:"Threat intel platform: IOC management, TQL queries, SOAR playbooks"},
  {id:"anomali",          name:"Anomali ThreatStream",        cat:"Threat Intel",   color:"#FF6B00", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/anomali.com",          description:"Threat intel aggregation, IOC matching, SIEM enrichment, STIX/TAXII"},
  {id:"misp",             name:"MISP",                        cat:"Threat Intel",   color:"#1A6FBA", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/misp-project.org",     description:"Open-source threat sharing: events, attributes, galaxies, STIX2"},
  {id:"mandiant-intel",   name:"Mandiant Threat Intelligence",cat:"Threat Intel",   color:"#C8102E", ini:"M", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/mandiant.com",         description:"Actor profiles, breach analytics, frontline intel, campaign tracking"},
  {id:"pre-security",     name:"PRE Security",                cat:"Threat Intel",   color:"#7C3AED", ini:"P", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/presecurity.ai",       description:"Predictive behavioral attack intelligence, pre-attack signal analysis"},
  {id:"virustotal",       name:"VirusTotal Enterprise",       cat:"Threat Intel",   color:"#3366CC", ini:"V", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/virustotal.com",       description:"File/URL/domain malware analysis, IoC lookup, hunting queries"},
  {id:"flashpoint",       name:"Flashpoint Intelligence",     cat:"Threat Intel",   color:"#1A1A2E", ini:"F", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/flashpoint-intel.com", description:"Deep/dark web monitoring, ransomware tracking, vulnerability intel"},
  {id:"crowdstrike-intel",name:"CrowdStrike Falcon Intel",    cat:"Threat Intel",   color:"#E01B22", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/crowdstrike.com",      description:"Adversary profiles, malware intel, indicator graph, sandbox reports"},
  {id:"picus-security",   name:"Picus Security",              cat:"Threat Intel",   color:"#FF5500", ini:"P", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/picussecurity.com",    description:"Breach & Attack Simulation, MITRE ATT&CK coverage scoring, TI validation"},
  {id:"mitre-attack",     name:"MITRE ATT&CK (TAXII)",        cat:"Threat Intel",   color:"#003865", ini:"⊡", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/mitre.org",            description:"ATT&CK TAXII feed: techniques, mitigations, group/software mapping"},

  // ── Deception Technology ───────────────────────────────────────────────────
  {id:"deceptivebytes",   name:"DeceptiveBytes",              cat:"Deception",      color:"#1A1A2E", ini:"D", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/deceptivebytes.com",   description:"Active endpoint deception: Moving Target Defense, pre-execution traps"},
  {id:"attivo-networks",  name:"Attivo Networks (SentinelOne)",cat:"Deception",     color:"#6C3EC5", ini:"A", authType:"api-key",     featured:true,  logoUrl:"https://logo.clearbit.com/sentinelone.com",      description:"Identity deception, AD protection, lateral movement bait & detection"},
  {id:"illusive-networks",name:"Illusive Networks",           cat:"Deception",      color:"#003087", ini:"I", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/illusive.com",         description:"Agentless deception fabric, AD attack paths, lateral movement baiting"},
  {id:"specter",          name:"Specter",                     cat:"Deception",      color:"#1E3A5F", ini:"S", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/specter.ai",           description:"Deception honeypots, attacker profiling, TTPs, smart lures"},
  {id:"acalvio",          name:"Acalvio ShadowPlex",          cat:"Deception",      color:"#0057B8", ini:"A", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/acalvio.com",          description:"Distributed deception, autonomous lures, breadcrumbs, threat intel"},
  {id:"traps-cymmetria",  name:"Cymmetria MazeRunner",        cat:"Deception",      color:"#FF6B00", ini:"C", authType:"api-key",     featured:false, logoUrl:"https://logo.clearbit.com/cymmetria.com",        description:"Deception campaigns, attacker path mapping, threat actor analysis"},
];

// ── Categories (All + 21 domain groups) ──────────────────────────────────────
export const CATEGORIES = [
  "All","Cloud","Identity","EDR/XDR","PAM","ITSM","DevSecOps",
  "SIEM/SOAR","Network","Vuln Mgmt","SaaS","Data","HR & People",
  "Email Security","DLP/CASB","SSE","Threat Intel","Deception",
  "GRC/Compliance","Observability","Backup/DR","Collaboration"
];

export const OS_CAPABILITIES: Record<string, { os: AgentOS; icon: string; color: string; capabilities: Array<{ name: string; description: string; supported: boolean }> }> = {
  Windows: {
    os: "windows", icon: "⊞", color: "#0078D4",
    capabilities: [
      { name: "Registry Auditing",       description: "Monitor registry key changes, run-key persistence, COM hijacking",       supported: true },
      { name: "AD / WMI Queries",         description: "Query Active Directory, WMI classes, domain membership",                 supported: true },
      { name: "Software Inventory",       description: "Enumerate installed applications, versions, publisher, path",             supported: true },
      { name: "GPO Compliance",           description: "Audit Group Policy Objects against CIS/STIG benchmarks",                 supported: true },
      { name: "Event Log Forwarding",     description: "Forward Security, System, Application event logs via ETW",               supported: true },
      { name: "File Integrity Monitoring",description: "SHA-256 hash monitoring on configurable directory trees",                 supported: true },
      { name: "Scheduled Task Audit",     description: "Enumerate all scheduled tasks, detect persistence mechanisms",           supported: true },
      { name: "Service Account Analysis", description: "Identify over-privileged service accounts and stale credentials",        supported: true },
    ],
  },
  Linux: {
    os: "linux", icon: "⊗", color: "#E2A62D",
    capabilities: [
      { name: "Package Inventory",       description: "apt/yum/dnf/rpm — full installed package catalog with CVE mapping",       supported: true },
      { name: "CIS Benchmark",           description: "CIS Linux Benchmark L1/L2 automated assessment",                         supported: true },
      { name: "File Integrity Monitoring",description: "inotify-based FIM on /etc, /bin, /usr/bin, custom paths",               supported: true },
      { name: "Syslog Forwarding",       description: "Forward syslog, auth.log, kern.log to event bus",                        supported: true },
      { name: "Container Runtime",       description: "Docker & containerd: image inventory, running containers, misconfigs",    supported: true },
      { name: "Kernel Module Audit",     description: "Detect unsigned or unexpected kernel modules",                            supported: true },
      { name: "Cron Job Monitoring",     description: "Enumerate all cron jobs, detect persistence via cron",                   supported: true },
      { name: "Network Socket Audit",    description: "Enumerate open sockets, listening ports, unexpected connections",        supported: false },
    ],
  },
  macOS: {
    os: "macos", icon: "⌘", color: "#6B7280",
    capabilities: [
      { name: "TCC Privacy Audit",       description: "Audit app permissions: Camera, Mic, Full Disk Access, Contacts",         supported: true },
      { name: "Gatekeeper / Notarization",description: "Verify app signatures, detect unsigned binaries",                      supported: true },
      { name: "Launch Agent Monitoring", description: "Detect persistence via LaunchAgents and LaunchDaemons",                  supported: true },
      { name: "Keychain Integrity",      description: "Detect unexpected keychain modifications and credential access",         supported: true },
      { name: "MDM Profile Audit",       description: "Enumerate installed MDM profiles, detect rogue profiles",                supported: true },
      { name: "Brew Package Inventory",  description: "Enumerate Homebrew packages for shadow IT and vuln detection",           supported: false },
      { name: "FileVault Status",        description: "Verify disk encryption status and recovery key rotation",                supported: true },
      { name: "SIP / System Integrity",  description: "Report System Integrity Protection status and modifications",            supported: true },
    ],
  },
  Mobile: {
    os: "mobile", icon: "⬡", color: "#8B5CF6",
    capabilities: [
      { name: "Jailbreak / Root Detection",description: "Detect jailbroken iOS or rooted Android devices",                     supported: true },
      { name: "App Inventory",            description: "Enumerate installed applications, versions, signing certs",              supported: true },
      { name: "MDM Compliance Check",     description: "Verify MDM enrollment, profile compliance, passcode policy",            supported: true },
      { name: "Network Traffic Audit",    description: "Detect VPN bypass, DNS-over-HTTPS, certificate pinning anomalies",      supported: true },
      { name: "OS Patch Level",           description: "Report iOS/Android OS version and patch date against CVE database",     supported: true },
      { name: "App Permission Audit",     description: "Enumerate app permissions: Camera, Contacts, Location, Microphone",     supported: true },
      { name: "Device Encryption",        description: "Verify device encryption status (FileVault / Android FDE)",             supported: true },
      { name: "Biometric Policy",         description: "Verify biometric authentication is enabled and enforced by MDM",        supported: false },
    ],
  },
  Cloud: {
    os: "cloud", icon: "☁", color: "#0EA5E9",
    capabilities: [
      { name: "IAM Policy Audit",        description: "Enumerate IAM roles, policies, privilege paths, public exposure",        supported: true },
      { name: "Storage Bucket Analysis", description: "S3/GCS/Blob: public ACLs, encryption, access logs, versioning",         supported: true },
      { name: "Security Group Review",   description: "Flag permissive ingress/egress rules, 0.0.0.0/0 exposure",              supported: true },
      { name: "Config Drift Detection",  description: "Detect drift from approved IaC baseline (Terraform / CDK)",             supported: true },
      { name: "Runtime Threat Detection",description: "CloudTrail/Activity Log anomalies, credential exfiltration patterns",    supported: true },
      { name: "Key Management Audit",    description: "KMS / Key Vault: key rotation, expiry, usage policy compliance",        supported: true },
      { name: "Container Security",      description: "EKS/GKE/AKS pod security policies, image scan results, RBAC",          supported: true },
      { name: "Secret Scanner",          description: "Scan environment variables, config maps, Secrets for exposed credentials",supported: false },
    ],
  },
  Docker: {
    os: "docker", icon: "🐳", color: "#2496ED",
    capabilities: [
      { name: "Image Vulnerability Scan",  description: "Scan Docker images for CVEs using Trivy/Grype; block critical findings in CI/CD",   supported: true  },
      { name: "Dockerfile Policy Audit",   description: "Lint Dockerfiles against CIS Docker Benchmark: USER, COPY vs ADD, HEALTHCHECK",     supported: true  },
      { name: "Container Runtime Security",description: "Monitor running containers for privilege escalation, namespace breakouts, anomalies",supported: true  },
      { name: "Registry Access Control",   description: "Audit Docker Hub / ECR / GCR / ACR push/pull permissions and image signing status", supported: true  },
      { name: "Secret & Env Leak Detection",description: "Detect secrets baked into image layers or exposed via ENV/ARG in Dockerfiles",     supported: true  },
      { name: "Image Signing & Provenance",description: "Verify Docker Content Trust (Notary v2), Sigstore/Cosign signatures, SBOM",         supported: true  },
      { name: "Build Pipeline Compliance", description: "Gate CI/CD pipelines: enforce scan-before-push, signed-image, no-root policies",   supported: true  },
      { name: "Container Isolation Audit", description: "Review seccomp profiles, AppArmor/SELinux labels, capability drops, read-only FS",  supported: false },
      // DevSecOps
      { name: "SAST in Dockerfile Stage",  description: "Inject Semgrep/Checkmarx scan as a multi-stage Docker build step and collect results",supported: true },
      { name: "Dependency SCA Scan",       description: "Run Snyk/OWASP Dependency-Check in image build; fail on high/critical CVEs",        supported: true },
    ],
  },
  Kubernetes: {
    os: "kubernetes", icon: "⎈", color: "#326CE5",
    capabilities: [
      { name: "CIS K8s Benchmark",         description: "Automated CIS Kubernetes Benchmark Level 1 & 2 assessment via kube-bench",          supported: true  },
      { name: "RBAC Audit",                description: "Enumerate ClusterRoles, RoleBindings; flag wildcard verbs, overprivileged service accounts",supported: true },
      { name: "Pod Security Standards",    description: "Enforce Restricted/Baseline Pod Security Standards; detect privileged pods, host-PID",supported: true  },
      { name: "Network Policy Enforcement",description: "Verify namespace-level NetworkPolicies; flag pods with no egress/ingress restriction", supported: true  },
      { name: "Secrets Management Audit",  description: "Detect plain-text Secrets vs Sealed Secrets/External Secrets Operator usage",        supported: true  },
      { name: "API Server Audit Logging",  description: "Forward K8s audit log to SIEM; alert on sensitive verbs (exec, port-forward, delete)",supported: true  },
      { name: "Image Policy & Admission",  description: "Enforce OPA Gatekeeper / Kyverno policies: signed images, no-latest, resource limits", supported: true  },
      { name: "Namespace Isolation Review",description: "Audit cross-namespace access, Ingress exposure, and multi-tenant isolation hygiene",   supported: true  },
      // DevSecOps
      { name: "IaC Security Scan (Helm)",  description: "Run Checkov/Terrascan on Helm charts and raw manifests; fail pipeline on policy breach",supported: true },
      { name: "Runtime Threat Detection",  description: "Falco rules: detect crypto-mining, reverse shells, sensitive mount access in pods",    supported: true },
      { name: "Supply Chain Verification", description: "Verify SBOM attestations and Sigstore signatures before admission to cluster",         supported: false},
    ],
  },
  AWS: {
    os: "aws", icon: "⬡", color: "#FF9900",
    capabilities: [
      { name: "IAM & SCP Audit",           description: "Enumerate IAM users, roles, SCP policies; flag unused permissions, Access Analyzer",  supported: true  },
      { name: "Security Hub Findings",     description: "Ingest AWS Security Hub findings, standards (CIS, FSBP, PCI-DSS) into risk register",  supported: true  },
      { name: "GuardDuty Detections",      description: "Stream GuardDuty threat detections: EC2, S3, IAM, EKS, Lambda anomalies",              supported: true  },
      { name: "CloudTrail Audit",          description: "Monitor CloudTrail for sensitive API calls, credential abuse, root activity",           supported: true  },
      { name: "Config Rules Compliance",   description: "AWS Config rule evaluations: non-compliant resources, drift, remediation status",       supported: true  },
      { name: "S3 Bucket Posture",         description: "Detect public buckets, missing encryption, no versioning, disabled access logs",        supported: true  },
      { name: "Secrets Manager Audit",     description: "Audit secret rotation schedules, unused secrets, cross-account access policies",        supported: true  },
      { name: "VPC Flow Log Analysis",     description: "Analyse VPC Flow Logs for rejected traffic, unusual cross-AZ flows, exfil patterns",    supported: true  },
      // DevSecOps
      { name: "CodePipeline Security Gate",description: "Inject SAST/DAST/SCA gates in AWS CodePipeline; block deploy on policy failure",       supported: true  },
      { name: "ECR Image Scanning",        description: "Enable ECR enhanced scanning (Inspector); gate ECS/EKS deploys on critical CVEs",       supported: true  },
      { name: "Lambda & IaC Scan",         description: "Scan CloudFormation / CDK templates with Checkov; audit Lambda function permissions",   supported: false },
    ],
  },
  Azure: {
    os: "azure", icon: "⊞", color: "#0078D4",
    capabilities: [
      { name: "Defender for Cloud",        description: "Microsoft Defender for Cloud secure score, recommendations, security alerts",           supported: true  },
      { name: "Entra ID & RBAC Audit",     description: "Enumerate Entra (AAD) roles, PIM assignments, Conditional Access, risky sign-ins",     supported: true  },
      { name: "Azure Policy Compliance",   description: "Policy initiative assignments, non-compliant resources, remediation tasks",             supported: true  },
      { name: "Key Vault Audit",           description: "Diagnose Key Vault: soft-delete, purge protection, access policies, secret expiry",     supported: true  },
      { name: "NSG & Firewall Review",     description: "Flag overly permissive NSG rules, Any/Any, internet-exposed management ports",          supported: true  },
      { name: "Activity Log Monitoring",   description: "Azure Activity Log: control-plane events, privileged operations, policy changes",       supported: true  },
      { name: "Blob Storage Posture",      description: "Detect public blob access, missing immutability, disabled soft-delete, no encryption",  supported: true  },
      { name: "Privileged Identity Mgmt",  description: "PIM just-in-time role activations, orphaned assignments, alert on permanent Global Admin",supported: true},
      // DevSecOps
      { name: "Azure DevOps Pipeline Gate",description: "Inject security scan tasks in ADO pipelines; block release on critical vulnerability",  supported: true  },
      { name: "ACR Defender Image Scan",   description: "Microsoft Defender for Containers: ACR image scanning, Kubernetes workload protection",  supported: true  },
      { name: "Bicep / ARM IaC Scan",      description: "Scan Bicep and ARM templates with Checkov/PSRule.Azure before resource deployment",      supported: false },
    ],
  },
  GCP: {
    os: "gcp", icon: "◈", color: "#4285F4",
    capabilities: [
      { name: "Security Command Center",   description: "Ingest SCC Premium findings: misconfigs, vulnerabilities, threats, sensitive data",     supported: true  },
      { name: "IAM & Org Policy Audit",    description: "Enumerate org-level IAM, org policies, service account keys, privilege escalation paths",supported: true },
      { name: "Cloud Audit Logs",          description: "Admin Activity, Data Access, System Event logs — forward to SIEM, alert on anomalies",  supported: true  },
      { name: "VPC Firewall Rules Review", description: "Flag 0.0.0.0/0 ingress, disabled VPC Flow Logs, unrestricted SSH/RDP ports",            supported: true  },
      { name: "Cloud KMS Audit",           description: "Key rotation schedule, CMEK coverage, IAM bindings on crypto keys, version lifecycle",  supported: true  },
      { name: "GKE Node & Cluster Security",description: "Shielded nodes, binary authorisation, workload identity, private clusters, RBAC",      supported: true  },
      { name: "Cloud Armor / WAF",         description: "Review Cloud Armor security policies, rate limiting, reCAPTCHA, WAF rule coverage",     supported: true  },
      { name: "Artifact Registry Security",description: "Container Analysis CVE scan results, VPC-SC perimeter, binary authorisation policy",    supported: true  },
      // DevSecOps
      { name: "Cloud Build Security Gate", description: "Inject SAST/container scan steps in Cloud Build; block deploy on critical policy breach",supported: true  },
      { name: "Terraform / Deployment Mgr",description: "Scan Terraform and Deployment Manager templates with Checkov before GCP provisioning",  supported: true  },
      { name: "Confidential Computing",    description: "Audit Confidential VM / Confidential GKE node usage for sensitive workloads",            supported: false },
    ],
  },
};
