// ── Framework Implementation Steps, Audit Checklists & Template Details ──────
// Detailed compliance journey data for AIGO-X GRC Platform

export interface ImplementationPhase {
  phase: number;
  title: string;
  icon: string;
  timeframe: string;
  description: string;
  tasks: string[];
  deliverables: string[];
}

export interface AuditChecklistItem {
  item: string;
  required: boolean;
}

export interface AuditDomain {
  domain: string;
  icon: string;
  items: AuditChecklistItem[];
}

export interface TemplateDetail {
  name: string;
  description: string;
  required: boolean;
  type: "policy" | "form" | "checklist" | "report" | "plan" | "register" | "procedure" | "assessment";
}

export interface FrameworkDetail {
  frameworkId: string;
  certificationBody?: string;
  totalDuration: string;
  applicableTo: string;
  implementationPhases: ImplementationPhase[];
  auditChecklist: AuditDomain[];
  templateDetails: TemplateDetail[];
}

// ── Helper to build a generic fallback for any framework ─────────────────────
export const GENERIC_DETAIL: Omit<FrameworkDetail, "frameworkId"> = {
  totalDuration: "12–18 months",
  applicableTo: "All applicable organisations",
  implementationPhases: [
    { phase:1, title:"Initiation & Scoping", icon:"🎯", timeframe:"Weeks 1–3",
      description:"Establish project governance, define scope boundaries, and secure executive sponsorship and budget.",
      tasks:["Obtain executive sponsorship and budget approval","Define framework scope and applicability boundaries","Establish a cross-functional compliance steering committee","Conduct initial readiness survey with key stakeholders","Develop project plan with milestones and accountability matrix"],
      deliverables:["Project Charter","Scope Statement","Steering Committee Terms of Reference","Initial Readiness Survey Report"] },
    { phase:2, title:"Gap Assessment", icon:"📊", timeframe:"Weeks 4–8",
      description:"Assess current state against all framework requirements to identify gaps and prioritise remediation.",
      tasks:["Map all existing policies and controls to framework requirements","Conduct interviews with process owners and control owners","Identify partial implementations and undocumented controls","Classify gaps by severity (critical / major / minor)","Estimate effort and cost for each gap remediation"],
      deliverables:["Gap Analysis Report","Control Maturity Heatmap","Risk-Prioritised Remediation Roadmap","Effort & Cost Estimates"] },
    { phase:3, title:"Policy & Procedure Development", icon:"📝", timeframe:"Weeks 6–14",
      description:"Develop or update all required policies, procedures, standards and guidelines to meet framework requirements.",
      tasks:["Draft or update core information security policy","Create supporting policies (access control, encryption, change management, incident response)","Develop procedure documents and work instructions","Conduct internal review and legal review","Obtain management approval and publish in document management system"],
      deliverables:["Information Security Policy (Board-approved)","Supporting Policy Pack","Procedure Library","Approved Document Register"] },
    { phase:4, title:"Control Implementation", icon:"⚙", timeframe:"Weeks 8–22",
      description:"Implement or strengthen technical, administrative and physical controls to close identified gaps.",
      tasks:["Implement technical security controls (network, endpoint, identity, data)","Deploy monitoring and logging infrastructure","Implement access management controls (MFA, PAM, IAM)","Conduct staff security awareness training","Implement asset inventory and classification","Complete vendor/third-party risk assessments"],
      deliverables:["Control Implementation Tracker","Asset Register","Training Completion Records","Vendor Assessment Reports","Technical Configuration Baselines"] },
    { phase:5, title:"Internal Audit & Testing", icon:"🔍", timeframe:"Weeks 20–26",
      description:"Conduct independent internal assessment to validate control effectiveness and identify residual gaps.",
      tasks:["Develop internal audit plan aligned to framework controls","Execute control testing (inquiry, observation, inspection, re-performance)","Collect and review evidence for each control","Document all non-conformities and observations","Track corrective and preventive actions (CAPA)","Obtain management sign-off on CAPA plans"],
      deliverables:["Internal Audit Plan","Audit Evidence Register","Non-Conformity Reports","CAPA Tracker","Internal Audit Report"] },
    { phase:6, title:"Management Review & Certification", icon:"🏆", timeframe:"Weeks 26–30+",
      description:"Conduct formal management review, address residual findings and prepare for external audit or certification.",
      tasks:["Conduct management review meeting (scope, audit results, risk status, objectives)","Close all critical/major CAPAs from internal audit","Engage external auditor or certification body","Support Stage 1 (documentation) audit","Support Stage 2 (on-site) audit","Respond to auditor findings within agreed timelines","Receive certification or compliance attestation"],
      deliverables:["Management Review Minutes","Final CAPA Closure Evidence","External Audit Report","Certification or Compliance Attestation","Continuous Improvement Plan"] },
  ],
  auditChecklist: [
    { domain:"Governance & Leadership", icon:"🏛",
      items:[
        { item:"Board-approved information security policy exists and is current", required:true },
        { item:"Executive ownership of compliance programme is defined", required:true },
        { item:"Compliance roles and responsibilities are documented", required:true },
        { item:"Annual management review of the framework is conducted", required:true },
        { item:"Compliance budget is allocated and approved", required:true },
      ]},
    { domain:"Risk Management", icon:"⚠",
      items:[
        { item:"Formal risk assessment has been completed within the last 12 months", required:true },
        { item:"Risk register maintained and reviewed quarterly", required:true },
        { item:"Risk treatment plans are documented and tracked", required:true },
        { item:"Risk acceptance is documented and signed off by management", required:false },
        { item:"Risk owners are assigned for each identified risk", required:true },
      ]},
    { domain:"Controls & Technical Safeguards", icon:"🛡",
      items:[
        { item:"Access control policy implemented and enforced", required:true },
        { item:"Multi-factor authentication (MFA) deployed for critical systems", required:true },
        { item:"Patch management programme active with SLA tracking", required:true },
        { item:"Encryption applied to data at rest and in transit", required:true },
        { item:"Security monitoring and log retention in place", required:true },
        { item:"Vulnerability management programme operational", required:true },
      ]},
    { domain:"Incident Management", icon:"🚨",
      items:[
        { item:"Incident response policy and plan documented", required:true },
        { item:"Incident response team defined with roles and contacts", required:true },
        { item:"Incident classification criteria defined", required:true },
        { item:"Regulatory reporting timelines documented and trained", required:true },
        { item:"Post-incident review process in place", required:false },
        { item:"Incident log maintained with required fields", required:true },
      ]},
    { domain:"Third-Party & Supply Chain", icon:"🤝",
      items:[
        { item:"Third-party risk assessment process defined and implemented", required:true },
        { item:"Vendor security questionnaires in use", required:true },
        { item:"Contractual security requirements included in all critical vendor contracts", required:true },
        { item:"Annual reviews of critical third-party providers conducted", required:true },
        { item:"Right-to-audit clauses included in critical vendor agreements", required:false },
      ]},
    { domain:"Awareness & Training", icon:"🎓",
      items:[
        { item:"Annual security awareness training programme exists", required:true },
        { item:"New joiner security training completed within 30 days of onboarding", required:true },
        { item:"Role-specific training for privileged users provided", required:true },
        { item:"Training completion records maintained", required:true },
        { item:"Phishing simulation exercises conducted", required:false },
      ]},
    { domain:"Audit & Compliance", icon:"📋",
      items:[
        { item:"Internal audit programme aligned to framework controls", required:true },
        { item:"External/third-party audit conducted per framework schedule", required:true },
        { item:"Audit findings tracked to closure", required:true },
        { item:"Corrective action plan (CAP) approved by management", required:true },
        { item:"Compliance reporting submitted to regulator within required timelines", required:true },
      ]},
  ],
  templateDetails: [
    { name:"Information Security Policy", description:"Top-level board-approved policy covering all framework objectives", required:true, type:"policy" },
    { name:"Risk Assessment Methodology", description:"Documented approach to identifying, analysing and evaluating risks", required:true, type:"procedure" },
    { name:"Risk Register", description:"Centralised register of all identified risks with treatment status", required:true, type:"register" },
    { name:"Incident Response Plan", description:"Step-by-step guide for detecting, containing and reporting incidents", required:true, type:"plan" },
    { name:"Asset Inventory", description:"Register of all in-scope information assets with owner and classification", required:true, type:"register" },
    { name:"Internal Audit Plan & Report", description:"Annual internal audit programme and findings report", required:true, type:"report" },
    { name:"Management Review Minutes", description:"Minutes from annual management review of the compliance programme", required:true, type:"report" },
    { name:"Staff Training Record", description:"Attendance and completion records for all required training", required:true, type:"register" },
    { name:"Vendor Security Assessment", description:"Third-party security questionnaire results and risk ratings", required:true, type:"assessment" },
    { name:"CAPA Tracker", description:"Corrective and preventive actions with due dates and closure evidence", required:true, type:"register" },
  ],
};

// ── INDIA FRAMEWORKS ─────────────────────────────────────────────────────────

const IN_DPDP: FrameworkDetail = {
  frameworkId: "in_dpdp",
  certificationBody: "Data Protection Board of India (DPBI)",
  totalDuration: "9–12 months",
  applicableTo: "All organisations processing digital personal data of Indian residents",
  implementationPhases: [
    { phase:1, title:"Data Discovery & Classification", icon:"🗺", timeframe:"Weeks 1–4",
      description:"Identify all personal data processed by the organisation, map data flows and classify data types to determine DPDP applicability and obligations.",
      tasks:[
        "Inventory all databases, applications and processes handling personal data",
        "Map personal data flows across collection, processing, storage and deletion",
        "Identify Special Categories of Personal Data (health, financial, biometric, children's data)",
        "Assess whether organisation qualifies as Significant Data Fiduciary (SDF)",
        "Identify all data processors and sub-processors",
        "Determine retention periods and deletion obligations for each data category",
      ],
      deliverables:["Personal Data Inventory","Data Flow Map (RoPA-style)","Data Classification Register","SDF Assessment Report","Processor Mapping Document"] },
    { phase:2, title:"Consent Architecture Design", icon:"✅", timeframe:"Weeks 5–10",
      description:"Design and implement lawful consent mechanisms with clear notice, granular consent options, withdrawal facility and a reliable consent record store.",
      tasks:[
        "Design Notice framework — plain language, itemised purpose, processing description",
        "Implement granular consent mechanisms per processing purpose",
        "Build consent withdrawal mechanism (at least as easy as giving consent)",
        "Design consent record management system with audit trail",
        "Update website cookie consent and privacy banners",
        "Design consent for children's data processing (verifiable parental consent, age-gating)",
        "Draft consent notice templates in all required languages",
      ],
      deliverables:["Consent Framework Design","Notice Templates (English + regional languages)","Consent Record Management System","Children's Data Consent Procedure","Cookie / DPDP Banner"] },
    { phase:3, title:"Data Principal Rights Implementation", icon:"⚖", timeframe:"Weeks 8–14",
      description:"Implement mechanisms for all four Data Principal rights under the DPDP Act: information, correction/erasure, grievance redressal and nomination.",
      tasks:[
        "Build Data Principal Rights request portal (web + app)",
        "Define 30-day response SLA and escalation process",
        "Implement right to access personal data — respond with data summary",
        "Implement right to correction and erasure — update / delete from all systems",
        "Implement right to grievance redressal — dedicated grievance officer with contact details",
        "Implement right to nominate — nomination form for incapacitated Data Principals",
        "Test end-to-end workflow for each right with sample requests",
        "Train customer-facing staff on handling rights requests",
      ],
      deliverables:["Rights Request Portal","Rights Response SLA Document","Grievance Officer Appointment Letter & Publication","Nomination Facility","Staff Training Pack"] },
    { phase:4, title:"Governance, Policies & DPO Setup", icon:"📋", timeframe:"Weeks 10–16",
      description:"Establish privacy governance framework, appoint required personnel and update all contracts and policies.",
      tasks:[
        "Draft and approve Privacy Policy under DPDP Act requirements",
        "Appoint Data Protection Officer (DPO) if SDF designation applies",
        "Update all vendor/processor agreements with DPDP-compliant clauses",
        "Conduct Cross-Border Personal Data Transfer (CBPDT) impact assessment",
        "Implement Data Sharing Agreements with Data Processors",
        "Run internal DPDP awareness training for all staff handling personal data",
        "Create internal escalation matrix for privacy incidents",
      ],
      deliverables:["Board-Approved Privacy Policy","DPO Charter (if SDF)","Updated Processor Agreements","CBPDT Assessment","Privacy Training Completion Records"] },
    { phase:5, title:"Technical Safeguards & Security Controls", icon:"🛡", timeframe:"Weeks 12–20",
      description:"Implement appropriate technical and organisational security measures to protect personal data as required by the DPDP Act.",
      tasks:[
        "Deploy data encryption at rest and in transit for all personal data repositories",
        "Implement access controls and role-based access to personal data",
        "Enable data minimisation — review and remove unnecessary personal data collection",
        "Implement data deletion / anonymisation workflows for expired data",
        "Configure audit logs for all personal data access and modifications",
        "Implement Data Loss Prevention (DLP) controls for sensitive personal data",
        "Conduct security testing on all systems storing personal data",
      ],
      deliverables:["Data Encryption Policy","Access Control Matrix for Personal Data","Data Minimisation Review Report","Deletion / Anonymisation Procedure","DLP Configuration Evidence"] },
    { phase:6, title:"Breach Detection & Response Setup", icon:"🚨", timeframe:"Weeks 15–20",
      description:"Implement personal data breach detection, containment and notification procedures aligned with DPDP Act reporting obligations.",
      tasks:[
        "Define personal data breach detection triggers and escalation matrix",
        "Implement breach notification workflow for Data Protection Board of India (DPBI)",
        "Draft Data Principal breach notification templates (plain language)",
        "Test breach response procedure via tabletop exercise",
        "Document breach log with required fields per DPDP Rules",
        "Train incident response team on DPDP breach classification",
      ],
      deliverables:["Breach Response Plan","DPBI Notification Template","Data Principal Notification Template","Breach Log Template","Tabletop Exercise Summary"] },
    { phase:7, title:"Ongoing Compliance & Audit", icon:"🔄", timeframe:"Weeks 20+ (Ongoing)",
      description:"Establish continuous compliance monitoring, internal audit cycle and preparation for DPBI registration (for Significant Data Fiduciaries).",
      tasks:[
        "Schedule annual internal privacy audit against DPDP Act requirements",
        "Register with DPBI (if designated as Significant Data Fiduciary)",
        "Implement periodic Data Protection Impact Assessment (DPIA) for high-risk processing",
        "Review and update consent notices after product changes",
        "Refresh Data Principal Rights training for staff annually",
        "Monitor DPBI guidance and DPDP Rules updates; update programme accordingly",
      ],
      deliverables:["Annual Privacy Audit Report","DPBI Registration (if SDF)","DPIA Programme","Continuous Improvement Register"] },
  ],
  auditChecklist: [
    { domain:"Governance & Accountability", icon:"🏛", items:[
      { item:"Privacy Policy published and covers all DPDP Act required elements", required:true },
      { item:"Data Protection Officer (DPO) appointed (mandatory for SDFs)", required:false },
      { item:"Personal data inventory maintained and reviewed quarterly", required:true },
      { item:"Data flow maps documented for all processing activities", required:true },
      { item:"Processor agreements updated with DPDP-compliant clauses", required:true },
      { item:"Board-level privacy governance in place", required:false },
    ]},
    { domain:"Consent & Notice", icon:"✅", items:[
      { item:"Plain-language Notice provided before collecting personal data", required:true },
      { item:"Granular, specific and free consent obtained for each purpose", required:true },
      { item:"Consent withdrawal mechanism is at least as easy as giving consent", required:true },
      { item:"Consent records maintained with timestamp and version of notice", required:true },
      { item:"Children's data: verifiable parental consent obtained for users under 18", required:true },
      { item:"Age-gating or age verification implemented for services likely used by children", required:true },
    ]},
    { domain:"Data Principal Rights", icon:"⚖", items:[
      { item:"Right to access personal data — mechanism available and tested", required:true },
      { item:"Right to correction — data update process implemented within 30 days", required:true },
      { item:"Right to erasure — data deletion workflow operational", required:true },
      { item:"Grievance Officer details published on website and app", required:true },
      { item:"Right to nominate — nomination form available", required:true },
      { item:"30-day response SLA for rights requests enforced", required:true },
    ]},
    { domain:"Data Minimisation & Retention", icon:"🗄", items:[
      { item:"Only personal data necessary for the stated purpose is collected", required:true },
      { item:"Retention periods defined for each data category", required:true },
      { item:"Automated deletion or anonymisation implemented after retention period", required:true },
      { item:"Unnecessary personal data identified and deleted in backups and archives", required:false },
    ]},
    { domain:"Cross-Border Transfer", icon:"🌐", items:[
      { item:"Cross-border personal data transfer assessment conducted", required:true },
      { item:"Restricted countries list checked against DPBI notifications", required:true },
      { item:"Transfer mechanisms documented where transfer is permitted", required:true },
    ]},
    { domain:"Security Safeguards", icon:"🔐", items:[
      { item:"Encryption at rest and in transit implemented for all personal data", required:true },
      { item:"Access controls restrict personal data access to authorised personnel only", required:true },
      { item:"Audit logs for personal data access maintained for 12 months minimum", required:true },
      { item:"Data Loss Prevention (DLP) controls in place", required:false },
      { item:"Security testing of personal data systems conducted annually", required:true },
    ]},
    { domain:"Breach Management", icon:"🚨", items:[
      { item:"Personal data breach detection and alerting in place", required:true },
      { item:"Breach classification criteria aligned to DPDP Act definitions", required:true },
      { item:"DPBI breach notification procedure documented and tested", required:true },
      { item:"Data Principal breach notification template ready", required:true },
      { item:"Breach log maintained with required fields", required:true },
    ]},
  ],
  templateDetails: [
    { name:"Privacy Notice / Policy (DPDP-compliant)", description:"Public-facing privacy notice covering all DPDP Act required disclosures, in plain language", required:true, type:"policy" },
    { name:"Consent Collection Template", description:"Standardised consent mechanism with itemised purposes and withdrawal link", required:true, type:"form" },
    { name:"Consent Withdrawal Form", description:"Simple form for Data Principals to withdraw consent for specific purposes", required:true, type:"form" },
    { name:"Data Principal Rights Request Form", description:"Unified form covering access, correction, erasure, nomination rights", required:true, type:"form" },
    { name:"Grievance Redressal Procedure", description:"Internal SOP for handling Data Principal grievances within 30 days", required:true, type:"procedure" },
    { name:"Personal Data Inventory (RoPA)", description:"Register of all processing activities with purpose, lawful basis, retention, recipients", required:true, type:"register" },
    { name:"Data Flow Mapping Template", description:"Detailed data flow diagram for each processing activity", required:true, type:"assessment" },
    { name:"Cross-Border Transfer Impact Assessment", description:"Assessment of whether proposed transfers comply with DPDP Act restrictions", required:true, type:"assessment" },
    { name:"Data Processor Agreement (DPDP-compliant)", description:"Contractual clauses binding processors to DPDP Act obligations", required:true, type:"policy" },
    { name:"Children's Data Parental Consent Form", description:"Age verification and verifiable parental consent mechanism for minors' data", required:true, type:"form" },
    { name:"Data Breach Response Plan", description:"Step-by-step procedure for detecting, containing and notifying personal data breaches", required:true, type:"plan" },
    { name:"DPBI Breach Notification Template", description:"Standardised form for notifying the Data Protection Board of India of a breach", required:true, type:"form" },
    { name:"Significant Data Fiduciary (SDF) Self-Assessment", description:"Assessment worksheet to determine whether SDF designation applies", required:false, type:"assessment" },
    { name:"Annual Internal Privacy Audit Checklist", description:"Checklist for annual internal review of DPDP Act compliance", required:true, type:"checklist" },
  ],
};

const IN_RBI: FrameworkDetail = {
  frameworkId: "in_rbi",
  certificationBody: "CERT-In Empanelled Auditor / RBI IS Audit",
  totalDuration: "12–18 months (initial); annual cycle thereafter",
  applicableTo: "All Scheduled Commercial Banks, Cooperative Banks, NBFCs, Payment System Operators licensed by RBI",
  implementationPhases: [
    { phase:1, title:"Governance & CISO Setup", icon:"🏛", timeframe:"Weeks 1–4",
      description:"Establish board-level cybersecurity governance, appoint CISO, form IT Steering Committee and set cyber budget.",
      tasks:[
        "Draft and obtain Board approval for Cybersecurity Policy (aligned to RBI Master Direction on IT Framework)",
        "Appoint CISO — mandatory for banks with total assets > ₹5,000 crore; CISO must report to Board/MD",
        "Constitute IT Steering Committee (ITSC) with quarterly meeting cadence",
        "Allocate minimum 15% of annual IT budget to cybersecurity",
        "Define Cyber Crisis Management Plan (CCMP) structure",
        "Register entity on RBI CSITE portal for incident reporting",
        "Define metrics for Board-level cybersecurity KPI dashboard",
      ],
      deliverables:["Board-Approved Cybersecurity Policy","CISO Appointment Letter / Charter","ITSC Terms of Reference","Cybersecurity Budget Allocation","RBI CSITE Registration Confirmation"] },
    { phase:2, title:"Critical Asset Identification & Risk Assessment", icon:"🗺", timeframe:"Weeks 5–10",
      description:"Identify critical IT assets (CBS, SWIFT, payment gateways, ATMs, internet banking), conduct cyber risk assessment and prioritise remediation.",
      tasks:[
        "Identify and classify all critical information assets: CBS (Core Banking System), SWIFT messaging, ATM Switch, internet banking, mobile banking, payment gateways",
        "Map data flows between critical systems and external networks",
        "Conduct Cyber Risk Assessment using RBI-prescribed methodology",
        "Identify Crown Jewel assets requiring enhanced protection",
        "Map all third-party service providers (TSPs) and their access to critical systems",
        "Define Risk Appetite Statement for cyber risk",
        "Produce Risk Treatment Plan with remediation priorities",
      ],
      deliverables:["Critical Asset Register","Data Flow Maps","Cyber Risk Assessment Report","Crown Jewel Asset List","TSP Mapping","Risk Treatment Plan"] },
    { phase:3, title:"Network & Application Security Controls", icon:"🛡", timeframe:"Weeks 8–22",
      description:"Implement technical security controls for network perimeter, internal segmentation, application security and privileged access.",
      tasks:[
        "Deploy and tune Next-Generation Firewalls at network perimeter and between zones",
        "Implement network segmentation — CBS, payment, internet, DMZ zones",
        "Deploy Intrusion Detection / Prevention System (IDS/IPS)",
        "Implement Web Application Firewall (WAF) for all internet-facing banking portals",
        "Enforce HTTPS/TLS 1.2+ on all customer-facing applications",
        "Implement Privileged Access Management (PAM) for all privileged accounts",
        "Deploy Multi-Factor Authentication (MFA) for all admin access and internet banking",
        "Conduct VAPT on internet banking, mobile banking and payment gateway apps",
        "Implement API security controls for Open Banking / FinTech integrations",
        "Review and harden ATM network security",
        "Implement endpoint detection and response (EDR) across all endpoints",
      ],
      deliverables:["Network Architecture Diagram (segmented)","Firewall Rule Review Report","WAF Deployment Evidence","PAM Implementation Evidence","MFA Deployment Report","VAPT Report — Internet Banking","VAPT Report — Mobile Banking","API Security Review"] },
    { phase:4, title:"SOC Establishment & SIEM Deployment", icon:"📡", timeframe:"Weeks 12–22",
      description:"Set up or validate Security Operations Centre (SOC) with 24x7 monitoring capability, SIEM and threat intelligence for banking threats.",
      tasks:[
        "Define SOC operating model — internal vs. outsourced (to CERT-In empanelled MSSP)",
        "Deploy SIEM with use cases covering: failed login attempts, privilege escalation, data exfiltration, SWIFT transaction anomalies",
        "Onboard critical log sources: CBS, SWIFT, firewalls, IDS/IPS, Active Directory, payment systems",
        "Configure threat intelligence feeds (RBI CSITE, CERT-In, banking sector ISACs)",
        "Define SOC SLAs: alert triage within 15 min, escalation within 30 min for P1",
        "Test SOC detection coverage with simulated attack scenarios",
        "Establish 24x7 monitoring for internet banking, payment gateway and mobile banking",
        "Create SOC runbooks for common banking cyber threats (account takeover, SWIFT fraud, ATM jackpotting)",
      ],
      deliverables:["SOC Charter","SIEM Use Case Library (Banking-Specific)","Log Source Inventory","SOC SLA Document","SOC Readiness Assessment Report","SOC Runbook Pack"] },
    { phase:5, title:"Cyber Resilience & BCP Testing", icon:"🔄", timeframe:"Weeks 18–26",
      description:"Validate recovery capabilities through BCP/DR testing, DDoS simulation and cyber crisis management exercises.",
      tasks:[
        "Conduct Business Impact Analysis (BIA) for all critical banking applications",
        "Test Disaster Recovery Plan — CBS recovery within RTO (≤4h for large banks)",
        "Conduct DDoS simulation exercise for internet banking",
        "Run tabletop Cyber Crisis Management exercise with senior management",
        "Test SWIFT resilience and offline payment processing fallback",
        "Validate ATM network fallback procedures",
        "Test Data Loss Prevention (DLP) controls for data exfiltration scenarios",
      ],
      deliverables:["BIA Report","DR Test Report (CBS Recovery)","DDoS Simulation Report","CCMP Tabletop Exercise Summary","BCP/DR RTO/RPO Achievement Record"] },
    { phase:6, title:"VAPT, Red Team & Compliance Validation", icon:"🔬", timeframe:"Weeks 22–28",
      description:"Conduct comprehensive VAPT, red team exercises, and prepare for RBI annual cyber audit.",
      tasks:[
        "Engage CERT-In empanelled firm for annual VAPT (network, web, mobile, API)",
        "Conduct Red Team assessment (for banks with total assets > ₹20,000 crore)",
        "Execute phishing simulation campaign targeting banking staff",
        "Review VAPT findings and create remediation tracker",
        "Verify all critical VAPT findings remediated before RBI audit",
        "Prepare Annual Cyber Security Report (ACSR) for RBI submission",
        "Conduct Board-level cybersecurity posture review",
      ],
      deliverables:["VAPT Report (CERT-In empanelled)","Red Team Report","Phishing Simulation Report","Vulnerability Remediation Tracker","Annual Cyber Security Report (ACSR) for RBI","Board Cybersecurity Presentation"] },
    { phase:7, title:"Annual RBI Audit & Continuous Monitoring", icon:"📊", timeframe:"Ongoing (Annual Cycle)",
      description:"Submit annual compliance return, support RBI IS audit and maintain continuous security monitoring programme.",
      tasks:[
        "Submit Annual IT Return to RBI (via XBRL portal)",
        "Support RBI-nominated IS Auditor during annual IS Audit",
        "Respond to IS Audit findings within prescribed timelines",
        "Maintain incident log and submit incident reports via RBI CSITE (within 2–6 hours)",
        "Conduct quarterly ITSC meetings and produce minutes",
        "Review and update Cybersecurity Policy annually",
        "Track regulatory updates from RBI (circulars, master directions) and implement changes",
      ],
      deliverables:["Annual IT Return (XBRL)","IS Audit Support Package","Incident Reports (RBI CSITE)","ITSC Minutes (Quarterly)","Updated Cybersecurity Policy"] },
  ],
  auditChecklist: [
    { domain:"Governance & Board Oversight", icon:"🏛", items:[
      { item:"Board-approved Cybersecurity Policy exists, reviewed within last 12 months", required:true },
      { item:"CISO appointed with appropriate mandate and reporting to Board / MD&CEO", required:true },
      { item:"IT Steering Committee (ITSC) constituted and meeting quarterly", required:true },
      { item:"Cybersecurity budget allocated — minimum 15% of IT budget", required:true },
      { item:"Board receives cybersecurity KPI report at least quarterly", required:true },
      { item:"Cyber Crisis Management Plan (CCMP) approved by Board", required:true },
    ]},
    { domain:"Critical Asset & Risk Management", icon:"⚠", items:[
      { item:"All critical IT assets identified and classified (CBS, SWIFT, ATM, payment gateways)", required:true },
      { item:"Crown Jewel assets identified with enhanced controls", required:true },
      { item:"Cyber Risk Assessment conducted within the last 12 months", required:true },
      { item:"Risk Treatment Plan active with remediation owners and due dates", required:true },
      { item:"Third-party service provider (TSP) risk assessments completed", required:true },
    ]},
    { domain:"Network & Perimeter Security", icon:"🌐", items:[
      { item:"Next-Generation Firewalls deployed at all network perimeter points", required:true },
      { item:"Network segmentation implemented — CBS, payment, DMZ, internet zones", required:true },
      { item:"IDS/IPS deployed and monitored 24x7", required:true },
      { item:"WAF deployed for all internet-facing banking portals", required:true },
      { item:"DDoS protection in place for internet banking and payment systems", required:true },
    ]},
    { domain:"Application & API Security", icon:"💻", items:[
      { item:"Annual VAPT conducted on internet banking by CERT-In empanelled firm", required:true },
      { item:"Annual VAPT conducted on mobile banking application", required:true },
      { item:"API security controls implemented for open banking / fintech integrations", required:true },
      { item:"Secure SDLC process defined and followed for all banking applications", required:true },
      { item:"All critical VAPT findings from previous audit remediated", required:true },
    ]},
    { domain:"Identity, Access & MFA", icon:"🔐", items:[
      { item:"Privileged Access Management (PAM) solution deployed", required:true },
      { item:"MFA enforced for all internet banking customers", required:true },
      { item:"MFA enforced for all admin and privileged user accounts", required:true },
      { item:"Quarterly privileged access review conducted", required:true },
      { item:"Separation of duties enforced for critical functions (maker-checker)", required:true },
    ]},
    { domain:"SOC Operations & Monitoring", icon:"📡", items:[
      { item:"SOC operational — 24x7 monitoring for internet banking and payment systems", required:true },
      { item:"SIEM deployed with banking-specific use cases", required:true },
      { item:"Log retention — minimum 180 days online, 1 year archived", required:true },
      { item:"SWIFT transaction anomaly monitoring in place", required:true },
      { item:"Threat intelligence feeds active (RBI CSITE, CERT-In, sector ISACs)", required:true },
    ]},
    { domain:"Incident Response & Reporting", icon:"🚨", items:[
      { item:"Cyber Incident Response Plan documented and tested via tabletop exercise", required:true },
      { item:"Entity registered on RBI CSITE portal for incident reporting", required:true },
      { item:"Major cyber incidents reported to RBI within 2–6 hours", required:true },
      { item:"Post-incident reviews conducted and learnings documented", required:true },
      { item:"CCMP tabletop exercise conducted in the last 12 months", required:true },
    ]},
    { domain:"Supply Chain & Third-Party Security", icon:"🤝", items:[
      { item:"All critical TSPs have undergone security assessment in the last 12 months", required:true },
      { item:"Contractual security SLAs in place with all critical vendors", required:true },
      { item:"Right-to-audit clause included in critical TSP contracts", required:true },
      { item:"Cloud service provider security assessment conducted", required:false },
      { item:"Outsourcing risk register maintained and reviewed quarterly", required:true },
    ]},
    { domain:"Compliance & Regulatory Reporting", icon:"📋", items:[
      { item:"Annual IT Return submitted to RBI via XBRL portal", required:true },
      { item:"Annual VAPT report by CERT-In empanelled firm produced and submitted", required:true },
      { item:"IS Audit conducted annually by RBI-empanelled auditor", required:true },
      { item:"All IS Audit findings remediated within prescribed timelines", required:true },
      { item:"Annual Cyber Security Return (ACSR) submitted to RBI", required:true },
    ]},
  ],
  templateDetails: [
    { name:"Board Cybersecurity Policy", description:"RBI-compliant board-level cybersecurity policy covering governance, risk, controls and reporting", required:true, type:"policy" },
    { name:"IT Steering Committee Charter & Minutes", description:"ITSC constitution document and quarterly meeting minutes template", required:true, type:"report" },
    { name:"Cyber Risk Assessment Report", description:"Structured risk assessment methodology and findings report for banking systems", required:true, type:"assessment" },
    { name:"Critical Asset Register (CBS / SWIFT / ATM)", description:"Register of critical IT assets with classification, owner and risk level", required:true, type:"register" },
    { name:"SOC Use Case Library (Banking)", description:"Pre-built SIEM detection use cases for banking threats including SWIFT fraud, account takeover, ATM attacks", required:true, type:"checklist" },
    { name:"VAPT Scope Document (Internet / Mobile Banking)", description:"Scope statement for annual VAPT engagement with CERT-In empanelled firm", required:true, type:"form" },
    { name:"Cyber Incident Report Template (RBI CSITE)", description:"Structured incident report form matching RBI CSITE portal fields, with 2h/6h timeline guidance", required:true, type:"form" },
    { name:"Cyber Crisis Management Plan (CCMP)", description:"Crisis management procedure for major cyber incidents, with Board escalation and media comms", required:true, type:"plan" },
    { name:"Third-Party / TSP Security Assessment Questionnaire", description:"Comprehensive security questionnaire for technology service providers", required:true, type:"assessment" },
    { name:"DDoS Response Runbook", description:"Step-by-step runbook for detecting and mitigating DDoS attacks on internet banking", required:true, type:"procedure" },
    { name:"SWIFT Security Controls Checklist (CSCF)", description:"SWIFT Customer Security Programme (CSP) self-attestation checklist", required:true, type:"checklist" },
    { name:"Annual IT Return Template (XBRL)", description:"Guidance and template for completing RBI's annual IT return submission", required:true, type:"report" },
    { name:"Board Cybersecurity Dashboard Template", description:"KPI dashboard for quarterly Board cybersecurity reporting", required:false, type:"report" },
    { name:"Privileged Access Review Template", description:"Quarterly review template for all privileged accounts and access rights", required:true, type:"checklist" },
    { name:"IS Audit Support Package", description:"Evidence pack template for supporting RBI-nominated IS Auditor during annual audit", required:true, type:"checklist" },
  ],
};

const IN_SEBI: FrameworkDetail = {
  frameworkId: "in_sebi",
  certificationBody: "CERT-In Empanelled Auditor / SEBI CIRT",
  totalDuration: "12–18 months (initial); annual audit cycle thereafter",
  applicableTo: "SEBI-regulated entities: Stock Exchanges, Depositories, Clearing Corporations (MIIs); Brokers, Mutual Funds, Portfolio Managers, Investment Advisers, Research Analysts",
  implementationPhases: [
    { phase:1, title:"Entity Classification & Gap Assessment", icon:"📊", timeframe:"Weeks 1–5",
      description:"Determine entity category under SEBI CSCRF 2024 (MII / Qualified RIA / Others), conduct comprehensive gap assessment against all 61 controls and produce a prioritised remediation roadmap.",
      tasks:[
        "Classify entity type under SEBI CSCRF 2024 (Market Infrastructure Institution, Qualified RIA, Registered Intermediary)",
        "Map all existing cybersecurity controls to SEBI CSCRF control categories",
        "Identify mandatory vs. recommended controls based on entity classification",
        "Conduct gap analysis workshop with IT, Risk and Compliance teams",
        "Prioritise gaps by criticality (critical / high / medium / low)",
        "Develop remediation roadmap with timelines and cost estimates",
        "Obtain management sign-off on roadmap and budget allocation",
      ],
      deliverables:["Entity Classification Document","Gap Analysis Report","SEBI CSCRF Control Mapping Matrix","Remediation Roadmap","Budget Approval Note"] },
    { phase:2, title:"Governance & CISO Appointment", icon:"🏛", timeframe:"Weeks 4–8",
      description:"Establish cybersecurity governance framework with Board accountability, CISO appointment (mandatory for MIIs) and risk management structure.",
      tasks:[
        "Draft and obtain Board approval for Cybersecurity Policy",
        "Appoint CISO — mandatory for Market Infrastructure Institutions (MIIs); CISO must have direct Board access",
        "Constitute Cybersecurity Risk Committee with Management, IT and Risk representation",
        "Define cybersecurity KPIs and reporting structure to Board",
        "Develop Annual Cybersecurity Strategy and submit to SEBI (for MIIs)",
        "Define Risk Appetite Statement for cyber risk",
        "Create Third-Party / TPSP Cybersecurity Risk Framework",
      ],
      deliverables:["Board-Approved Cybersecurity Policy","CISO Appointment Order","Cybersecurity Risk Committee Charter","Annual Cybersecurity Strategy (SEBI submission)","Risk Appetite Statement"] },
    { phase:3, title:"Technical Controls & Trading System Security", icon:"🛡", timeframe:"Weeks 8–20",
      description:"Implement all required technical controls with particular focus on trading systems, market data infrastructure and API security.",
      tasks:[
        "Network segmentation of trading systems (front office, back office, settlement, market data)",
        "Deploy DDoS protection for trading platforms (mandatory for MIIs)",
        "Implement Web Application Firewall (WAF) for all internet-facing order management and reporting portals",
        "Enforce MFA for all trading system access, including broker terminals",
        "Implement API security framework for algorithmic trading integrations",
        "Deploy Data Loss Prevention (DLP) for prevention of insider data exfiltration",
        "Harden order management system (OMS) and risk management system (RMS)",
        "Implement secure FTP / SFTP for all data file transfers with exchanges",
        "Deploy endpoint protection on all trading workstations",
        "Implement encryption for all sensitive market and client data",
      ],
      deliverables:["Network Architecture (trading zone segmented)","DDoS Protection Deployment Evidence","WAF Deployment Evidence","MFA Rollout Evidence","API Security Assessment","DLP Policy","OMS/RMS Hardening Report"] },
    { phase:4, title:"CSIRT / SOC Setup & Monitoring", icon:"📡", timeframe:"Weeks 12–22",
      description:"Constitute Cyber Security Incident Response Team (CSIRT), establish 24x7 SOC monitoring (mandatory for MIIs) and integrate with SEBI CIRT.",
      tasks:[
        "Constitute CSIRT with defined roles, escalation matrix and contact details",
        "Register CSIRT with SEBI CIRT (mandatory for all SEBI entities)",
        "Set up SOC with 24x7 monitoring capability (mandatory for MIIs)",
        "Deploy SIEM with use cases for market manipulation, data leakage, DDoS on trading systems",
        "Configure log collection from trading systems, order management, settlement and network devices",
        "Define incident classification for market-specific incidents (trading halt, data breach, market manipulation)",
        "Create and test playbooks for: trading system outage, DDoS attack, data breach, ransomware",
        "Establish 6-hour reporting SLA for major incidents to SEBI CIRT",
      ],
      deliverables:["CSIRT Charter","SEBI CIRT Registration Confirmation","SOC Operational Model Document","SIEM Use Cases (Market-Specific)","Incident Classification Matrix","Response Playbooks","6h Reporting SLA Document"] },
    { phase:5, title:"Business Continuity & Cyber Resilience", icon:"🔄", timeframe:"Weeks 18–26",
      description:"Test and validate BCP/DR capabilities with focus on trading system continuity, settlement resilience and cyber resilience exercises.",
      tasks:[
        "Update Business Impact Analysis (BIA) for all trading and settlement systems",
        "Test Disaster Recovery Plan — trading system RTO ≤ 2 hours for MIIs",
        "Conduct DDoS simulation on trading platform",
        "Run Cyber Resilience Tabletop Exercise with SEBI scenario",
        "Test market data feed failover and recovery",
        "Conduct phishing simulation targeting trading floor and compliance staff",
        "Validate settlement system resilience under simulated cyber attack",
        "Test third-party connectivity resilience (exchanges, depositories, clearing corporations)",
      ],
      deliverables:["BIA Report (Trading Systems)","DR Test Report (Trading System RTO)","DDoS Simulation Report","Cyber Resilience Tabletop Exercise Report","Phishing Simulation Report"] },
    { phase:6, title:"Annual SEBI Cyber Audit & Reporting", icon:"📊", timeframe:"Annual Cycle",
      description:"Conduct mandatory annual cyber audit by CERT-In empanelled firm, submit compliance report to SEBI and maintain continuous monitoring.",
      tasks:[
        "Engage CERT-In empanelled cybersecurity auditor for annual audit",
        "Scope and conduct VAPT covering trading infrastructure, web portals, mobile apps and APIs",
        "Produce Annual Cybersecurity Compliance Report (ACCR) for SEBI submission",
        "Submit incident reports to SEBI CIRT within 6h (initial) / 24h (detailed)",
        "Conduct Board-level cybersecurity review — submit to SEBI",
        "Track and remediate all audit findings within prescribed timelines",
        "Update cybersecurity risk register and report to Board quarterly",
        "Monitor SEBI circulars for CSCRF updates; implement changes promptly",
      ],
      deliverables:["Annual VAPT Report (CERT-In empanelled)","Annual Cybersecurity Compliance Report (SEBI)","Board Cybersecurity Review Minutes","Incident Reports Submitted to SEBI CIRT","Audit Finding Remediation Tracker"] },
  ],
  auditChecklist: [
    { domain:"Governance & Leadership", icon:"🏛", items:[
      { item:"Board-approved Cybersecurity Policy in place, reviewed within 12 months", required:true },
      { item:"CISO designated — mandatory for MIIs, with Board-level access", required:true },
      { item:"Cybersecurity Risk Committee constituted and meeting regularly", required:true },
      { item:"Annual Cybersecurity Strategy submitted to SEBI (for MIIs)", required:true },
      { item:"Board receives quarterly cybersecurity KPI report", required:true },
    ]},
    { domain:"Trading System Security", icon:"📈", items:[
      { item:"Trading network segmented from corporate network", required:true },
      { item:"DDoS protection deployed for trading platform (mandatory for MIIs)", required:true },
      { item:"OMS and RMS hardened against unauthorized access", required:true },
      { item:"API security controls for algorithmic trading integrations", required:true },
      { item:"Secure file transfer (SFTP/encrypted) for exchange data feeds", required:true },
    ]},
    { domain:"SOC / CSIRT Operations", icon:"📡", items:[
      { item:"CSIRT constituted and registered with SEBI CIRT", required:true },
      { item:"24x7 SOC monitoring operational (mandatory for MIIs)", required:true },
      { item:"SIEM deployed with market-specific use cases", required:true },
      { item:"6-hour initial incident reporting SLA to SEBI CIRT enforced", required:true },
      { item:"Playbooks tested for: DDoS, trading outage, data breach scenarios", required:true },
    ]},
    { domain:"Risk Management & Third Party", icon:"⚠", items:[
      { item:"Annual cyber risk assessment conducted and documented", required:true },
      { item:"TPSP risk assessments completed for all critical technology vendors", required:true },
      { item:"Security SLAs in all critical vendor contracts", required:true },
      { item:"Right-to-audit clause in critical vendor agreements", required:false },
    ]},
    { domain:"Business Continuity & Resilience", icon:"🔄", items:[
      { item:"BCP/DR plan tested annually — trading system RTO ≤ 2h for MIIs", required:true },
      { item:"DDoS simulation conducted in the last 12 months", required:true },
      { item:"Cyber resilience tabletop exercise conducted annually", required:true },
      { item:"Settlement system resilience validated", required:true },
    ]},
    { domain:"Compliance & Audit", icon:"📋", items:[
      { item:"Annual VAPT by CERT-In empanelled firm covering trading infrastructure", required:true },
      { item:"Annual Cybersecurity Compliance Report submitted to SEBI", required:true },
      { item:"All audit findings remediated within timelines approved by Board", required:true },
      { item:"Incident reports submitted within 6h initial / 24h detailed timelines", required:true },
    ]},
  ],
  templateDetails: [
    { name:"SEBI CSCRF Control Compliance Matrix", description:"Master tracker mapping all 61 SEBI CSCRF controls to implementation status and evidence", required:true, type:"checklist" },
    { name:"CISO Appointment Order", description:"Formal appointment letter for CISO with mandate, reporting line and authorities", required:true, type:"form" },
    { name:"Annual Cybersecurity Strategy (SEBI Submission)", description:"Annual cybersecurity strategy document in SEBI-prescribed format for MII submission", required:true, type:"report" },
    { name:"Cyber Incident Report Format (6h / 24h)", description:"SEBI CIRT incident report template with 6-hour initial and 24-hour detailed reporting fields", required:true, type:"form" },
    { name:"CSIRT Charter", description:"Formal CSIRT constitution with roles, responsibilities, escalation matrix and contact directory", required:true, type:"policy" },
    { name:"Annual Cybersecurity Compliance Report (ACCR)", description:"Comprehensive annual compliance report for SEBI submission covering all CSCRF domains", required:true, type:"report" },
    { name:"Trading System VAPT Scope Document", description:"Scope statement for annual VAPT covering trading platform, OMS, RMS, APIs and web portals", required:true, type:"form" },
    { name:"DDoS Resilience Test Report Template", description:"Structured report format for documenting DDoS simulation exercises and outcomes", required:true, type:"report" },
    { name:"Third-Party / TPSP Security Assessment Questionnaire (Capital Markets)", description:"Capital-markets-specific security questionnaire for technology vendors and data providers", required:true, type:"assessment" },
    { name:"Cyber Resilience Tabletop Exercise Script (SEBI Scenario)", description:"Pre-designed tabletop exercise scenario based on SEBI CSCRF threat scenarios", required:true, type:"form" },
    { name:"Board Cybersecurity Presentation Template", description:"Quarterly Board-level cybersecurity KPI dashboard in PowerPoint format", required:false, type:"report" },
  ],
};

const IN_IRDAI: FrameworkDetail = {
  frameworkId: "in_irdai",
  certificationBody: "IRDAI-Approved Information Security Auditor",
  totalDuration: "12–18 months (initial); annual audit cycle thereafter",
  applicableTo: "All IRDAI-regulated entities: Life Insurers, General Insurers, Health Insurers, Reinsurers, TPAs and Insurance Intermediaries",
  implementationPhases: [
    { phase:1, title:"Governance Foundation & CISO Appointment", icon:"🏛", timeframe:"Weeks 1–4",
      description:"Establish Board-level cybersecurity governance, appoint CISO, form IT Security Committee and draft the cybersecurity policy per IRDAI guidelines.",
      tasks:[
        "Draft and obtain Board approval for Information and Cybersecurity Policy",
        "Appoint CISO — mandatory under IRDAI guidelines; CISO must report to MD/CEO or Board",
        "Constitute IT Security Committee with quarterly meeting cadence",
        "Define cybersecurity budget (minimum percentage of IT spend)",
        "Define Annual Cybersecurity Strategy",
        "Create IRDAI incident reporting escalation matrix (24h reporting SLA)",
        "Register with CERT-In for incident reporting if not already done",
      ],
      deliverables:["Board-Approved Information & Cybersecurity Policy","CISO Appointment Letter","IT Security Committee Charter","Annual Cybersecurity Strategy","IRDAI Escalation Matrix"] },
    { phase:2, title:"Risk Assessment & Critical Asset Classification", icon:"⚠", timeframe:"Weeks 5–10",
      description:"Conduct comprehensive IT and cyber risk assessment, identify and classify critical insurance systems and policyholder data assets.",
      tasks:[
        "Identify and classify critical insurance systems: Core Insurance Platform, Policy Administration System (PAS), Claims Management, Reinsurance Treaty System",
        "Classify policyholder data (personal, health, financial, biometric) by sensitivity",
        "Map data flows from agents, intermediaries, TPAs, hospitals and customers",
        "Conduct cyber risk assessment using IRDAI-aligned risk methodology",
        "Conduct third-party / outsourced service provider risk assessment",
        "Define Risk Appetite Statement",
        "Produce Risk Treatment Plan with priorities and timelines",
      ],
      deliverables:["Critical Asset Register (Insurance Systems)","Data Classification Register","Data Flow Map","Cyber Risk Assessment Report","Third-Party Risk Assessment Report","Risk Treatment Plan"] },
    { phase:3, title:"Technical Controls Implementation", icon:"🛡", timeframe:"Weeks 8–22",
      description:"Deploy technical security controls for insurance systems, customer portals, mobile apps and agent-facing interfaces.",
      tasks:[
        "Deploy network segmentation (core insurance, DMZ, agent portal, customer portal zones)",
        "Implement WAF for all internet-facing insurance portals (policy purchase, claims)",
        "Conduct VAPT on web portals, mobile insurance apps and agent interfaces",
        "Implement MFA for all admin access and customer-facing portals",
        "Deploy Privileged Access Management (PAM) for admin accounts",
        "Implement encryption for policyholder data at rest and in transit",
        "Deploy DLP to prevent policyholder data exfiltration",
        "Implement anti-fraud analytics for motor, life and health insurance claims",
        "Endpoint Detection & Response (EDR) on all endpoints processing policyholder data",
        "Implement patch management programme with SLA tracking",
      ],
      deliverables:["Network Architecture Diagram (Segmented)","WAF Deployment Evidence","VAPT Report (Web & Mobile)","MFA Deployment Evidence","Encryption Implementation Evidence","DLP Policy & Deployment","Anti-Fraud Controls Documentation"] },
    { phase:4, title:"SOC, Monitoring & Fraud Detection", icon:"📡", timeframe:"Weeks 12–22",
      description:"Establish SOC with 24x7 monitoring capability, SIEM deployment and fraud detection analytics specific to insurance sector.",
      tasks:[
        "Define SOC operating model (internal or outsourced to CERT-In empanelled MSSP)",
        "Deploy SIEM with insurance-specific use cases (claims fraud, identity theft, portal attacks)",
        "Configure log collection from all critical insurance systems and customer portals",
        "Deploy fraud detection and analytics for claims processing",
        "Configure alerts for anomalous claim patterns, duplicate claims, identity fraud",
        "Test SOC detection coverage with insurance-specific attack scenarios",
        "Establish 24x7 monitoring for customer portals and payment systems",
      ],
      deliverables:["SOC Charter","SIEM Use Cases (Insurance-Specific)","Fraud Detection System Evidence","Log Source Inventory","SOC Test Report"] },
    { phase:5, title:"Business Continuity & Disaster Recovery", icon:"🔄", timeframe:"Weeks 18–26",
      description:"Ensure continuity of critical insurance operations (claims, policy issuance, reinsurance) through BCP/DRP testing and cyber crisis exercises.",
      tasks:[
        "Update Business Impact Analysis for critical insurance operations",
        "Test Core Insurance Platform DR — RTO/RPO per IRDAI guidelines",
        "Test claims processing continuity — critical for life and health insurance",
        "Conduct Cyber Crisis Management tabletop exercise with senior management",
        "Test TPA (Third Party Administrator) connectivity resilience",
        "Test hospital network access resilience for health insurance claims",
        "Validate customer portal failover for online policy purchase and renewal",
      ],
      deliverables:["BIA Report (Insurance Operations)","DR Test Report (Core Insurance Platform)","Claims Processing BCP Test Report","Cyber Crisis Tabletop Exercise Report"] },
    { phase:6, title:"Annual IRDAI Audit & Compliance Reporting", icon:"📋", timeframe:"Annual Cycle",
      description:"Conduct annual cybersecurity audit, submit compliance report to IRDAI and maintain continuous improvement programme.",
      tasks:[
        "Engage CERT-In empanelled / IRDAI-approved cybersecurity auditor for annual audit",
        "Conduct comprehensive VAPT covering insurance systems, portals and mobile apps",
        "Prepare Annual Cybersecurity Compliance Report for IRDAI submission",
        "Submit cyber incident reports to IRDAI within 24 hours of discovery",
        "Conduct Board-level Annual Cybersecurity Review",
        "Remediate all audit findings within IRDAI-prescribed timelines",
        "Update cybersecurity risk register and submit updated risk profile to IRDAI",
        "Review and update all cybersecurity policies annually",
      ],
      deliverables:["Annual VAPT Report","Annual Cybersecurity Compliance Report (IRDAI)","Board Cybersecurity Review Minutes","IRDAI Incident Reports","Audit Finding Remediation Tracker"] },
  ],
  auditChecklist: [
    { domain:"Governance & Board Accountability", icon:"🏛", items:[
      { item:"Board-approved Information & Cybersecurity Policy in place", required:true },
      { item:"CISO appointed with Board/MD reporting line", required:true },
      { item:"IT Security Committee constituted with quarterly meetings", required:true },
      { item:"Board receives cybersecurity report at least annually", required:true },
      { item:"Cybersecurity budget approved and tracked against utilisation", required:true },
    ]},
    { domain:"Policyholder Data Protection", icon:"🔐", items:[
      { item:"All policyholder data classified by sensitivity (personal, health, financial)", required:true },
      { item:"Encryption applied to policyholder data at rest and in transit", required:true },
      { item:"Access to policyholder data restricted to authorised personnel only", required:true },
      { item:"Policyholder data retention and deletion policy implemented", required:true },
      { item:"Privacy policy for customers complies with DPDP Act / IT Act", required:true },
    ]},
    { domain:"Application & Portal Security", icon:"💻", items:[
      { item:"Annual VAPT on insurance web portals (policy purchase, claims, payments)", required:true },
      { item:"Annual VAPT on mobile insurance application", required:true },
      { item:"WAF deployed for all internet-facing insurance portals", required:true },
      { item:"MFA enforced for customer logins on digital channels", required:true },
      { item:"API security controls for agent and intermediary integrations", required:true },
    ]},
    { domain:"Fraud Detection & Anti-Fraud Controls", icon:"🔍", items:[
      { item:"Anti-fraud analytics deployed for claims processing", required:true },
      { item:"Duplicate claims detection mechanism operational", required:true },
      { item:"Suspicious claims flagging and investigation process defined", required:false },
      { item:"Identity verification for new policy issuance implemented", required:true },
    ]},
    { domain:"SOC & Incident Response", icon:"🚨", items:[
      { item:"SOC operational (24x7 for large insurers)", required:true },
      { item:"Incident Response Plan documented and tested annually", required:true },
      { item:"IRDAI incident reporting within 24 hours of discovery", required:true },
      { item:"Cyber Crisis Management tabletop exercise conducted annually", required:true },
      { item:"Incident log maintained with all required fields", required:true },
    ]},
    { domain:"Business Continuity (Insurance Operations)", icon:"🔄", items:[
      { item:"BCP/DRP covers all critical insurance operations (claims, policy issuance)", required:true },
      { item:"Core Insurance Platform DR test conducted in the last 12 months", required:true },
      { item:"Claims processing continuity tested (critical for health insurance)", required:true },
      { item:"TPA connectivity resilience tested", required:false },
      { item:"RTO/RPO for critical systems met during DR testing", required:true },
    ]},
    { domain:"Third-Party & Outsourcing Risk", icon:"🤝", items:[
      { item:"IT service provider / cloud provider security assessments completed", required:true },
      { item:"TPA (Third Party Administrator) security assessments completed", required:true },
      { item:"Insurance intermediary access controls reviewed annually", required:true },
      { item:"Contractual security SLAs in all critical vendor agreements", required:true },
    ]},
    { domain:"Compliance & Regulatory Reporting", icon:"📋", items:[
      { item:"Annual cybersecurity audit by IRDAI-approved auditor completed", required:true },
      { item:"Annual Cybersecurity Compliance Report submitted to IRDAI", required:true },
      { item:"All audit findings remediated within prescribed timelines", required:true },
      { item:"Annual IT/Cybersecurity Return submitted to IRDAI", required:true },
      { item:"Staff cybersecurity awareness training completed annually", required:true },
    ]},
  ],
  templateDetails: [
    { name:"Board Information & Cybersecurity Policy (IRDAI)", description:"IRDAI-compliant board-level policy covering governance, risk, controls and annual review", required:true, type:"policy" },
    { name:"CISO Charter & Appointment Order", description:"CISO formal appointment with mandate, reporting structure, authorities and KPIs", required:true, type:"form" },
    { name:"Cyber Risk Assessment Report (Insurance)", description:"Structured risk assessment covering insurance-specific threats: policyholder data breach, claims fraud, portal attacks", required:true, type:"assessment" },
    { name:"Annual Cybersecurity Audit Checklist (IRDAI)", description:"Comprehensive audit checklist aligned to IRDAI cybersecurity guidelines, organised by domain", required:true, type:"checklist" },
    { name:"Insurance Portal VAPT Scope Document", description:"Scope definition for annual VAPT covering policy portal, claims portal, mobile app and agent interfaces", required:true, type:"form" },
    { name:"Cyber Incident Report Template (IRDAI 24h)", description:"Structured incident report format for IRDAI notification within 24 hours of incident discovery", required:true, type:"form" },
    { name:"Anti-Fraud Controls Assessment", description:"Assessment of fraud detection controls for motor, life and health insurance claims", required:true, type:"assessment" },
    { name:"BCP Test Report (Core Insurance Platform)", description:"Structured report for annual BCP/DR test results against defined RTO/RPO targets", required:true, type:"report" },
    { name:"Third-Party / TPA Security Assessment Questionnaire", description:"Security questionnaire for Third Party Administrators, IT outsourcing providers and cloud providers", required:true, type:"assessment" },
    { name:"Annual Cybersecurity Compliance Report (IRDAI)", description:"Comprehensive annual report for IRDAI submission, covering all guideline domains with evidence references", required:true, type:"report" },
    { name:"IT Security Committee Minutes Template", description:"Quarterly meeting agenda and minutes template for IT Security Committee", required:true, type:"report" },
  ],
};

const IN_CERTIN: FrameworkDetail = {
  frameworkId: "in_certin",
  certificationBody: "CERT-In (no external certification; self-attested compliance)",
  totalDuration: "3–6 months (initial setup); ongoing compliance",
  applicableTo: "All Service Providers, Intermediaries, Data Centres, Body Corporates and Government Organisations in India operating IT infrastructure",
  implementationPhases: [
    { phase:1, title:"Applicability Assessment & CERT-In Registration", icon:"🎯", timeframe:"Weeks 1–2",
      description:"Assess organisational applicability of CERT-In Directions 2022, identify all 20 reportable incident types and register with CERT-In.",
      tasks:[
        "Confirm applicability of CERT-In Directions 2022 to the organisation",
        "Map all 20 types of cyber incidents mandated for reporting under the Directions",
        "Register organisation with CERT-In portal for incident reporting",
        "Identify Point of Contact (PoC) for CERT-In incident reporting",
        "Assess current incident detection and reporting capabilities against 6-hour requirement",
        "Review existing log retention policies against 180-day minimum requirement",
      ],
      deliverables:["Applicability Assessment Document","CERT-In Portal Registration Confirmation","PoC Details Registration","20 Incident Types Mapping","Gap Assessment against 6h Reporting SLA"] },
    { phase:2, title:"Incident Reporting System Setup", icon:"🚨", timeframe:"Weeks 3–8",
      description:"Implement the capability to detect, classify and report all 20 types of cyber incidents to CERT-In within the mandatory 6-hour window.",
      tasks:[
        "Deploy or upgrade SIEM to detect all 20 CERT-In reportable incident types",
        "Define incident classification matrix mapping internal incidents to CERT-In's 20 categories",
        "Create 6-hour incident reporting procedure with clear roles and escalation paths",
        "Draft Incident Report template pre-formatted for CERT-In portal submission",
        "Establish 24x7 on-call roster for incident response and reporting",
        "Test end-to-end reporting workflow with simulated incident scenario",
        "Train security team and management on 6-hour reporting obligation and consequences",
      ],
      deliverables:["CERT-In Incident Classification Matrix (20 Types)","6-Hour Reporting Procedure","Incident Report Template (CERT-In Format)","On-Call Roster","Reporting Workflow Test Evidence","Staff Training Completion Records"] },
    { phase:3, title:"Log Retention & NTP Synchronisation", icon:"🗄", timeframe:"Weeks 3–10",
      description:"Implement compliant log retention (minimum 180 days) and mandatory NTP synchronisation to Indian Standard Time (IST) across all ICT systems.",
      tasks:[
        "Audit all ICT systems for log generation capability — identify gaps",
        "Deploy or upgrade log management / SIEM to retain logs for minimum 180 days (1 year recommended for financial entities)",
        "Configure centralised log collection for all critical systems (firewalls, servers, applications, network devices, endpoints)",
        "Implement NTP synchronisation across all ICT systems using IST-aligned NTP servers",
        "Configure NTP monitoring alerts for drift detection",
        "Document log retention policy with system-specific retention periods",
        "Test log completeness and integrity monthly",
      ],
      deliverables:["Log Retention Policy","Log Management System Configuration Evidence","NTP Synchronisation Evidence (all systems)","Log Completeness Verification Report","System-wise Log Retention Schedule"] },
    { phase:4, title:"VPN / Cloud / Virtual Asset KYC Records", icon:"🔑", timeframe:"Weeks 5–10",
      description:"Implement and maintain subscriber information records for VPN services, cloud accounts and virtual asset transactions as required by CERT-In Directions.",
      tasks:[
        "Inventory all VPN services used by the organisation and employees",
        "Establish VPN subscriber records — name, IP address assignment, usage logs — retain for 5 years",
        "Inventory all cloud service provider (CSP) accounts and subscriptions",
        "Maintain cloud account subscriber information records — retain for 5 years",
        "If Virtual Asset Service Provider (VASP): maintain KYC records for all customers for 5 years",
        "Define process for maintaining and updating subscriber records",
        "Ensure records are available for CERT-In access upon request",
      ],
      deliverables:["VPN Subscriber Records Register","Cloud CSP Account Register","VASP KYC Records (if applicable)","5-Year Retention Policy for Subscriber Records","Records Access Procedure for CERT-In"] },
    { phase:5, title:"Staff Training & Awareness", icon:"🎓", timeframe:"Weeks 6–10",
      description:"Train all relevant staff on CERT-In Directions, incident identification, classification and 6-hour reporting obligations.",
      tasks:[
        "Develop targeted training material on CERT-In Directions 2022 for IT security, IT operations and management",
        "Train IT security team on 20 incident types and reporting procedures",
        "Train management on reporting obligations and penalties for non-compliance",
        "Conduct simulated incident exercise to test 6-hour reporting capability",
        "Document training completion records",
      ],
      deliverables:["CERT-In Directions Training Pack","Training Completion Records","Simulated Incident Exercise Report"] },
    { phase:6, title:"Annual Compliance Maintenance", icon:"🔄", timeframe:"Ongoing (Annual)",
      description:"Maintain ongoing compliance including annual compliance declaration, log review, incident reporting drills and monitoring of CERT-In updates.",
      tasks:[
        "Conduct annual compliance review against CERT-In Directions 2022",
        "Produce Annual Compliance Declaration if required by CERT-In",
        "Test incident reporting workflow with simulated drill annually",
        "Review log retention completeness — verify 180-day minimum maintained",
        "Verify NTP synchronisation across all systems quarterly",
        "Monitor CERT-In advisories and security alerts for emerging threats",
        "Update incident classification matrix if CERT-In adds new reportable incident types",
      ],
      deliverables:["Annual Compliance Declaration","Incident Reporting Drill Results","Log Retention Audit Report","NTP Compliance Verification Record","CERT-In Advisory Response Log"] },
  ],
  auditChecklist: [
    { domain:"Incident Reporting Capability", icon:"🚨", items:[
      { item:"Organisation registered on CERT-In portal for incident reporting", required:true },
      { item:"Point of Contact (PoC) registered with CERT-In and contact details current", required:true },
      { item:"All 20 CERT-In reportable incident types mapped to internal classification", required:true },
      { item:"6-hour reporting SLA capability demonstrated and tested", required:true },
      { item:"Incident report template formatted for CERT-In portal submission", required:true },
      { item:"24x7 on-call capability for incident detection and reporting in place", required:true },
    ]},
    { domain:"Log Retention", icon:"🗄", items:[
      { item:"All ICT systems generating logs in centralised log management system", required:true },
      { item:"Log retention minimum 180 days (6 months) — online or accessible", required:true },
      { item:"Log integrity protection implemented (tamper-evidence)", required:true },
      { item:"Log completeness verification conducted monthly", required:true },
      { item:"Log coverage includes: firewalls, servers, applications, network devices, endpoints", required:true },
    ]},
    { domain:"NTP Synchronisation (IST)", icon:"🕐", items:[
      { item:"All ICT systems synchronised to NTP servers using Indian Standard Time (IST)", required:true },
      { item:"NTP monitoring in place with drift detection alerts", required:true },
      { item:"NTP synchronisation verified and documented for all critical systems", required:true },
      { item:"NTP configuration review conducted quarterly", required:true },
    ]},
    { domain:"VPN & Cloud Subscriber Records", icon:"🔑", items:[
      { item:"VPN subscriber records maintained — name, IP, usage logs — 5-year retention", required:true },
      { item:"Cloud CSP account subscriber records maintained — 5-year retention", required:true },
      { item:"Virtual Asset Service Provider KYC records maintained (if applicable)", required:false },
      { item:"Subscriber records accessible to CERT-In upon legitimate request", required:true },
    ]},
    { domain:"Staff Awareness & Training", icon:"🎓", items:[
      { item:"IT security staff trained on 20 reportable incident types", required:true },
      { item:"Management trained on 6-hour reporting obligation and penalties", required:true },
      { item:"Simulated incident reporting exercise conducted in last 12 months", required:true },
    ]},
  ],
  templateDetails: [
    { name:"CERT-In Incident Report Template (6-Hour Format)", description:"Pre-formatted report template matching CERT-In portal fields for all 20 reportable incident types", required:true, type:"form" },
    { name:"20 Incident Types Classification Matrix", description:"Internal mapping of all 20 CERT-In Direction-mandated incident types with detection triggers and examples", required:true, type:"checklist" },
    { name:"6-Hour Reporting Procedure (SOP)", description:"Step-by-step SOP for detecting, classifying and reporting incidents to CERT-In within 6 hours", required:true, type:"procedure" },
    { name:"Log Retention Policy", description:"Policy defining minimum retention periods for all ICT system log types (minimum 180 days per CERT-In Directions)", required:true, type:"policy" },
    { name:"NTP Synchronisation Configuration Template", description:"NTP configuration template for IST-aligned synchronisation, including IST NTP server addresses", required:true, type:"procedure" },
    { name:"VPN Subscriber Records Register", description:"Register template for maintaining VPN subscriber details with 5-year retention, per CERT-In requirements", required:true, type:"register" },
    { name:"Cloud CSP Account Register", description:"Register template for all cloud service provider accounts and subscriber information", required:true, type:"register" },
    { name:"Annual Compliance Declaration", description:"Declaration form for annual CERT-In compliance self-attestation", required:true, type:"form" },
    { name:"Incident Reporting Drill Script", description:"Annual drill scenario to test the 6-hour incident reporting capability end-to-end", required:false, type:"form" },
  ],
};

// ── GLOBAL FRAMEWORKS (Key ones with detailed data) ──────────────────────────

const ISO27001_DETAIL: FrameworkDetail = {
  frameworkId: "iso27001",
  certificationBody: "Accredited Certification Body (e.g., BSI, Bureau Veritas, SGS, DNV)",
  totalDuration: "12–18 months (initial certification); 3-year certification cycle with annual surveillance",
  applicableTo: "Any organisation of any size or sector seeking ISO 27001 certification or alignment",
  implementationPhases: [
    { phase:1, title:"Initiation & Project Planning", icon:"🎯", timeframe:"Weeks 1–4",
      description:"Secure leadership buy-in, define the ISMS project scope, form the ISMS project team and develop the project plan.",
      tasks:[
        "Secure executive sponsorship and Board/management commitment (Clause 5.1)",
        "Define ISMS scope — organisational boundaries, assets, locations, processes (Clause 4.3)",
        "Appoint ISMS Project Manager / CISO with adequate authority and resource",
        "Form Cross-Functional ISMS Working Group",
        "Develop detailed ISMS Implementation Project Plan with milestones",
        "Conduct ISMS awareness kick-off for all staff",
        "Select target Certification Body (CB) and obtain indicative certification timeline",
      ],
      deliverables:["Management Commitment Statement","ISMS Scope Statement","Project Charter","ISMS Project Plan","CB Selection Rationale"] },
    { phase:2, title:"Context, Interested Parties & Risk Methodology", icon:"📋", timeframe:"Weeks 4–8",
      description:"Document organisational context, identify interested parties, define risk assessment and treatment methodology, and state risk appetite.",
      tasks:[
        "Document internal and external issues (Clause 4.1) — PESTLE / SWOT analysis",
        "Identify all interested parties and their requirements (Clause 4.2)",
        "Draft Risk Assessment Methodology (ISO 27005 recommended) — Clause 6.1.2",
        "Define Risk Acceptance Criteria and Risk Appetite Statement",
        "Conduct initial asset inventory (supporting Annex A control implementation)",
        "Define information security objectives (Clause 6.2) — measurable, aligned to strategy",
      ],
      deliverables:["Organisational Context Document","Interested Parties Register","Risk Assessment Methodology","Risk Appetite Statement","Information Security Objectives","Asset Register (Initial)"] },
    { phase:3, title:"Risk Assessment & Treatment", icon:"⚠", timeframe:"Weeks 8–14",
      description:"Conduct formal risk assessment across all in-scope assets and produce risk treatment plan aligned to Annex A controls.",
      tasks:[
        "Execute risk assessment — identify threats, vulnerabilities and impacts for all assets",
        "Assess likelihood and impact; calculate risk level using agreed methodology",
        "Evaluate risks against acceptance criteria; identify all unacceptable risks",
        "Select appropriate Annex A controls for each unacceptable risk",
        "Produce Risk Treatment Plan with owners, timelines and residual risk",
        "Obtain management sign-off on Risk Treatment Plan",
        "Prepare initial Statement of Applicability (SOA) based on risk treatment decisions",
      ],
      deliverables:["Risk Assessment Report","Risk Register","Risk Treatment Plan","Initial Statement of Applicability (SOA)","Risk Owner Assignments"] },
    { phase:4, title:"Policy & Document Framework", icon:"📝", timeframe:"Weeks 10–18",
      description:"Develop all mandatory ISMS documentation including policies, procedures, standards and records required by ISO 27001:2022.",
      tasks:[
        "Draft Information Security Policy (Clause 5.2) — Board-approved",
        "Develop all supporting policies: Access Control, Cryptography, Physical Security, Supplier Relations, Incident Management, Business Continuity, HR Security",
        "Create ISMS Manual covering all clause requirements",
        "Develop procedures: Risk Assessment, Internal Audit, CAPA, Document Control, Competence",
        "Establish Document Management System with version control and approval workflow",
        "Conduct document review cycle — technical and management review, approval",
      ],
      deliverables:["Information Security Policy","Supporting Policy Pack (15+ policies)","ISMS Manual","Procedure Library","Document Control Register","Approved Document Set"] },
    { phase:5, title:"Annex A Control Implementation", icon:"⚙", timeframe:"Weeks 12–26",
      description:"Implement all applicable controls from ISO 27001:2022 Annex A (93 controls across 4 themes) as documented in the SOA.",
      tasks:[
        "Implement Organisational Controls (Clause A.5 — 37 controls): policies, roles, asset management, supplier security, information classification",
        "Implement People Controls (Clause A.6 — 8 controls): screening, terms, awareness, training, disciplinary, remote working",
        "Implement Physical Controls (Clause A.7 — 14 controls): physical security, secure areas, clear desk, equipment security",
        "Implement Technological Controls (Clause A.8 — 34 controls): endpoint protection, access management, cryptography, network security, SIEM, incident management, DLP, threat intelligence",
        "Update SOA with actual implementation status for each control",
        "Collect evidence of control implementation for all applicable controls",
        "Track control implementation progress against project plan",
      ],
      deliverables:["Final Statement of Applicability (SOA)","Control Implementation Evidence Pack","Control Testing Checklist","Access Control Matrix","Asset Classification Register","Supplier Security Register"] },
    { phase:6, title:"Internal Audit & Management Review", icon:"🔍", timeframe:"Weeks 24–30",
      description:"Conduct comprehensive internal audit against all Clauses 4–10 and Annex A, then hold formal management review.",
      tasks:[
        "Develop Internal Audit Programme (Clause 9.2) covering all ISMS clauses and Annex A controls",
        "Conduct internal audit using qualified lead auditor (trained to ISO 19011)",
        "Document audit findings, non-conformities and observations",
        "Issue Non-Conformity Reports (NCRs) and initiate corrective actions",
        "Close all major NCRs before Stage 2 certification audit",
        "Conduct Management Review (Clause 9.3) — scope, risk results, audit results, objectives, continual improvement",
        "Produce Management Review Record with decisions and action items",
      ],
      deliverables:["Internal Audit Programme","Internal Audit Report","Non-Conformity Reports (NCRs)","CAPA Tracker","Management Review Record","Corrective Action Evidence"] },
    { phase:7, title:"Certification Audit (Stage 1 & Stage 2)", icon:"🏆", timeframe:"Weeks 28–36",
      description:"Undergo Stage 1 documentation review and Stage 2 on-site certification audit by the accredited Certification Body.",
      tasks:[
        "Submit ISMS documentation to CB for Stage 1 document review",
        "Respond to Stage 1 findings and update documentation as required",
        "Schedule and prepare for Stage 2 on-site audit",
        "Prepare evidence packs for all in-scope controls and clauses",
        "Brief all audit interviewees (process owners, IT team, HR, management)",
        "Support Stage 2 audit — interviews, observations, document inspection",
        "Respond to any Stage 2 minor non-conformities within agreed timeline",
        "Receive ISO 27001:2022 certification",
      ],
      deliverables:["Stage 1 Audit Readiness Pack","Stage 2 Evidence Packs","Interviewee Briefing Pack","Minor NC Responses","ISO 27001:2022 Certificate"] },
  ],
  auditChecklist: [
    { domain:"Leadership & Context (Clauses 4–6)", icon:"🏛", items:[
      { item:"Clause 4.1 — Internal/external issues documented and reviewed annually", required:true },
      { item:"Clause 4.2 — Interested parties and their requirements documented", required:true },
      { item:"Clause 4.3 — ISMS scope documented with clear boundaries and exclusions justified", required:true },
      { item:"Clause 5.1 — Evidence of top management commitment to ISMS", required:true },
      { item:"Clause 5.2 — Information Security Policy Board-approved and communicated", required:true },
      { item:"Clause 5.3 — ISMS roles, responsibilities and authorities assigned and communicated", required:true },
      { item:"Clause 6.1 — Risk Assessment Methodology documented; Clause 6.2 — Objectives set", required:true },
    ]},
    { domain:"Risk Management (Clause 6 & 8)", icon:"⚠", items:[
      { item:"Clause 6.1.2 — Risk assessment completed for all in-scope assets within 12 months", required:true },
      { item:"Clause 6.1.3 — Risk treatment plan documented with control selections justified", required:true },
      { item:"Clause 6.1.3 — Statement of Applicability (SOA) complete with justifications for all 93 Annex A controls", required:true },
      { item:"Clause 8.2 — Risk assessment results documented", required:true },
      { item:"Clause 8.3 — Risk treatment plan being implemented; residual risk accepted", required:true },
    ]},
    { domain:"Operations (Clause 8 — Annex A)", icon:"⚙", items:[
      { item:"All applicable Annex A Organisational Controls (A.5) implemented with evidence", required:true },
      { item:"All applicable Annex A People Controls (A.6) implemented with evidence", required:true },
      { item:"All applicable Annex A Physical Controls (A.7) implemented with evidence", required:true },
      { item:"All applicable Annex A Technological Controls (A.8) implemented with evidence", required:true },
      { item:"Clause 8.1 — Operational processes planned, implemented and controlled", required:true },
    ]},
    { domain:"Performance Evaluation (Clause 9)", icon:"📊", items:[
      { item:"Clause 9.1 — ISMS performance monitored and measured against defined metrics", required:true },
      { item:"Clause 9.2 — Internal audit programme completed; auditors qualified", required:true },
      { item:"Clause 9.2 — Internal audit findings documented and tracked to closure", required:true },
      { item:"Clause 9.3 — Management review conducted; record of agenda items and decisions", required:true },
    ]},
    { domain:"Improvement (Clause 10)", icon:"🔄", items:[
      { item:"Clause 10.1 — Non-conformities documented; root cause analysis completed", required:true },
      { item:"Clause 10.1 — Corrective actions implemented and verified as effective", required:true },
      { item:"Clause 10.2 — Continual improvement programme active with improvement register", required:true },
    ]},
  ],
  templateDetails: [
    { name:"ISMS Scope Statement", description:"Defines the ISMS boundary, assets, locations and processes in scope (Clause 4.3)", required:true, type:"policy" },
    { name:"Information Security Policy (Board-Approved)", description:"Top-level information security policy meeting all Clause 5.2 requirements", required:true, type:"policy" },
    { name:"Risk Assessment Methodology", description:"Documented risk assessment approach aligned to ISO 27005, covering identification, analysis and evaluation", required:true, type:"procedure" },
    { name:"Risk Register", description:"Structured register of all identified information security risks with likelihood, impact, owner and treatment", required:true, type:"register" },
    { name:"Statement of Applicability (SOA)", description:"ISO 27001 SOA covering all 93 Annex A controls with applicability decisions and implementation status", required:true, type:"register" },
    { name:"Risk Treatment Plan", description:"Plan linking each unacceptable risk to selected Annex A controls, with implementation owner and timeline", required:true, type:"plan" },
    { name:"Asset Register", description:"Register of all information assets within scope with classification, owner and risk rating", required:true, type:"register" },
    { name:"Internal Audit Programme & Report", description:"Annual audit programme schedule and structured audit report template covering all ISMS clauses", required:true, type:"report" },
    { name:"Non-Conformity Report (NCR) Template", description:"Standardised NCR form with finding description, clause reference, objective evidence and CAPA tracking", required:true, type:"form" },
    { name:"Management Review Minutes Template", description:"Formal management review meeting agenda and minutes, covering all Clause 9.3 mandatory agenda items", required:true, type:"report" },
    { name:"ISMS Policy Pack (15 Policies)", description:"Complete set of supporting policies: Access Control, Cryptography, Physical Security, Supplier, Incident, BCP, HR Security, Acceptable Use, BYOD, Remote Work, Mobile Device, Clear Desk, Logging, Change Management, Patch Management", required:true, type:"policy" },
    { name:"Supplier / Third-Party Security Agreement", description:"Security clauses for supplier contracts and SLAs (Annex A.5.19-A.5.22)", required:true, type:"policy" },
  ],
};

// ── FRAMEWORK DETAIL MAP ─────────────────────────────────────────────────────
const DETAIL_MAP: Record<string, FrameworkDetail> = {
  in_dpdp:  IN_DPDP,
  in_rbi:   IN_RBI,
  in_sebi:  IN_SEBI,
  in_irdai: IN_IRDAI,
  in_certin:IN_CERTIN,
  iso27001: ISO27001_DETAIL,
};

export function getFrameworkDetail(frameworkId: string): FrameworkDetail {
  return DETAIL_MAP[frameworkId] ?? {
    ...GENERIC_DETAIL,
    frameworkId,
  };
}
