// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/grc-dashboard/ArchDiagram.tsx": () => import("../components/mockups/grc-dashboard/ArchDiagram.tsx"),
  "./components/mockups/grc-dashboard/VariantA.tsx": () => import("../components/mockups/grc-dashboard/VariantA.tsx"),
  "./components/mockups/grc-dashboard/VariantB.tsx": () => import("../components/mockups/grc-dashboard/VariantB.tsx")
};
