apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: aigo-x
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: aigo-x
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 8001
      targetPort: http
      protocol: TCP
